### ISSUE TITLE
doc missing: Action_DNAionTracker

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#101]
I can not find its doc in AT15 man. 

it's at least 3 year old: http://archive.ambermd.org/201301/0100.html

**Comment by drroe** [comment]
This is why the Action is currently not enabled (see `Command.cpp`, the `Commands[]` array). It's an experimental Action originally in ptraj which Tom started developing and I started porting but was never finished.

**Comment by hainm** [comment]
ok bro. Next time I will check `Command.cpp` rather `ls Action*cpp`
