### ISSUE TITLE
Feature request:SPLIT PDB files per frame using trajout command

### ISSUE THREAD

**Issue by ghost** [Amber-MD/cpptraj#1011]
Hi Dan,

Just wondering if we can do a per frame print out of pdb file rather than using trajout to print a gigantic file containing 1000+frames.
Is this possible with the current version of cpptraj where the user can give in a netcdf file and use cpptraj to print out each frame as a separate pdb for visualization?
Thanks

**Comment by drroe** [comment]
Hopefully `multi` resolved the issue. If not please feel free to reopen the thread.
