### ISSUE TITLE
configure error 

### ISSUE THREAD

**Issue by mayank-kohli** [Amber-MD/cpptraj#1021]
Hi, I am getting the following error:
![image](https://user-images.githubusercontent.com/64058587/225604518-6a85970a-addd-4117-8e43-57c49b4a67ae.png)
![image](https://user-images.githubusercontent.com/64058587/225604515-8a390ebe-970c-4c67-8a3c-020e428200d7.png)

**Comment by drroe** [comment]
Can you provide your complete `configure` line?

**Comment by mayank-kohli** [comment]
./configure -cuda CUDA_HOME=/usr/local/cuda-11.7/ -shared

**Comment by drroe** [comment]
I think what may be happening here is that you initially ran `configure` without the `-shared` option, so all your libraries that `configure` built (like HDF5) were built without shared support. Try running without the `-shared` option, or remove everything from the `$CPPTRAJHOME/lib` directory and rebuild everything with `-shared` on, e.g.
```
CUDA_HOME=/usr/local/cuda-11.7 ./configure --buildlibs -shared -cuda
```
Hopefully that will do the trick.

**Comment by mayank-kohli** [comment]
![image](https://user-images.githubusercontent.com/64058587/226243948-4037c9e2-9a75-4901-b5ea-7684a726319b.png)
still getting the same error

**Comment by drroe** [comment]
Strange - I've never encountered this error before. My guess is that for some reason on your system, when cpptraj builds the HDF5 library it's dynamically linking to an existing libcurl, whereas on all the systems I've tested this on this doesn't happen for some reason. What if you add `-lcurl` to the LDFLAGS variable? E.g.:
```
LDFLAGS=-lcurl CUDA_HOME=/usr/local/cuda-11.7 ./configure --buildlibs -shared -cuda 
```

**Comment by mayank-kohli** [comment]
Hi the issue got resolved I was able to configure it.
But after make install, when I ran make check, I got this error.

![image](https://user-images.githubusercontent.com/64058587/226524415-ed8ba430-9360-4466-9942-77e8383ef813.png)

**Comment by mayank-kohli** [comment]
I have one more thing to add, the link for netcdf mentioned in config file is not working.

**Comment by mayank-kohli** [comment]
1. I did source the CPPTRAJ.
2. I am using ubuntu 20.04
3.` uname -a`: Linux BIO-WK-025 5.14.0-1057-oem #64-Ubuntu SMP Mon Jan 23 17:02:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
4. Line worked: LDFLAGS=-lcurl CUDA_HOME=/usr/local/cuda-11.7 ./configure --buildlibs -shared -cuda 
5. cpptraj --defines : did not gave anyoutput
6. The `configure `file tries to download it but it fails after sometime, so I went to that particular link I was not able to to access it, the same versions(v4.6.1) are shifted to the github page.

**Comment by drroe** [comment]
> cpptraj --defines : did not gave anyoutput

This seems like a problem. I'm guessing `which cpptraj` returns nothing as well? If that's the case, your PATH environment variable was not properly set. Are you using C-shell? If that's the case then sourcing `cpptraj.sh` won't work, since that's set up for shells like bash, zsh, dash, etc.

If you have c-shell, try the following:
```
$> setenv CPPTRAJHOME "<directory containing cpptraj"
$> setenv PATH "$CPPTRAJHOME/bin:$PATH"
$> setenv LD_LIBRARY_PATH "$AMBERHOME/lib:$LD_LIBRARY_PATH"
```
And then try going to $CPPTRAJHOME/test/Test_General and executing `./RunTest.sh`. If that works, try running all the tests.

**Comment by mayank-kohli** [comment]
`$> setenv CPPTRAJHOME "<directory containing cpptraj"
$> setenv PATH "$CPPTRAJHOME/bin:$PATH"
$> setenv LD_LIBRARY_PATH "$AMBERHOME/lib:$LD_LIBRARY_PATH"`

After doing I am still getting anything after running `cpptraj --defines`

But when I ran cpptraj.cuda I got this:
![image](https://user-images.githubusercontent.com/64058587/226825495-f71c93d2-8e2c-4590-9faf-065e76d91c19.png)

**Comment by drroe** [comment]
> But when I ran #cpptraj.cuda I got this:

Yikes - I totally forgot you configured with `-cuda`, so of course `cpptraj.cuda` was produced instead of `cpptraj`. Try running `make test.cuda` instead of `make test`.

**Comment by drroe** [comment]
Since this hasn't been updated for a few months I'm hoping it was resolved. If not, please reopen it. Thanks!
