### ISSUE TITLE
Query regarding mask option

### ISSUE THREAD

**Issue by saikat0003** [Amber-MD/cpptraj#1022]
I want to estimate distance using chain id. So, i have tried the following input:

distance K210A-E97D  **::A:;210@NZ,HZ1,HZ2,HZ3 ::D:;97@OE1,OE2,CD** out rgs01-salt-210-lys-97-glu-1.dat

ACTION SETUP FOR PARM 'rgs01_renumber_only.pdb' (1 actions):
  0: [distance K210A-E97D ::A:;210@NZ,HZ1,HZ2,HZ3 ::D:;97@OE1,OE2,CD out rgs01-salt-210-lys-97-glu-1.dat]
	::A:;210@NZ,HZ1,HZ2,HZ3 (5086 atoms) to ::D:;97@OE1,OE2,CD (2130 atoms), imaged.
----- mmgbsa-rgs01-1-2-merge.nc (1-1000, 1) -----
 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Complete.

I have selected only 4 atoms. However, using chain id scheme, it choose 5086 atoms.
I want to know what will be the correct syntax for using chain ID?

**Comment by drroe** [comment]
Hi,

Try adding the 'and' (`&`) operator, e.g.
```
::A&:;210&@NZ,HZ1,HZ2,HZ3
```
which should mean "chain ID A and original residue number 210 and atoms NZ, HZ1, HZ2, HZ3".

**Comment by saikat0003** [comment]
Thank you so much. It works fine.
