### ISSUE TITLE
Guidance required on MD simulation

### ISSUE THREAD

**Issue by Saqlain5565** [Amber-MD/cpptraj#1029]
Hello Sir,

Hope you are having a good time there.
I am a MS/PhD integrated student in Gwanjgu insutitute of science and technology, south korea.
i recently started working on MD simulation , i am facing trouble in getting tip5p.pdb file.
kindly share the file if you have or share the process for making it .

i would really appreciate your help.

Saqlain

**Comment by Saqlain5565** [comment]
Thank you for the response.
Actually i did not get response from amber forum thats why i am posting here my issue. I send blank email almost a month ago for subscriptios but no response from the forum, i could not post without a membership.

And about issue i got the tip5p.pdb file thanks for that but to run this i need source leaprc.water.tip5p, frcmod.ionsjc_tip5p and frcmod.ions234lm_tip5p files which are not included in Amber20 directory, so can you help me out in these.
or kindly accept my subscription request in amber forum so that i can ask there openly.

thanks again for your response and guidance.

**Comment by drroe** [comment]
> i need source leaprc.water.tip5p, frcmod.ionsjc_tip5p and frcmod.ions234lm_tip5p files which are not included in Amber20 directory,

Make sure you are sourcing the amber.sh (or amber.csh depending on your shell) file in your AMBERHOME directory. Then when you run `tleap` your paths will be set automatically (the files in question are somewhere inside the $AMBERHOME/dat directory).

It seems like you're a beginner, so you may want to do a few of the starting tutorials for Amber to get familiar with the Amber workflow: https://ambermd.org/tutorials/

> or kindly accept my subscription request in amber forum so that i can ask there openly.

Unfortunately I don't have admin access to the mailing list. Try sending another blank email to `amber-subscribe<at>ambermd.org` - maybe you just hit a temporary issue.

**Comment by drroe** [comment]
If this issue is not resolved, please reopen it.
