### ISSUE TITLE
unit of force in Jarcynski ASMD output

### ISSUE THREAD

**Issue by macardosa** [Amber-MD/cpptraj#1038]
Dear Amber team,

I have been trying to figure out what are the units of force printed in the DUMPAVE file from an adaptive SMD simulation as quoted [here](https://ambermd.org/tutorials/advanced/tutorial26/section2.php) and in the manual Amber23 page 545.
I have the impression they should be kcal/mol/Ang,  but since I have not found it explicitly said I wanted to be sure of that. Also, I went to so many emails in the amber mailing list asking about units of force in other contexts,  and saying it might be amu Ang/ps^2, that I got a little confused. 
Finally, I found [this other issue](https://github.com/Amber-MD/cpptraj/issues/989) which says the units are kcal/mol/Ang in the NetCDF output.

So, please which are the units of force printed in the output file of ASMD: the file with four columns: x0(t), x, force, work.

Kind regards
Manuel

**Comment by drroe** [comment]
Hi! This repository is really just for cpptraj issues - you'll almost certainly get a better response on the [Amber mailing list](http://lists.ambermd.org/mailman/listinfo/amber). I'll do my best to respond here.

> So, please which are the units of force printed in the output file of ASMD: the file with four columns: x0(t), x, force, work.

I'm not an expert in SMD simulations, but I do know that internally Amber uses AKMA units, so force is going to be kcal/mol/Ang unless there is some conversion going on. But to be certain I would ping the mailing list.

**Comment by macardosa** [comment]
Thank you to @drroe for addressing so quickly my question. 
I also found in one of the threads of the Amber mailing list that the units should be kcal/mol/Ang
http://archive.ambermd.org/200906/0424.html
http://archive.ambermd.org/200611/0143.html

I appreciate your response and I will ask on the [Amber mailing list](http://lists.ambermd.org/mailman/listinfo/amber) other issues of this kind.
