### ISSUE TITLE
Install cpptraj las version

### ISSUE THREAD

**Issue by groponp** [Amber-MD/cpptraj#1071]
Dear, 

I'm novice using cpptraj. I want install the last version  with openmp , but I haven't idea as make it. 

Can some body help me with this? 

Note: my problem is more into as install external libraries. 

best.

**Comment by groponp** [comment]
@drroe I have installed using conda, but I am not sure if using conda is enable openmp, my cpptraj using conda are running OK.

**Comment by groponp** [comment]
@drroe, one question more : 

I'm using cpptraj to analysis PSF/DCD NAMD traj, when I load the PSF and DCD i have the followings warnings, Is it critical for following analysis?  
```bash
CPPTRAJ: Trajectory Analysis. V6.18.1 (AmberTools)
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_

| Date/time: 03/27/24 10:28:59
| Available memory: 306.909 MB

        Loading previous history from log 'cpptraj.log'
> parm files/MD_QwikMD.psf 
  [parm files/MD_QwikMD.psf]
        Reading 'files/MD_QwikMD.psf' as Charmm PSF
    Reading Charmm PSF file MD_QwikMD.psf as topology file.
        PSF contains 36366 atoms, 11425 residues.
Warning: Determining bond length parameters from element types for 'MD_QwikMD.psf'.
> trajin 04_MD/MD_r1.dcd 
  [trajin 04_MD/MD_r1.dcd]
        Reading '04_MD/MD_r1.dcd' as Charmm DCD
        Version >= 22; assuming shape matrix is stored.
Warning: Trajectory box type is 'Orthorhombic' but topology box type is 'None'.
Warning: Setting topology box information from trajectory.
> 
```

**Comment by drroe** [comment]
I don't manage the conda install, but the OpenMP cpptraj binary is typically called cpptraj.OMP - if that binary exists, run that. You should see OpenMP printed somewhere in the header, e.g.
```
$ cpptraj.OMP

CPPTRAJ: Trajectory Analysis. V6.23.0 (GitHub) OpenMP
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_
```
Don't forget to set OMP_NUM_THREADS to something reasonable; i.e. if you have hyperthreading turned on, it's usually better to set OMP_NUM_THREADS equal to the number of physical cores (typically half of what `nproc` returns).

> Warning: Determining bond length parameters from element types for 'MD_QwikMD.psf'.

Since PSF files only contain topology information, this is just letting you know that cpptraj is guessing what the bond lengths should be based on the elements. It's usually OK to ignore this warning.

>  Trajectory box type is 'Orthorhombic' but topology box type is 'None'.

This is also fine to ignore. PSF files don't have unit cell information, so CPPTRAJ is telling you it's getting the unit cell information from the trajectory itself.

**Comment by groponp** [comment]
@drroe thanks for much for you help. finally when use trajout  Can i add the commando "nobox", to avoid warning related to the box when make rms (remove rot+trans from my trah)?

**Comment by drroe** [comment]
> Can i add the commando "nobox", to avoid warning related to the box when make rms (remove rot+trans from my trah)?

Yes, but note that you will no longer be able to image the trajectory once box information is removed.

If you want to preserve unit cell information after rotation, use a format that stores complete unit cell vectors like Gromacs TRR or XTC.

**Comment by groponp** [comment]
@drroe with your last comment I have a doubt.  If I following the scipt: 
```bash 
parm name.psf 
trajin nam.dcd     # from md misulation 
autoimage           # to remove PBC effects 
trajout  name-fix.dcd 
run
```

and follwing use the name-fix.dcd to remove rot+trans 
```bash 
parm name.psf 
trajin namd-fix.dcd 
rms   fit :1-153@CA 
trajout name-fit.dcd  nobox  # here if I don't use nobox, it given a lot of warning of box
run
```
Is this ok?, I use rot+trans only for visualization.

**Comment by drroe** [comment]
Hopefully this issue is now resolved - if not please feel free to reopen it.

**Comment by groponp** [comment]
Thanks so much, this is resolve.
