### ISSUE TITLE
running multiple analysis in single file question

### ISSUE THREAD

**Issue by groponp** [Amber-MD/cpptraj#1072]
Dear, I want to do multiple analysis using an only script, but I have doubt , I show my script below: 

```bash
parm name.psf 
trajin namd_fixpbcb.dcd   # it is the traj without pbc effect produced with autoimage 

rmsd  first :@CA&!(:WAT|:LIG) out rmsd.dat 
atomicfluct  irst :@CA&!(:WAT|:LIG) out rmsf.dat
hbond 
distance  
run
```

Q1:  Is my command from rmsd rigth? 
Q2:  How do I generate the PDB from atomicfluct to be colored by bfactor? 
Q3: The rmsd fit affect the folowing analysis? 
Q4: Is in atomicfluct the fit task done automatic?

**Comment by drroe** [comment]
> Q1: Is my command from rmsd rigth?

If what you want is CA best-fit coordinate RMSD using the first frame as a reference, excluding WAT and LIG residues, then yes.

> Q2: How do I generate the PDB from atomicfluct to be colored by bfactor?

You need to specify the `bfactor` keyword for `atomicfluct`, then specify that data to the output PDB with `bfacdata`. You also need to pick what you want to use as the coordinates; could be the average, first frame, etc. So for example, this input will put calculated B-factors into a PDB:
```
parm ../tz2.parm7
trajin ../tz2.nc
atomicfluct A0 :2-12
average crdset MyAvg
run
crdout MyAvg fluct.2.pdb bfacdata A0 chainid " "
```

> Q3: The rmsd fit affect the folowing analysis?

Yes, if you're doing best-fit RMSD then the coordinates are affected for all following actions.

> Q4: Is in atomicfluct the fit task done automatic?

No, so in your case you are best-fitting to the first frame as your reference for the atomicfluct calculation. Check all the output that CPPTRAJ produces. I also highly recommend reading the manual entries on all of these commands/keywords.

**Comment by groponp** [comment]
Thanks so much for you anwser !

**Comment by drroe** [comment]
If this issue isn't actually resolved, please do reopen it!

**Comment by groponp** [comment]
This is resolve!
