### ISSUE TITLE
cpptraj

### ISSUE THREAD

**Issue by H-EKE** [Amber-MD/cpptraj#1073]
Hi,

I am tracking the tryptophan dihedral  (chi1,chi2) of 2 different systems with

```
parm prod1/structure.psf
trajin prod$1/output.xtc
strip :SOD,CLA,TIP3
autoimage
rms first @CA 
dihedral :X@N :X@CA :X@CB :X@CG out WX_chi_u.dat #chi1
dihedral :X@CA :X@CB :X@CG :X@CD2 out WX_chi_u.dat #chi

```

**Comment by drroe** [comment]
> However, when I export the pdb and overlayed them, they are not the same.

Hi - so it's not clear to me what your issue is. When you export the PDB of what specifically? And overlay which two structures? Please provide as much detail as you possibly can. Maybe even attach the two PDBs in question if you think that will help explain your issue more clearly.

**Comment by H-EKE** [comment]
Hi @drroe 

Thanks for your fast reply .

 I am trying to compare the dihedral angles (chi1 and chi2) of two different systems, expecting that regions with the same chi1 and chi2 values should have the same rotamer conformation. However, when I overlay the structures based on these dihedral angles, Im not getting the expected result. I can't attached pdbs here for confidential reasons, but I could send it to you by mail.

**Comment by drroe** [comment]
> However, when I overlay the structures based on these dihedral angles, Im not getting the expected result.

How are you overlaying the structures? If you are just using the RMS best-fit that is in the original script you posted, similar chi1/chi2 values between 2 different frames could appear to be different based on what they are attached to. For example, say your sequence in question is `SAAWKL` - the tryptophan may have similar values in frames 1 and 10, but if the conformation of `SAA` is different in the two frames the position of `W` may appear different because you are fitting on the entire protein. If what you want is to overlay the tryptophan, you could try something like this:

```
parm prod1/structure.psf
trajin prod$1/output.xtc
strip :SOD,CLA,TIP3
autoimage
rms first @CA 
# Output trajectory after fitting on all C-alphas
outtraj CAfit.xtc
# Fit on backbone of X (this will not affect dihedral calcs)
rms first :X@C,CA,N,O
# Output trajectory after fitting on backbone of X
outtraj Xfit.xtc
dihedral :X@N :X@CA :X@CB :X@CG out WX_chi_u.dat #chi1
dihedral :X@CA :X@CB :X@CG :X@CD2 out WX_chi_u.dat #chi
```

Does that make sense? You could also use the `filter` command and/or `maxmin` keyword of `outtraj` to output frames that meet certain dihedral value criteria.

**Comment by H-EKE** [comment]
That sounds as a good hint! I will try it. Thanks a lot !!!

**Comment by H-EKE** [comment]
Hi @drroe,

Sorry for bothering you again, but I have 2 additional questions:

```
help multidihedral 
    [<name>] <dihedral types> [resrange <range>] [out <filename>] [range360]
    [dihtype <name>:<a0>:<a1>:<a2>:<a3>[:<offset>] ...]
        Offset -2=<a0><a1> in previous res, -1=<a0> in previous res,
                0=All <aX> in single res,
                1=<a3> in next res, 2=<a2><a3> in next res.
    <dihedral types> =  alpha beta gamma delta epsilon zeta nu1 nu2 h1p c2p chin phi psi chip omega
```
```
multidihedral chin chi2 :X 
```

and 
```
dihedral :X@N :X@CA :X@CB :X@CG out WX_chi_u.dat #chi1
dihedral :X@CA :X@CB :X@CG :X@CD2 out WX_chi_u.dat #chi2
```
1) should lead to the same result right?

2)  if i just strip, without autoimage, dihedral is able to reimage?

**Comment by drroe** [comment]
Sorry for the delay in responding.

> should lead to the same result right?

No, `chin` is "nucleic acid chi" (see the manual for details). There is no preset for 'chi2', there is only 'chip' (protein chi). You can add a custom definition to `multidihedral` with `dihtype chi2:CA:CB:CG:CD2` - again see the manual for full details.

> if i just strip, without autoimage, dihedral is able to reimage?

Imaging won't affect dihedrals that are connected by bonds, unless you have imaged individual atoms (i.e. your molecules are "split" across images, which is not typical).
