### ISSUE TITLE
vector definition

### ISSUE THREAD

**Issue by H-EKE** [Amber-MD/cpptraj#1089]
Hi I am decomposing my system in vectors using cpptraj to measure angles and rotations and I have afew questions?doubts

1) Defining vectors

My protein is composed by 5 helices and I would like to calcul the tilt between the helices,

I saw this answer in the mailing list (http://archive.ambermd.org/201908/0084.html) where it is proposed to use the use 3 residues which are ~3 from each end to account for any end-terminal fraying. Why would be this better than using the whole helix?

2) Rotation angle between vector

I woudl like to measure the twist/rotation angle  between an N-terminal and C-terminal domain as they did in this paper

In order to capture rotation towards more active-like or inactive-like conformations, we measure rotation about a particular axis: the rotation axis that defines the displacement of the C domain (relative to the N domain) between the inactive and active crystal structures

I have thought about this

```
# Load the topology and trajectory files
parm strucuture.psf
trajin output.xtc

# Calculate the rotation  of the C-terminal domain relative to the N-terminal domain
vector v1 :1-50@CA :51-100@CA  in
vector v2 :151-200@CA :201-250@CA  

run

```

but if i understood correcty, that give me the angle between vectors but not rotation. Is it correct?

Thanks in advance!

**Comment by drroe** [comment]
> I saw this answer in the mailing list (http://archive.ambermd.org/201908/0084.html) where it is proposed to use the use 3 residues which are ~3 from each end to account for any end-terminal fraying. Why would be this better than using the whole helix?

Well, you wrote it yourself; to account for end-terminal fraying 😃 . If the ends of your helix tend to fray, then the residues at the end of the helix may not be good for defining a vector that runs through the center of the helix. If your helix is relatively stable (which is something you can check with the `secstruct` action), then you may be able to use the residues at the ends of the helix.

One way you can check if the vector truly represents the helix well is by calculating the vector and then visualizing it via creation of a vector pseudo-trajectory, e.g.
```
parm strucuture.psf
trajin output.xtc
vector v1 <helix mask 0> <helix mask 1>
run
writedata v1.mol2 v1 vectraj trajfmt mol2
```
You can then load `v1.mol2` in your favorite visualization program alongside the original structure and see how well it lines up with the helix in question. See the manual for full details on `writedata vectraj`.

>  woudl like to measure the twist/rotation angle between an N-terminal and C-terminal domain as they did in this paper

Well you didn't actually link a paper, but one way you might be able to go about this is by fitting one domain on the other via an RMS best-fit using `rms` (if there are enough atoms in common to do so, like maybe just `CA` atoms), saving the rotation matrices with `savematrices`, and extracting the angles from the rotation matrices with `rotate calcfrom`, or maybe just calculate the principal axes vectors for each domain using `vector principal x` and then calculating the angle between those vectors using `vectormath`. Without seeing the original analysis I can really only guess.

Hope this helps.

**Comment by H-EKE** [comment]
Dear @drroe 

Thanks for your fast reply!


In my case I have a GPCR, so I have some helices where have end-terminal fraying. I just read again my statement and I saw I was not very clear. My question was if it would be straighforward to mix vector definitions:

Helix one: I have end-terminal fraying so I define vector based on the whole helix.
Helix two: I dont end-terminal fraying so I definde my vector based on 3 from each end. 

Is it correct to measure angle between helix one and two? or should i go for the same helix definition?


Well you didn't actually link a paper, but one way you might be able to go about this is by fitting one domain on the other via an RMS best-fit using rms (if there are enough atoms in common to do so, like maybe just CA atoms), saving the rotation matrices with savematrices, and extracting the angles from the rotation matrices with rotate calcfrom, or maybe just calculate the principal axes vectors for each domain using vector principal x and then calculating the angle between those vectors using vectormath. Without seeing the original analysis I can really only guess.

I would try your suggestion, thanks a lot ! I was trying to replicate the analysis on this paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6294333/) wherer they measure the twist of beta-arrestin

**Comment by drroe** [comment]
Let me know if you have any more questions, or if it's OK to close this issue.

**Comment by H-EKE** [comment]
Thanks again :) .It is ok.
