### ISSUE TITLE
lowestcurve: what(): std:bad_alloc

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#110]
I just tried very dummy example

```bash
parm tz2.ortho.parm7
trajin tz2.ortho.nc
rms myrmsd @CA
lowestcurve points 10 myrmsd
```

got (only show the end)
```bash
ANALYSIS: Performing 1 analyses:
  0: [lowestcurve points 10 myrmsd]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

It's likely that we should have better message and exit here.

**Comment by drroe** [comment]
Fixed by #129

**Comment by hainm** [comment]
@drroe is this Action similar to Asim's apper?

**Comment by drroe** [comment]
> is this Action similar to Asim's paper (hist GA force field)?

@hainm Yes, exactly. Hasn't been tested as much as it could so feel free to try and break it.

**Comment by hainm** [comment]
ok. I have data to test in mind. will report later.
