### ISSUE TITLE
Puzzled by atom-based masking of energies

### ISSUE THREAD

**Issue by mkgilson** [Amber-MD/cpptraj#1103]
I want to decompose the energies of a system by atom, but am puzzled by the outputs. I'm using commands of the form

energy test1 @2 out test1.txt
energy test2 @1-10 out test2.txt

with the trpzip tutorial files here https://ambermd.org/tutorials/analysis/tutorial0/index.htm

When I use the mask @1, the energies are all zero. Same for mask @1,2. Mask @1-3 caused a core dump. Mask @1-4 gave me output angle energies, but all other energies are zero. Mask @1-5 gives both bond energies and angle energies. This is very weird, since two atoms should give a bond energy, three atoms should give angle, four should add torsions. Mask @1-6 brings in vdw14 and elec14 energies. Mask @1-7 gives same types of energy terms as @1-6, and Mask @1-8 finally also gives vdw and elec.

Is there a way to get e.g. the energies of all the bonds that atom 1 belongs to?

**Comment by drroe** [comment]
Hi! I just sent a reply to your email address regarding a similar issue (sorry for the delay again!). So you can't do energy decompositions like this yet - it's something I want to add. The `pairwise` command does a simple energy decomposition but only for simple nonbonded terms. The code should never be segfaulting - I'll look into what's causing that. Thanks for the report!
