### ISSUE TITLE
Smooth density grid

### ISSUE THREAD

**Issue by H-EKE** [Amber-MD/cpptraj#1118]
Hi,

Im using this script to see the density bindiing of a msall probe around a protein.

```
parm 0.2/prod1/structure.pdb
for i=1;i<21;i++
trajin 0.2/prod$i/output.xtc 1 last
solvent :IMI,TIP,SOD,CLA
autoimage origin
rms first @CA
done
#the bounds command, we are going to calculate the boundaries of just the g-quadruplex by selecting residues 1 to 15. If we ca
lculate the boundaries including the ligand, the box will be bigger in order to accommodate those events where the ligands is 
far from the DNA, and we do not want to include those events. The dx 0.5 tells the command#that the spacing will be every 0.5 
in the three x, y and z directions
bounds :1-210 dx 0.5 name MyGrid out boundaries_IMI.dat 
average average.pdb pdb :1-210 
createcrd MyCoords
run
#crdaction command to perform the grid 
#analysis in the data saved in ‘MyCoords’.
crdaction MyCoords grid grid_imi.dx data MyGrid :IMI normframes 
run
```

I would like to remove density as much as possible, so I thoug to use normframes and smoothdensity. However, it was not clear enought to me after reading the manual how to uuse.

One should use something like this: ``` smoothdensity 0.5 ``` ?

**Comment by H-EKE** [comment]
Also another question related to this,

If I would like to use volmap (https://amberhub.chpc.utah.edu/volmap/) to detect biding sites, would be this correct?


```
volmap vol_imi.dx 20,20,20 :IMI grid_imi.dx

```

**Comment by drroe** [comment]
First, putting `autoimage` and `rms` inside the loop just means you are unnecessarily repeating those commands. Just put the `trajin` stuff inside the loop. Actions by default will be run on all input trajectories.
```
parm 0.2/prod1/structure.pdb
for i=1;i<21;i++
  trajin 0.2/prod$i/output.xtc 1 last
done
solvent :IMI,TIP,SOD,CLA
autoimage origin
rms first @CA
bounds :1-210 dx 0.5 name MyGrid out boundaries_IMI.dat 
average average.pdb pdb :1-210 
createcrd MyCoords
run
```

Second, `smoothdensity` is a pretty old option that I implemented from ptraj, which uses a Gaussian-like kernel to try and smooth out the density. A far better option for having a "smooth" density is to use the `volmap` command, which uses Gaussian kernels which are based on the VDW size of the atoms themselves.
