### ISSUE TITLE
cpptraj conda build

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#118]
I've finished a build recipe for cpptraj (not libcpptraj) with mathlib.

It's very great if you get used to conda build.

- Install `conda`: http://conda.pydata.org/docs/get-started.html
- clone our recipe on amber github: https://github.com/Amber-MD/conda-recipes
- `cd  conda-recipes`
- add ambermd channel (with prebuilt lapack, arpack, blas): `conda config --add channels https://conda.binstar.org/ambermd`
- build cpptraj `conda build cpptraj` (cpptraj is a folder having conda recipe https://github.com/Amber-MD/conda-recipes/tree/master/cpptraj)
- test install: `conda install cpptraj-dev -c ambermd` (will install serial and openmp version)

if you want to test local install after build, you can try
`conda build /home/anaconda3/conda-bld/linux-64/cpptraj-dev-4.2.7-0.tar.bz2`
(or any bz2 file appear after build)

PS: thanks Robert for his arpack [recipe. ] (https://github.com/Amber-MD/conda-recipes/tree/master/arpack) and thanks to omnia channel.

**Comment by rmcgibbo** [comment]
I have a better idea for the arpack/blas/lapack stuff. Basically, use OpenBLAS for BLAS and LAPACK, and there's no need to build static libraries for arpack, you can have a runtime depends on libgfortran/libgcc, which is small.

**Comment by hainm** [comment]
yeah, I want to use `OpenBLAS` too because it's easy to get it from anaconda channel (and we have only one more dependence vs 3).

**Comment by rmcgibbo** [comment]
I also have OpenBLAS for OS X and Windows (mingw-w64 static toolchain) in omnia.

**Comment by rmcgibbo** [comment]
Also, it shouldn't be necessary for you to copy over the recipe files from omnia/conda-recipes, unless you need to. You can always copy over the built binaries (.tar.bz2) packages into another conda channel, but we already have all the build infrastructure set up to automatically build the packages for windows, osx and linux, and you're welcome to use it. We'd be happy to collaborate.

**Comment by hainm** [comment]
I have several reasons to reinvent the wheel here.

* I am quite new to conda build (only done before with travis), so this is a way to learn.

* AMBER has tradition to pack everything in one single package (it ships with lapack/blas/arpack). My vision is to include those recipe in one folder in amber (not sure for what reason).

* just a backup: I want to control the build and install. (for example if anaconda down, omnia disappear :D) 

> We'd be happy to collaborate.

We are too. It's great that you (and others) make the Window work. :+1:

**Comment by rmcgibbo** [comment]
The recipes really aren't meant for users. The point is to use the recipes to build binaries that the users install.

**Comment by rmcgibbo** [comment]
I guess my other hidden agenda here is that the maintenance of the conda-recipes is a nontrivial amount of ongoing work. So if you're using them, I'd really appreciate any collaboration on their maintenance.

**Comment by hainm** [comment]
> So if you're using them, I'd really appreciate any collaboration on their maintenance.

sure.
