### ISSUE TITLE
nastruct: skip 0 values? *X-disp    Y-disp    h-Rise    Incl.     Tip     h-Twist)

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#120]
I've just compared cpptraj and x3dna output. So far the helical pars match very well. But cpptraj skips 0.0 values for `X-disp    Y-disp    h-Rise    Incl.     Tip     h-Twist` in Dataset. Is this your intention?

x3dna

```bash
#        Shear    Stretch   Stagger   Buckle   Prop-Tw   Opening     X-disp    Y-disp    h-Rise    Incl.     Tip     h-Twist
g-c     -0.158     0.029     0.330    -2.130    -3.117     0.386     0.000     0.000     0.000     0.000     0.000     0.000
```

**Comment by drroe** [comment]
@hainm Not sure what you mean here - can you give an example, preferably with files I can use to reproduce? Thanks.

**Comment by hainm** [comment]
@drroe 
this is pdb file: https://github.com/Amber-MD/pytraj/blob/master/tests/data/Test_NAstruct/x3dna/rna.pdb

this is output from x3dna for helical pars:
https://github.com/Amber-MD/pytraj/blob/master/tests/data/Test_NAstruct/x3dna/bp_helical.par

pytraj took the data from DatasetList and it seems to me that cpptraj skip the 0 values for first g-c (non-capitalized) pairs for `X-disp    Y-disp    h-Rise    Incl.     Tip     h-Twist`

**Comment by drroe** [comment]
This is actually a non-issue. Cpptraj isn't skipping anything - the calculation of helical parameters requires two basepair reference frames (similar to basepair step). So there really should only be 7 values.

**Comment by hainm** [comment]
okie. Just want to make sure.
