### ISSUE TITLE
bfactor: should be seperated?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#126]
I think bfactor calculation is quite common and it's hidden in atomifluct command. What's about make it separate command?

**Comment by hainm** [comment]
should we add 'RMSF' as an alias to atomicfluct too?

**Comment by drroe** [comment]
> I think bfactor calculation is quite common and it's hidden in atomifluct command. What's about make it separate command?

I don't like that. First, it's not *really* a B-factor calculation, at least not the way an X-ray crystallographer would define it (similar but definitely not the same). Since it's just the atomic fluctuations converted to different units, I think it is fine where it is.

> should we add 'RMSF' as an alias to atomicfluct too?

That seems OK.

**Comment by hainm** [comment]
> I don't like that. First, it's not really a B-factor calculation, at least not the way an X-ray crystallographer would define it (similar but definitely not the same). Since it's just the atomic fluctuations converted to different units, I think it is fine where it is.

okie.
