### ISSUE TITLE
test lowestcurve

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#131]
my test https://github.com/Amber-MD/cpptraj/issues/110#issuecomment-148229056

**Comment by hainm** [comment]
@drroe I have a question about the command:

```bash
  mprintf("\tpoints <# lowest> [step <stepsize>] <dset0> [<dset1> ...]\n"
          "\t[out <file>] [name <setname>]\n"
          "  Calculate a curve of the average of the # lowest points in bins of stepsize.\n");
```

saying if I have a file with 2 columns: RMSD-EPOT

How can I use cpptraj to calculate the data? (what I meant is: can you give me detail traj.in)

![nfig016](https://cloud.githubusercontent.com/assets/4451957/10527505/cb59985c-735e-11e5-9ae4-0a2d141e79a9.gif)

**Comment by drroe** [comment]
```
readdata RMSD-EPTOT.dat index 1 name MyData
runanalysis lowestcurve MyData points 10 step 0.2 name Lowest
writedata All.agr MyData Lowest
```
Not tested but something like that should work. This will calculate the Y average of the 10 lowest points in bins sized 0.2 in X.

**Comment by hainm** [comment]
@drroe 
```bash
$ ../../cpptraj/bin/cpptraj.OMP -i t.in

CPPTRAJ: Trajectory Analysis. V16.00b OpenMP
    ___  ___  ___  ___
     | \/ | \/ | \/ |
    _|_/\_|_/\_|_/\_|_

| Date/time: 10/15/15 17:53:27
| Available memory: 6162.92 MB

INPUT: Reading Input from file t.in
  [readdata EPOTvsRMSD.dat index 1 name MyData]
        Reading 'EPOTvsRMSD.dat' as Standard Data File with name 'MyData'
        Using column 1 as index column.
        DataFile EPOTvsRMSD.dat has 2 columns, 35809 lines.
  [runanalysis lowestcurve MyData points 10 step 0.2 name Lowest]
Error: Only 1D data sets allowed.
Error: Could not add data sets.
TIME: Total analysis execution time: 0.0001 seconds.
        1 errors encountered reading input.
TIME: Total execution time: 0.0431 seconds.
```

input files
-------------

```bash
$ cat t.in
readdata EPOTvsRMSD.dat index 1 name MyData
runanalysis lowestcurve MyData points 10 step 0.2 name Lowest
writedata All.agr MyData Lowest
```

```bash
$ head EPOTvsRMSD.dat
0.37056 -.27442316E+03
0.56427 -.27693323E+03
1.24848 -.29345784E+03
3.44260 -.27236979E+03
3.02761 -.27974427E+03
2.22135 -.27529605E+03
2.77868 -.25797459E+03
1.87877 -.27099555E+03
5.91050 -.27093605E+03
4.38278 -.27035790E+03
```

**Comment by drroe** [comment]
This is actually a problem with how the data set is read - sorry. I'm working on it. Fix will be done soon.

**Comment by drroe** [comment]
Should work now as of #135

**Comment by hainm** [comment]
@drroe 

seems work for me with 'All.arg' ext, but if I use '.dat', I got

```bash
        Writing sets to All.dat, format 'Standard Data File'
 MyData:2 LC(MyData:2)
Error: X Dimension of LC(MyData:2) != MyData:2
Error:  LC(MyData:2): Min=0.348310 Step=0.200000
Error:  MyData:2: Min=2.145660 Step=0.000071
TIME: Total execution time: 0.0954 seconds.
```

**Comment by hainm** [comment]
and can you tell me how can I use this analysis internally for pytraj? 

Should I create a DatasetMesh (name `mysurf`), add its data and feed it to this analysis like below?

`points 10 mysurf`

This is what I got

```python
[<pytraj.datasets.DatasetMesh: size=27479, key=mysurf>
values: # rms - esurf
[[  2.14566  10.6364 ]
 [  1.80556  10.2486 ]
 [  1.7004   10.3254 ]
 ...,
 [  4.42627  10.8499 ]
 [  4.58734  11.1952 ]
 [  4.1027   11.58   ]],

 <pytraj.datasets.DatasetDouble: size=9, key=LC(mysurf)>
values:
[  9.09119   9.19316   9.32123   9.74471   9.82968  10.22593  11.32093
  13.61043  13.234  ]]
```

**Comment by drroe** [comment]
> seems work for me with 'All.arg' ext, but if I use '.dat', I got

Yeah, this is expected because the way "standard" data output works you have 1 X dimension for N Y dimensions. In this case the X dimensions don't match because the output from lowest is a histogram with far fewer data points. You actually do get output though right?

**Comment by hainm** [comment]
> You actually do get output though right?

with grace format, the calculation seems right to me. But the x label is wrong (`Frame`). However, I am more interested in how to get it right in pytraj without saving to file.

![all](https://cloud.githubusercontent.com/assets/4451957/10551609/eae6abd4-741b-11e5-8d6d-c3323087b1b0.png)

**Comment by drroe** [comment]
> If the steps above are true, how pytraj get the bin values for plotting?

Sorry, I missed this question previously. In cpptraj, the way to get a coordinate for *any* dimension is via `DataSet::Coord(unsigned int dimension, size_t position)`. For example,
```C++
double x_coord = dataset->Coord(0, 3);
```
would assign `x_coord` the coordinate for dimension 0 (X), position 3. If e.g. the dimension for `dataset` has a minimum of 10.0 and a step of 2.0, the coordinate will be 16.0 (10.0 + (3 * 2.0)).

For DataSet_1D classes (DataSet_double, DataSet_float, DataSet_integer, DataSet_Mesh) you can use the `Xcrd(size_t position)` function as a shortcut to get the value of the X coordinate at a certain position. Make sense?

**Comment by hainm** [comment]
ok. I will try to see if make sense or not. :D

**Comment by hainm** [comment]
@drroe Done

[tutorial on jupyter notebook is here] (http://amber-md.github.io/pytraj/doc/build/html/tutorials/plot_lowest_curve.html)

![](http://amber-md.github.io/pytraj/doc/build/html/_images/lowest_curve.png)

**Comment by drroe** [comment]
Looks good!
