### ISSUE TITLE
Add option to write sybyl atom types and bond types to generated mol2 files

### ISSUE THREAD

**Issue by swails** [Amber-MD/cpptraj#136]
`top2mol2` is trying to come back from the grave.  Apparently it had an option to generate mol2 files with SYBYL atom types and bond types (taken from the tables `$AMBERHOME/dat/antechamber/{ATOM,BOND}TYPE_CHECK.TAB`) which isn't available in any other program at the moment.

If cpptraj could do this easily, that would be great.  If not, we can always resurrect (yet another) mol2 writer.

**Comment by drroe** [comment]
I see, so it seems the format of `$AMBERHOME/dat/antechamber/ATOMTYPE_CHECK.TAB` is
```
Amber_Atom_Type SYBYL_AtomType
```
and the format of `$AMBERHOME/dat/antechamber/ATOMTYPE_CHECK.TAB` is
```
Amber_Atom1_Type Amber_Atom2_Type SYBYL_Bond_Type
```
is that correct? If so this should be a fairly easy thing to implement.

**Comment by drroe** [comment]
@swails Should be addressed (somewhat) by #150; use keyword 'sybyltype' with mol2 trajout to enable. Requires AMBERHOME be set and the Topology have Amber atom types.

**Comment by swails** [comment]
Is this somehow exposed through ambpdb?

**Comment by drroe** [comment]
Not yet - I wanted it to be tested a bit before moving on to the next step, whether that's making a top2mol2 interface etc.

**Comment by drroe** [comment]
@swails is the ultimate goal to make top2mol2 use cpptraj on the back-end (like ambpdb)?

**Comment by swails** [comment]
I think not.  I actually removed `top2mol2` from the distribution awhile ago (around the time that I added mol2 file support to the ambpdb F90 code).  I believe you added mol2 file writing to cpptraj that same week.  I (erroneously) thought that all top2mol2 functionality was available through `ambpdb` and `cpptraj`, so I figured it was an easy program to axe from the distro.

Then a week ago (or so), the one group in the world that used top2mol2 in the only mode not supported elsewhere surfaced and asked me what happened to the program.  When faced with the option between reviving top2mol2 (in any form) or putting in a request to have that functionality folded into cpptraj-driven ambpdb, I came here in hopes of convincing you of the latter :).

So *my* ultimate goal is to have some kind of `-sybyl` flag to `ambpdb` that completely eradicates the need for YAB (Yet Another Binary).

**Comment by drroe** [comment]
> So my ultimate goal is to have some kind of -sybyl flag to ambpdb that completely eradicates the need for YAB (Yet Another Binary).

Works for me. I can add that no problem. Out of curiosity, have you had a chance to test what's currently in cpptraj?

**Comment by swails** [comment]
> Works for me. I can add that no problem. Out of curiosity, have you had a chance to test what's currently in cpptraj?

Not yet.  It'll be easier if I can do a 1-line ambpdb command and compare it to a top2mol2 output.

**Comment by swails** [comment]
But of course I can do it via script as well

**Comment by drroe** [comment]
-sybyl flag for ambpdb implemented via #151

**Comment by swails** [comment]
Nice, I'll try it out when I get a chance.

Thanks!

**Comment by drroe** [comment]
I'm going to go ahead and close this. Any bugs can be brought up in a separate issue.
