### ISSUE TITLE
lifetime: [averageonly] Just calculate averages (no lifetime analysis)

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#138]
I am not sure with above statement. What's the point of using `lifetime` with `averageonly` saying `no lifetime analysis`? Should this be in another analysis?

**Comment by drroe** [comment]
> What's the point of using lifetime with averageonly saying no lifetime analysis?

To take advantage of the block averaging code over windows that `lifetime` uses.

> Should this be in another analysis?

I guess it could. However it's been around so long at this point I don't think it's worth potentially breaking backwards compatibility for people.

**Comment by hainm** [comment]
> I guess it could. However it's been around so long at this point I don't think it's worth potentially breaking backwards compatibility for people.

I agree. (just ask because It's not clear to me). thanks.
