### ISSUE TITLE
diffusion: issue from #140

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#141]
#140 

I've tried with diffusion

- [ ]  issue with `time` in diffusion and `tstep` in some of Actions. Seems to me that they have the same meaning but different words. Should keep `time` word (same in old code) or add `tstep` to make consistent?

- [ ] I've tried with `pytraj` and got empty array for slope, .. (which is exptected sine cpptraj throws to STDOUT)

**note** dummy example

```python
In [6]: pt._verbose()

In [7]: pt.common_actions.calc_diffusion(traj, '@CA', dtype='dict')
    DIFFUSION:
        Atom Mask is [@CA]
        Only average diffusion will be calculated.
        Data set base name: Diff_00000
        The time between frames is 1 ps.
        Calculating diffusion constants by fitting slope to MSD vs time
          and multiplying by 10.0/2*N (where N is # of dimensions), units
          are 1x10^-5 cm^2/s.
        Diffusion constant output to STDOUT.
        Mask [@CA] corresponds to 12 atoms.
Out[7]:
OrderedDict([('Diff_00000_X',
              array([ 0.05614873,  0.10287333,  0.18655994,  0.1184479 ,  0.12366827,
                      0.16195742,  0.29856962,  0.48491534,  0.3786582 ])),
             ('Diff_00000_Y',
              array([ 0.09496157,  0.1655993 ,  0.24139566,  0.18078968,  0.36902705,
                      0.21182814,  0.14611536,  0.19769755,  0.16951612])),
             ('Diff_00000_Z',
              array([ 0.03164485,  0.04508574,  0.01360616,  0.12820057,  0.24586084,
                      0.56681929,  0.28472589,  0.63362933,  1.05488908])),
             ('Diff_00000_R',
              array([ 0.18275516,  0.31355838,  0.44156176,  0.42743815,  0.73855616,
                      0.94060486,  0.72941087,  1.31624223,  1.6030634 ])),
             ('Diff_00000_A',
              array([ 0.42749872,  0.55996283,  0.66450114,  0.65378754,  0.8593929 ,
                      0.96984785,  0.85405554,  1.147276  ,  1.2661214 ])),
             ('Diff_00000_D', array(None, dtype=object)),
             ('Diff_00000_Label', array([], dtype=float64)),
             ('Diff_00000_Slope', array(None, dtype=object)),
             ('Diff_00000_Intercept', array(None, dtype=object)),
             ('Diff_00000_Corr', array(None, dtype=object))])

```

I can exclude the `_D`, `Label`, `Slope` from pytraj's output (or using `nocalc` keyword), but just asking if you can dump STDOUT to Dataset, like String? Since it's C++ STOUT, it won't appear in ipython-notebook.

- [ ] should we not use `Diff` keyword? I always think about 'diff' in `diff file_1 file_2`

**Comment by drroe** [comment]
I guess I need to know more about how pytraj is using Action_Diffusion under the hood. Right now there are two syntaxes supported for Action_Diffusion - the original PTRAJ syntax and the new CPPTRAJ syntax I just implemented. The defaults change depending on which is used in order to maintain backwards compatibility. So if you're using the old syntax, diffusion is tracked for each individual atom and diffusion constants are not calculated. Make sure you're using the new syntax.

**Comment by hainm** [comment]
can you paste the new syntax here? I have never used diffusion before so not sure which one is new or  old.

**Comment by drroe** [comment]
Old syntax:
```
diffusion <mask> <time per frame> [average] [<prefix>]
```
New syntax:
```
diffusion [{out <filename> | separateout <suffix>}] [time <time per frame>]
          [<mask>] [<set name>] [individual] [diffout <filename>] [nocalc]
```

**Comment by hainm** [comment]
so I think I am using new syntax:

```python
def _calc_diffusion(traj=None,
                    mask="",
                    tstep=1.0,
                    dtype='ndarray',
                    individual=False,
                    top=None,
                    frame_indices=None):
    '''
    '''
    traj = _get_fiterator(traj, frame_indices)
    act = CpptrajActions.Action_Diffusion()
    dslist = CpptrajDatasetList()

    _tsep = 'time ' + str(tstep)
    _individual = 'individual' if individual else ''

    if not isinstance(mask, string_types):
        command = array2d_to_cpptraj_maskgroup(mask)
    else:
        command = mask

    command = ' '.join((command, _tsep, 'nocalc', _individual))

    traj = _get_fiterator(traj, frame_indices)
    _top = _get_topology(traj, top)

    act(command, traj, top=_top, dslist=dslist)

    for d in dslist:
        # make nicer labels
        d.key = d.key.replace('[', '_').replace(']', '')

    return _get_data_from_dtype(dslist, dtype=dtype)
```

And the output in my 1st post shows the new syntax. But let's come back to each point in my 1st post. Let me know if my point is clear or not so I can try to rephrase.

**Comment by drroe** [comment]
Hi,

On Thu, Oct 29, 2015 at 11:52 AM, Hai Nguyen <notifications@github.com> wrote:
>     command = ' '.join((command, _tsep, 'nocalc', _individual))

Here you are specifying 'nocalc', which explicitly prevents
calculation of the diffusion constants, hence you won't get slopes of
the MSD vs time best-fit lines. If you get rid of 'nocalc' you should
get the diffusion constants.

**Comment by hainm** [comment]
@drroe yeah, I know that (perhaps I updated that code after my 1st post). But you throw the slopes stuff to STDOUT, don't you?

**Comment by drroe** [comment]
> But you throw the slopes stuff to STDOUT, don't you?

Only if 'diffout' has not been specified - this is so users still have a
chance to see the diffusion constants. In either case, the slopes etc are
always saved to data sets when calcDiffConst_ is true (i.e. 'nocalc' not
specified).

**Comment by hainm** [comment]
can you write to string first so python can take the output?

I don't want to write to file but still want the data (slopes) appear in jupyter notebook (which does not display C++ STDOUT).

**Comment by drroe** [comment]
Can't you get the values from the data sets? <name>[D], <name>[Slope], etc?

**Comment by hainm** [comment]
I tried 9 days ago and got empty array for slopes. Please see my 1 post again.

May be I made mistake in pytraj side?

**Comment by drroe** [comment]
> I tried 9 days ago and got empty array for slopes. Please see my 1 post again.

Did you have `nocalc` specified then? Make sure `nocalc` is not being specified and that you are using the new syntax.

**Comment by hainm** [comment]
Ok. I will try again.

**Comment by hainm** [comment]
@drroe oh boy, this `Action_Diffusion` requires calling `Print` method (I got this problem several times (Action_Hbond, ...). Things are fine now. cool.

**Comment by drroe** [comment]
You should *always* call Print(), just in case :-)

**Comment by hainm** [comment]
> You should always call Print(), just in case :-)

will keep in mind with new Action :D

**Comment by hainm** [comment]
added assertion to cpptraj in pytraj

https://github.com/Amber-MD/pytraj/pull/973
