### ISSUE TITLE
dssp discussion

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#142]
What do you guys think about 

- make 'dssp' as alias for secstruct

**Comment by drroe** [comment]
Already is, isn't it?

On Monday, October 26, 2015, Hai Nguyen <notifications@github.com> wrote:

> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/142>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
ack, yes. "29.9.21. dssp" AT15 man

**Comment by swails** [comment]
You're dodging the question

--
Jason M. Swails
BioMaPS,
Rutgers University
Postdoctoral Researcher

**Comment by hainm** [comment]
Does `dodging the question` mean 'avoiding question`? (check from 1st link in google)

If yes, not sure if this is a joke or not (since I already reply `ack, yes`) :D My bad English.

**Comment by swails** [comment]
Yes it does -- and it was aimed at @drroe, not you ;).

**Comment by hainm** [comment]
ha ha, I did not see your quote, so I though it was for me.
