### ISSUE TITLE
travis test for cpptraj MPI

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#145]
we don't have yet. Just put a holder here when Dan finishes his MPI stuff with traj.

**Comment by hainm** [comment]
bump this issue since @drroe  finished his stuff with parallel https://github.com/Amber-MD/cpptraj/pull/228

Need to add building for cpptraj.MPI on travis too.

**Comment by drroe** [comment]
One small issue with this is that I don't think there is a parallel netcdf package available. The tests will still run but coverage will be a bit reduced.

**Comment by hainm** [comment]
Is parallel netcdf required for all Actions or for only writing trajectory?

**Comment by drroe** [comment]
Just a few tests. I just need to protect them against not having parallel netcdf and things will be ok.

**Comment by drroe** [comment]
Addressed by #245
