### ISSUE TITLE
extend multidihedral

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#175]
Like I said that this is very useful command to me.

Not sure if I miss anything but what do you guys think about adding dihedral calculation for arbitrary molecule (having atom type that cpptraj does not recognize).

I just want to take the example of `$AMBERHOME/test/sugarlp/{inpcrd, prmtop}`

With pytraj

```python
In [5]: traj = pt.iterload('inpcrd', 'prmtop')

# pytraj stole the idea from mdtraj for this case since I found this is useful.
In [6]: pt.dihedrals(traj, mask=traj.top.dihedral_indices)
Out[6]:
array([[ 60.60988684],
       [-65.39808823],
       [ 59.79038556],
       ...,
       [-74.64314145],
       [ 63.91591211],
       [-61.55046812]])

In [7]: traj.top.dihedral_indices
Out[7]:
array([[ 4,  7,  9, 11],
       [ 4,  7,  9, 15],
       [ 4,  7, 29, 27],
       ...,
       [ 7,  9, 11, 12],
       [ 7,  9, 15, 16],
       [ 7, 29, 27, 28]])
```

if calling `multidihedral` from cpptraj:
```python
In [8]: pt.multidihedral(traj)
Out[8]:
<pytraj.DatasetList with 0 datasets>
```
This is what I am expecting since cpptraj only search for some specific dih types.

So may be add more Action (or extend) to compute all possible dihedral with given mask?

**Comment by drroe** [comment]
Why not use the `dihtype` keyword?
```
> help multidihedral 
	[<name>] <dihedral types> [resrange <range>] [out <filename>] [range360]
	[dihtype <name>:<a0>:<a1>:<a2>:<a3>[:<offset>] ...]
		Offset -2=<a0><a1> in previous res, -1=<a0> in previous res,
		        0=All <aX> in single res,
		        1=<a3> in next res, 2=<a2><a3> in next res.
	<dihedral types> =  alpha beta gamma delta epsilon zeta nu1 nu2 h1p c2p chin phi psi chip omega
```

**Comment by hainm** [comment]
because I hate typing. :D 

`multidihedral   [dihtype <name>:<a0>:<a1>:<a2>:<a3>[:<offset>] ...]`

vs

`compute_all_for_me(mask=':3-7')`

**Comment by hainm** [comment]
Note that I am thinking about interactive computing with jupyter notebook ([example](http://amber-md.github.io/pytraj/doc/build/html/tutorials/plot_hbond_basic.html)). So 'compute_all_for_me' (long name) is auto-completed (vs typing `<name>:<a0>:<a1>:<a2>:<a3>[:<offset>]`).

**Comment by drroe** [comment]
Oh. Do you mean essentially making masks into data sets? While potentially a nice idea, that's a big change and currently not on the radar. First in order for that to work any ArgList would need to know what's going on in at least the master DataSetList and there is no clean way to do that short of using a static global variable which I'm not a huge fan of. Second and more of an obstacle is that currently many masks are obtained via the ArgList::GetMaskNext() function, which recognizes masks according to a certain criterion which would not be compatible with generic data set names.

One potential solution would be to make some sort of general command like 'AddDihedralType' which then the DihedralSearch class could know about. I may consider that but it's not a huge priority, and I don't think it's that hard to do something like
```
multidihedral dihtype custom:N:CA:CB:CG resrange 3-7
```

**Comment by hainm** [comment]
uhm,  I am not sure I clearly understand what you are saying.

prmtop file already have dihedral indices (or similar). So we can extract those indices for only given mask (example: '3-7'), right?

indices
```
[[ 4,  7,  9, 11],
[ 4,  7,  9, 15],
[ 4,  7, 29, 27]]
```

transfer to cpptraj's syntax:
'@5 @7 @9 @12`, ...

I am not sure how this is a technical problem. :D 

But you are right that this is low priority since pytraj can calculate all dihedral from index array (migh got from cpptraj or parmed) and you don't need this function.

**Comment by drroe** [comment]
Oh - you want to calculate *all* possible dihedrals within a given mask? Sure that can be done, but just using the indices in the dihedral arrays will lead to a lot of redundant values (e.g. do you really need both C-N-CA-CB and C-N-CA-HA?). Can you give an example of where this is more useful than current multidihedral syntax?

**Comment by hainm** [comment]
>  Sure that can be done, but just using the indices in the dihedral arrays will lead to a lot of redundant values (e.g. do you really need both C-N-CA-CB and C-N-CA-HA?). 

ok, now I know this. (I do not play well with prmtop in amber).

> Can you give an example of where this is more useful than current multidihedral syntax?

I am thinking about small molecules. sugar...

for example: $AMBERHOME/test/sugarlp/{inpcrd, prmtop}

Actually I forgot that cpptraj can print to stdout all the dihedral with given mask. We might need to store this information in string so pytraj can take them, parse and pass to dihedral method.

PS: I actually prefer cpptraj has a tag (or similar ) to dump info to string first. For example, those lines from nativecontacts has never appeared in Jupyter notebook:

```bash
#                     Contact  Nframes    Frac.      Avg    Stdev
       1        :3@OG1_:3@HG1      101        1     0.96 0.000451
       2            :3@N_:3@H      101        1     1.01  0.00038
       3       :6@ND2_:6@HD22      101        1     1.01 0.000419
       4        :4@NE1_:4@HE1      101        1     1.01 0.000413
       5            :6@N_:6@H      101        1     1.01 0.000374
       6       :6@ND2_:6@HD21      101        1     1.01 0.000371
       7            :5@N_:5@H      101        1     1.01 0.000407
       8            :7@N_:7@H      101        1     1.01 0.000398
       9            :4@N_:4@H      101        1     1.01 0.000413
      10        :4@CZ2_:4@HZ2      101        1     1.08 0.000375
      11        :4@CD1_:4@HD1      101        1     1.08 0.000416
      12        :4@CE3_:4@HE3      101        1     1.08 0.000449
```

**Comment by drroe** [comment]
> PS: I actually prefer cpptraj has a tag (or similar ) to dump info to string first. For example, those lines from nativecontacts has never appeared in Jupyter notebook:

This appears to be a general communication problem between cpptraj and pytraj, specifically that certain Actions/Analyses use direct file writes for some output, like hbond, nativecontacts, etc. One potential solution is to put the data that this output is generated from into the DataSetList, which would mean those data set types would need to be created (DataSet_Hbond, DataSet_NativeContacts). I have resisted doing this before because the original idea behind DataSets is that they would be as general as possible (although I guess you could say DataSet_Modes is pretty specific...). Maybe a new issue should be created with all of the data that pytraj currently doesn't have access to but would like to? Does that make sense?

**Comment by hainm** [comment]
> Maybe a new issue should be created with all of the data that pytraj currently doesn't have access to but would like to? Does that make sense?

Sure. I will create new issue and keep adding up. The new issue probably closely related to https://github.com/Amber-MD/cpptraj/issues/93

**Comment by hainm** [comment]
I am closing this issue in favor of #177
