### ISSUE TITLE
configure -static does not try very hard

### ISSUE THREAD

**Issue by rmcgibbo** [Amber-MD/cpptraj#204]
`configure`'s `-static` flag does not try very hard to actually link things statically, in that it only [tries](https://github.com/Amber-MD/cpptraj/blob/master/configure#L702-L725) to find `.a` files for packages specified with explicit paths (`--with-<feature>`).

For example, `./configure -static --with-netcdf=/home/rmcgibbo/opt/netcdf-4.3.3-static` will produce
```
LDFLAGS=-larpack -llapack -lblas \
  /home/rmcgibbo/opt/netcdf-4.3.3-static/lib/libnetcdf.a \
  -lbz2 -lz  -lgfortran -w
```

And then I get a binary like
```
$ ldd bin/cpptraj
	linux-vdso.so.1 =>  (0x00007fffe9c86000)
	libarpack.so.2 => /usr/lib/libarpack.so.2 (0x00007f486611c000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f486591f000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f486570f000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f48654f4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4865172000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4864e6a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4864c52000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4864888000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f486464a000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f486431e000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f4863daa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4863b8c000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559979a14000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f486394c000)
```

If you change around the link line a little bit, you can get a much more static build. For example using `-Wl,-Bstatic` on linux/gcc, you force the compiler to prefer static libraries over shared libraries for all libraries that follow
```
LDFLAGS=-Wl,-Bstatic -larpack -llapack -lblas \
  -L/home/rmcgibbo/opt/netcdf-4.3.3-static/lib/ -lnetcdf \
  -lbz2 -lz  -lgfortran -lquadmath \
  -w -static-libgcc -static-libstdc++
```

```
$ ldd bin/cpptraj
	linux-vdso.so.1 =>  (0x00007ffebc5c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e7aeea000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e7ab20000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a9c7145000)
```

This would also make of [this logic](https://github.com/Amber-MD/cpptraj/blob/master/configure#L702-L749) unnecessary. (edit: I guess this doesn't really work on OS X though)

**Comment by drroe** [comment]
:s/does not try very hard/is a bad hack

Yeah, I knew this little hack would catch up to me eventually. I wrote it a long time ago when cpptraj was simpler and I was the only one using the standalone configure script. I knew that instead of this stuff I should probably use the correct static flag for the compiler, but who knew other people would actually eventually work on this code? :-)

So +1 for bringing this up and I hope to get to this soon (unless someone beats me to it).

**Comment by rmcgibbo** [comment]
I don't know what the easiest way to do this in general (in a cross-platform way) is. I suspect in the long term the best option is to switch towards CMake, but obviously that's another ball of wax.

**Comment by drroe** [comment]
I think the `-libstatic` flag (#279) is a good compromise for this (at least the best one I can think of at the moment).
