### ISSUE TITLE
segmentation fault when setup action in ActionList

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#206]
from our chat, I made the log here

for the new API: https://github.com/Amber-MD/cpptraj/pull/205

You can checkout my branch: `cpptraj_Analysis_api_change`
https://github.com/hainm/pytraj (of course compile with your branch)

code

cd `tests` folder

```python
#!/usr/bin/env python

import pytraj as pt
traj = pt.iterload("data/tz2.nc", "data/tz2.parm7")
pt._verbose()
alist = pt.ActionList(['radgyr',], top=traj.top)
alist.do_actions(traj)
```

- log
```bash
    RADGYR: Calculating for atoms in mask *.
.....................................................
ACTION SETUP FOR PARM 'tz2.parm7' (1 actions):
  0: []
Segmentation fault
```

**Comment by hainm** [comment]
code for pytraj's ActionList: https://github.com/hainm/pytraj/blob/cpptraj_Analysis_api_change/pytraj/core/action_list.pyx

**Comment by drroe** [comment]
@hainm in this code snippet from `action_list.pyx` what is `action_.baseptr`?
```python
status = self.thisptr.AddAction(action_.baseptr, _arglist.thisptr[0],
                                        actioninit_)
```
From my reading of `Action` in `CpptrajActions.pyx` it seems like it's the pointer to the class itself - is that right? If so, I think what may be happening is that when the `add_action()` function finishes, `action_` is destroyed (and thus the `baseptr` is freed), leading to the eventual segfault. I believe what you have to do is define and call the action's `Alloc()` function to get a new independent instance of the `Action` to be passed to the `ActionList`. Does that make sense?

**Comment by hainm** [comment]
Make sense. I will try again and report later. Thanks.

**Comment by hainm** [comment]
phew, I did not introcude alloc method. Just don't let Cython free memory. Work for me now. thanks.

Another issue:

```python
In [5]: Command.dispatch(state, 'parm data/tz2.ortho.parm7')
Error: Data set with name 'parm' not found.
'parm data/tz2.ortho.parm7': Invalid command or expression.
```

I need to look at new Command code to know what does 'dispatch' do now.
