### ISSUE TITLE
code freeze Feb 25

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#215]
@drroe AMBER code is due by Feb 15, can we (you) try to finish new features soon and try to finish created issues? I would like to freeze pytraj code this month (Jan) and would like to have stable cpptraj API.

**Comment by hainm** [comment]
it's up to you but there are few things I would like to have in cpptraj v16.

- supporting XTC format. #156 

- updating doc (several issues)

- dump data to dataset rather stdout

and do you almost finish MPI stuff?

**Comment by drroe** [comment]
@hainm The only remaining API change I would like to get in are the changes in drroe/cpptraj/parallel_trajin, which I hope to have done soon (and I think these should be minor and may not even affect pytraj). I will try to address as many issues as I can before the code freeze, but I will probably be working right up to the Feb 15 deadline. However, I will not make any API changes after January in order to accommodate pytraj (unless it involves a code breaking bug or something).

**Comment by hainm** [comment]
Sounds good to me.

Hai

**Comment by drroe** [comment]
@hainm The new code in my parallel_trajin branch is pretty much ready to go if you want to take it for a spin. I plan on merging either tomorrow or early next week.

**Comment by hainm** [comment]
Ok. I will test tonight.

Hai

**Comment by hainm** [comment]
@drroe 

pytraj compile was stuck at 

```bash
-    ActionFrame() : frm_(0) {}
-    ActionFrame(Frame* fIn) : frm_(fIn) {}
+    ActionFrame() : frm_(0), trajoutNum_(0) {}
+    ActionFrame(Frame* fIn, int t) : frm_(fIn), trajoutNum_(t) {}
```

Should I set trajoutNum_ = 0 (always) for serial cpptraj?

**Comment by drroe** [comment]
For the blank constructor thats fine. In serial trajoutNum should be the
same as frameNum (passed to DoAction()).

On Thursday, January 21, 2016, Hai Nguyen <notifications@github.com> wrote:

> @drroe <https://github.com/drroe>
>
> pytraj compile was stuck at
>
> -    ActionFrame() : frm_(0) {}
> -    ActionFrame(Frame* fIn) : frm_(fIn) {}
> +    ActionFrame() : frm_(0), trajoutNum_(0) {}
> +    ActionFrame(Frame* fIn, int t) : frm_(fIn), trajoutNum_(t) {}
>
> Should I set trajoutNum_ = 0 (always) for serial cpptraj?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/215#issuecomment-173789634>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
thanks. tests failed, so I need a bit time to update pytraj's code.

**Comment by drroe** [comment]
Let me know if you need any help.
