### ISSUE TITLE
./configure error on OS X

### ISSUE THREAD

**Issue by rmcgibbo** [Amber-MD/cpptraj#216]
I get a syntax error when running configure on OS X

```
$ ./configure --with-netcdf=sfd

Assuming 64 bit architecture.
expr: syntax error
Unrecognized OPTION: --with-netcdf=sfd
```

When I run with `bash -x -e`, I see that the error is at [line 400](https://github.com/Amber-MD/cpptraj/blob/master/configure#L400). It [looks like](https://discussions.apple.com/thread/923299?tstart=0) BSD `expr` doesn't have the index command 
```
$ expr index --with-netcdf=sfd =
expr: syntax error
```

**Comment by rmcgibbo** [comment]
I think replacing line 400 with works, if `awk` is more portable...
```
POS=`echo $1 | awk 'match($0,"="){print RSTART}'`
```

**Comment by swails** [comment]
Ah, I don't use BSD bash on my mac -- I use the one from MacPorts (since then I can use the same .bashrc file and stuff everywhere).

Thanks for the tip, I'll file a PR for this unless you'd rather.
