### ISSUE TITLE
remove readline + libsander in libcpptraj

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#220]
I am testing pytraj in amber and got undefined symbol that relates to readline. Can  you remove it from libcpptraj since there is no use here. thanks.

> libcpptraj.so: undefined symbol: rl_attempted_completion_function

**Comment by swails** [comment]
Why not just use the `-noreadline` switch when building libcpptraj for pytraj?

**Comment by hainm** [comment]
I used the config.h file in $AMBERHOME

```bash
cd $AMBERHOME/AmberTools/src/
make pytraj
```

This is a part of Makefile
```bash
pytraj::
    (cd cpptraj && $(MAKE) -f Makefile_at libcpptraj)
```

so I am not sure where and when I can use `-noreadline` :(

**Comment by rmcgibbo** [comment]
I tried building `libcpptraj.so` with just `./configure -shared; make libcpptraj`, and that symbol is definitely defined, according to `nm`. Could be a difference between the two Makefiles.

**Comment by hainm** [comment]
@rmcgibbo: My error only appear when cpptraj is in Amber suite.

I think my problem is I did './configure -openmp gnu` first and then `make pytraj`. So libreadline is never built. :D (Installing Amber need `make install` for serial build first (@Jason: correct me if I am wrong) and do the parallel build later).

But removing libreadline from libcpptraj.so is still my wish since there is not use for it.

**Comment by hainm** [comment]
@swails we discussed about checking serial build a while ago in email. May be it's time to implement.

(`Fwd: [AMBER] Problems with the installation of ambertools15.` (on Oct 2015)

**Comment by hainm** [comment]
@Dan and Jason: can you double check if we need to make install serial version before openmp for cpptraj in amber? 

First I tried ./configure -openmp gnu

(Without serial build) then 'make cpptraj' but also got readline error. So readline is required in seriL built (which is quite complicated for cpptraj (vs standalone version)

**Comment by drroe** [comment]
> @drroe and Jason: can you double check if we need to make install serial version before openmp for cpptraj in amber?

Just downloaded a fresh copy of the Amber GIT tree; `./configure -openmp gnu` followed by `cd AmberTools/src && make cpptraj` worked for me.

**Comment by drroe** [comment]
> I think my problem is I did ./configure -openmp gnu first and then make pytraj. So libreadline is never built.

I think the solution is that the `libcpptraj` target in `cpptraj/Makefile_at` needs to clean before `make`. Also, I should probably add a define like `-D_LIBCPPTRAJ` that will remove any non-essential components during the libcpptraj build (like readline).

**Comment by hainm** [comment]
> Also, I should probably add a define like -D_LIBCPPTRAJ that will remove any non-essential components during the libcpptraj build (like readline).

sounds good to me.

**Comment by hainm** [comment]
> Just downloaded a fresh copy of the Amber GIT tree; ./configure -openmp gnu followed by cd AmberTools/src && make cpptraj worked for me.

works for me too. magic happens (or something else happened).

**Comment by hainm** [comment]
@drroe I added libsander to my wishlist too.

pytraj works nicely with standalone cpptraj on osx but things become complicated if libcpptraj links to libsander. In short, if using clang, pytraj tries to link to `/usr/lib/libstdc++6.dylib` while libcpptraj links to `/usr/local/gfortran/lib/libstdc++.6.dylib`.

This issue is strongly related to https://github.com/Amber-MD/cpptraj/issues/327

**Comment by hainm** [comment]
```python
AmberTools/src (master) $ make pytraj -j8
(cd cpptraj && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile_at libcpptraj)
/bin/rm -f src/Action_Esander.o src/Cpptraj.o src/Energy_Sander.o
cd src && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile_at libcpptraj SANDERAPI_DEF=""
clang++ -stdlib=libstdc++ -Wall -Wno-unused-function -c -I/Users/haichit/amber_git/amber/include -O3  -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DBINTRAJ -DHASGZ -DHASBZ2 -D__PLUMED_HAS_DLOPEN     -I/Users/haichit/amber_git/amber/include    -o Action_Esander.o Action_Esander.cpp
clang++ -stdlib=libstdc++ -Wall -Wno-unused-function -c -I/Users/haichit/amber_git/amber/include -O3  -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DBINTRAJ -DHASGZ -DHASBZ2 -D__PLUMED_HAS_DLOPEN     -I/Users/haichit/amber_git/amber/include    -o Cpptraj.o Cpptraj.cpp
clang++ -stdlib=libstdc++ -Wall -Wno-unused-function -c -I/Users/haichit/amber_git/amber/include -O3  -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DBINTRAJ -DHASGZ -DHASBZ2 -D__PLUMED_HAS_DLOPEN     -I/Users/haichit/amber_git/amber/include    -o Energy_Sander.o Energy_Sander.cpp
```

**Comment by drroe** [comment]
@hainm Let me know if #336 addresses this issue. Thanks.

**Comment by hainm** [comment]
yes. thanks.

**Comment by hainm** [comment]
@drroe I am a bit confused now. Does `libcpptraj` still link to `linsander`?

**Comment by hainm** [comment]
```bash
In file included from Command.cpp:118:
In file included from ./Action_Esander.h:5:
./Energy_Sander.h:6:10: fatal error: 'sander.h' file not found
#include "sander.h"
         ^
1 error generated.
make[2]: *** [Command.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libcpptraj] Error 2
make: *** [pytraj] Error 2
```

**Comment by hainm** [comment]
my commands

```bash
make distclean
git pull

export CC="clang --stdlib=libstdc++"
export CXX="clang++ --stdlib=libstdc++"

# trick (wait for Dan to update cpptraj config.h)
# -lstdc++ flag is added to fix emil error (undefined symbols for architecture x86_64)
# http://stackoverflow.com/questions/11852568/gcc-4-8-on-mac-os-x-10-8-throws-undefined-symbols-for-architecture-x86-64
$AMBERHOME/configure  -macAccelerate clang
source amber.sh
export AMBERLDFLAGS='-L/usr/lib -lstdc++

cd $AMBERHOME/AmberTools/src
make pytraj -j8
```

**Comment by drroe** [comment]
The current Amber GIT tree builds fine for me with GNU compilers on Mac OSX (El Capitan, gcc 5.3). Also, libcpptraj.dylib appears to be built without readline or libsander:
```
$ otool -L libcpptraj.dylib 
libcpptraj.dylib:
	/Users/test/Amber/GIT/amber/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/opt/local/lib/libgcc/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.21.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
And no output from:
```
$ nm -o libcpptraj.dylib | grep cpptraj_completion
```
I will now test with clang.

**Comment by hainm** [comment]
Just curious, did you make distclean before install too?

My error said cpptraj can not find sander.h

**Comment by drroe** [comment]
Yep, `make distclean` before configure/install works fine with Gnu compilers.

**Comment by hainm** [comment]
Another curiosity: did you try to make pytraj only? (Without make install in amberhome). I dont have mac in lab so can not test until evening.

**Comment by drroe** [comment]
I made all of Amber (`make install`).

**Comment by hainm** [comment]
I see. If you trying clang, please just copy and paste my code snippet above. We did install differently.

**Comment by hainm** [comment]
I've tried Linux with gcc4.4 and got identical error. Please see my commands

```bash
git pull
make distclean
./configure gnu
source amber.sh
cd AmberTools/src/
make pytraj -j8
```

**Comment by hainm** [comment]
This is behind the scene of `make pytraj`

```python
(cd cpptraj && $(MAKE) -f Makefile_at libcpptraj)
(cd pytraj && $(PYTHON) setup.py install --disable-openmp $(PYTHON_INSTALL) --no-setuptools)
```

So I guess cpptraj try to compile both objects for cpptraj and libcpptraj. cpptraj require `sander.h` file.

**Comment by drroe** [comment]
OK, I think I see the issue now. The problem is that even though Command.o is the same object for cpptraj and libcpptraj, it includes a file that _is_ different. I didn't catch this initially because I was focused on `Energy_Sander.h`. I think if I create a separate Command.LIBCPPTRAJ.o the problem will go away. I'll do some tests and if that fixes it I'll create a PR to deal with it.

**Comment by drroe** [comment]
OK, try the Amber GIT tree now. #341 seems to have at least fixed the recent compile issue.

**Comment by hainm** [comment]
ok with Linux. I will test osx tonight. thanks.

**Comment by hainm** [comment]
@drroe: `AMBERLDFLAGS` does not behave as I am expecting (mostly due to my limited knowledge
about `make`)

So this is my testing.

- regular `make pytraj`: This is the linking line in the end of libcpptraj making (I truncated the message)
```bash
-L/Users/haichit/amber_git/amber/lib /Users/haichit/amber_git/amber/lib/libnetcdf.a
```

- `export AMBERLDFLAGS='-L/usr/lib'` and then `make pytraj`
```bash
-L/Users/haichit/amber_git/amber/lib /Users/haichit/amber_git/amber/lib/libnetcdf.a
```

So nothing change.

- But if I do `export AMBERBUILDFLAGS='-L/usr/lib'` and then `make pytraj`: 
```bash
# Note: -L/usr/lib is inserted as I am expecting
-L/usr/lib -L/Users/haichit/amber_git/amber/lib /Users/haichit/amber_git/amber/lib/libnetcdf.a
```

Is there any way I can set environment by 'export' in terminal rather editing `config.h` file?

**Comment by hainm** [comment]
uhm, it's likely AMBER only users to set `AMBERBUILDFLAGS`.

**Comment by hainm** [comment]
close now. I will update configure2. thanks.
