### ISSUE TITLE
add more test for cpptraj

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#23]
I (again) encourage to upload more cpptraj's tests

We could make 'Amber-MD/CpptrajAdditionalTestSuite' (or any interesting name).

and add to `.travis.yml` file

```
git clone https://github.com/Amber-MD/CpptrajAdditionalTestSuite
cd CpptrajAdditionalTestSuite && make test
```

Benefit
* pytraj can pull and test
* minimize break cpptraj's code when someones make PR
* travis does all the tests, so we don't 'forget'

**updated**
Some of tests I would like to have on github
- [ ] lifetime

**Comment by swails** [comment]
We've talked about this and decided to go with what was in the Amber test directory for now.

Dan's supplemental tests are 10s of GB with large binary files.  That simply cannot be uploaded to Github, regardless of whether it's in a different repo or not.  Keeping everything in the same repo will help keep the tests and code up-to-date.  And source code is so small that breaking off a separate repo just for tests will likely not buy appreciable extra space, so the more I think about it the more I'm in favor of keeping everything in one repository.

+1 on more tests, but they will have to be adapted and scaled down from Dan's supplemental suite to fit on GH.

**Comment by drroe** [comment]
I may be able to add a few more tests from my extended suite that are small and use existing test coordinates/topologies. As Jason said, the entire extended test suite is just to big to host on GitHub.
I was thinking maybe I could give certain people (you, Jason etc) access to the extended test Git repo I host on my PC at U Utah. I just need to look into how to do that :-). The tests won't run automagically but then at least you'd have access to them.

**Comment by hainm** [comment]
@drroe 

I will update a list of tests I would like to see on  github. First thing is `lifetime`.

**Comment by drroe** [comment]
Although coverage is not 100% complete, I think I've added enough new tests that this can be closed.
