### ISSUE TITLE
add stride for loading traj?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#237]
I am not sure if cpptraj has this or not in loading traj.

```bash
parm 2koc.parm7
trajin traj0.nc 1 100 10
trajin traj1.nc 1 100 10
trajin traj2.nc 1 100 10
trajin traj3.nc 1 100 10
trajin traj4.nc 1 100 10
```

can be shortened by
```bash
parm 2koc.parm7
trajin traj*.nc stride 10
```

**Comment by drroe** [comment]
Why not just use the existing syntax?
```
trajin traj*.nc 1 last 10
```
I don't see any benefit to adding `stride`.

**Comment by swails** [comment]
@hainm's suggested syntax is equivalent to

```
trajin traj*.nc 1 10000000 10
```

**Comment by hainm** [comment]
thanks all. cool, I did not know cpptraj has above syntax.

**Comment by swails** [comment]
Oh, I didn't realize what "last" did :).  :+1: on this -- it's clearer about what the first frame should be.
