### ISSUE TITLE
rmsd test for refmask

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#244]
seems cpptraj github does not have it yet

```
[<name>] <mask> [<refmask>]
```

**Comment by hainm** [comment]
I guess this syntax is legit

```python
        parm data/Tc5b.top [tc5b]
        trajin data/Tc5b.x [tc5b]
        parm data/tz2.parm7 [tz2]
        reference data/tz2.nc parm [tz2] 1 [myref]
        rms myrmsd ref [myref] @1-10 @11-20
```

**Comment by drroe** [comment]
In `/test/Test_General/RunTest.sh`:

https://github.com/Amber-MD/cpptraj/blob/1a6ceaa7703c9d694c6b0717cf2c2c8f05353469/test/Test_General/RunTest.sh#L38-L39

Reference masks are explicitly defined for both `rmsd` commands.

**Comment by hainm** [comment]
thanks Dan.
