### ISSUE TITLE
remlog command 

### ISSUE THREAD

**Issue by roitberg** [Amber-MD/cpptraj#26]
Can we try to make the remold command work with ph remd style remlogs ?

**Comment by drroe** [comment]
@roitberg Check out my cpptraj fork, branch read_ph_remlog.

**Comment by hainm** [comment]
from Dan's personal repo
https://github.com/drroe/cpptraj/tree/read_ph_remlog

**Comment by drroe** [comment]
Actually my initial tests look weird :-/. Feel free to try it but consider
it alpha. Pretty sure its not working correctly.

On Fri, Aug 7, 2015 at 3:38 PM, Hai Nguyen <notifications@github.com> wrote:

> from Dan's personal repo
> https://github.com/drroe/cpptraj/tree/read_ph_remlog
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/26#issuecomment-128839029>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by drroe** [comment]
OK, after latest push results seem more reasonable but still needs more
testing. You can probably try it on some short logs.

On Fri, Aug 7, 2015 at 3:43 PM, Daniel Roe <daniel.r.roe@gmail.com> wrote:

> Actually my initial tests look weird :-/. Feel free to try it but consider
> it alpha. Pretty sure its not working correctly.
>
> On Fri, Aug 7, 2015 at 3:38 PM, Hai Nguyen <notifications@github.com>
> wrote:
>
>> from Dan's personal repo
>> https://github.com/drroe/cpptraj/tree/read_ph_remlog
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Amber-MD/cpptraj/issues/26#issuecomment-128839029>.
>>
>
>
>
> --
> -------------------------
> Daniel R. Roe, PhD
> Department of Medicinal Chemistry
> University of Utah
> 30 South 2000 East, Room 307
> Salt Lake City, UT 84112-5820
> http://home.chpc.utah.edu/~cheatham/
> (801) 587-9652
> (801) 585-6208 (Fax)
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by drroe** [comment]
Closed via #80
