### ISSUE TITLE
Too many concurrent Travis-CI builds

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#273]
@swails Right now it seems like the max number of concurrent builds is 4. If the OSX one with clang eventually works, what do you think of getting rid of the plain clang one?

**Comment by hainm** [comment]
also, osx build is quite slow to start. I have only a single job submitted a while ago but it has not started yet: https://travis-ci.org/hainm/pytraj/builds/111883111

**Comment by drroe** [comment]
Oh - maybe the problem is that Travis-CI just doesn't have a lot of macs to go 'round.

**Comment by swails** [comment]
I believe 5 concurrent builds will start at once.  But don't forget that every time you merge, it starts all the tests over again.

But getting rid of the regular clang build is probably fine if we have Macs testing clang.  How much time is it adding to the test process?

**Comment by hainm** [comment]
I think 4 linux builds are fine. It takes time for osx to start.

**Comment by drroe** [comment]
Testing has been fine for a while at this point, so I'm deeming this a non-issue.
