### ISSUE TITLE
better (and nicer) data label?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#28]
currently pytraj use cpptraj's Dataset's legends as keys for python dictionary. 

for example

```python
In [3]: d = pt.multidihedral(traj, resrange=[0, 3 ,5])

In [4]: d.keys()
Out[4]:
['psi:1',
 'phi:4',
 'psi:4',
 'chip:4',
 'omega:4',
 'phi:6',
 'psi:6',
 'chip:6',
 'omega:6']
```

It's nice that when converting to panda's DataFrame, we can access the key by class's attribute
```python
In [5]: df = pt.multidihedral(traj, resrange=[0, 3 ,5], dtype='dataframe')

In [6]: df.psi_1
Out[6]:
0    176.615564
1    166.821296
2    168.795100
3    167.425619
4    151.183350
5    134.176110
6    160.992079
7    165.112697
8    147.943321
9    145.429014
Name: psi_1, dtype: float64
```
So my question to discuss is:

Should we spend a bit time to name the labels to make them nicer? Or I just go ahead changing them in `pytraj` to what I want and cpptraj still keep its name's convention? If Dan agrees that we can change cpptraj' side, I can spend more time make suggestions about naming (although I know that @swails  is really good at naming stuff). :D 

For example, hbond in cpptraj use 'UU', "UV" for legends. To my view, those are hard to understand and remember. Especially cpptraj prints those to output.

And to use pandas like above, I need to replace `:` to `_`  (`psi:1` to '`psi_1`) and `-` to `_` in python.

**Comment by hainm** [comment]
additionally, there are some outputs that are hard to look at.

```python
        DSSP_00000[None] "DSSP_00000[None]" (float), size is 10
        DSSP_00000[Para] "DSSP_00000[Para]" (float), size is 10
        DSSP_00000[Anti] "DSSP_00000[Anti]" (float), size is 10
        DSSP_00000[3-10] "DSSP_00000[3-10]" (float), size is 10
        DSSP_00000[Alpha] "DSSP_00000[Alpha]" (float), size is 10
        DSSP_00000[Pi] "DSSP_00000[Pi]" (float), size is 10
        DSSP_00000[Turn] "DSSP_00000[Turn]" (float), size is 10
        DSSP_00000[Bend] "DSSP_00000[Bend]" (float), size is 10
        DSSP_00000[res]:1 "SER:1" (integer), size is 10
        DSSP_00000[res]:2 "TRP:2" (integer), size is 10
        DSSP_00000[res]:3 "THR:3" (integer), size is 10
        DSSP_00000[res]:4 "TRP:4" (integer), size is 10
        DSSP_00000[res]:5 "GLU:5" (integer), size is 10
        DSSP_00000[res]:6 "ASN:6" (integer), size is 10
        DSSP_00000[res]:7 "GLY:7" (integer), size is 10
        DSSP_00000[res]:8 "LYS:8" (integer), size is 10
        DSSP_00000[res]:9 "TRP:9" (integer), size is 10
        DSSP_00000[res]:10 "THR:10" (integer), size is 10
        DSSP_00000[res]:11 "TRP:11" (integer), size is 10
        DSSP_00000[res]:12 "LYS:12" (integer), size is 10
        DSSP_00000[res]:13 "NHE:13" (integer), size is 10
```

**Comment by hainm** [comment]
any way, the issue I am opening here has very low priority (just make pytraj/cpptraj looks prettier). Not that a big deal.

**Comment by drroe** [comment]
@hainm Is this issue still relevant to you or have you done your own name changing like you mentioned above? I definitely can not change any of the current aspects etc (e.g. UU and UV in hbond) since data set selection uses them and it will break backwards compatibility. For example, if anyone has something like:
```
writedata solutehb.agr HB[UU]
```
then changing the `UU` aspect will break this. Also, if I change a legend like
```
LYS_12@O-SER_1@N-H3
```
to
```
LYS12_O-SER1_N-H3
```
this is actually less informative in my opinion since `@` means atom in Amber mask syntax.

If you have no strong objections we can close this.

**Comment by hainm** [comment]
> If you have no strong objections we can close this.

no I don't. (I went ahead changing in pytraj). pytraj/cpptraj has been here for decades, so not worth breaking.
