### ISSUE TITLE
move dna to box

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#286]
hi,

which command I should use to move the dna to the water box?

(file: reimage.mdcrd.save from cpptraj test)

![screenshot-3](https://cloud.githubusercontent.com/assets/4451957/13688708/85e0b33a-e6f1-11e5-8bc8-3e5351806227.png)

**Comment by drroe** [comment]
Not sure what you mean here; the DNA *is* in the water box. It has just been stretched to the point where it is now tilting to avoid hitting images of itself (you can see this in the way the water is parted to the left and right of this image.

**Comment by hainm** [comment]
oh, I should spend more time with PBC, too many years using implicit solvent. :D thanks.
