### ISSUE TITLE
testing with different compilers and different combo

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#287]
may be you (@drroe) can create a repo in your account to test with different compilers? This is not needed to be done frequently so just let the jobs run slowly (few hours?).

Example of many combination: https://travis-ci.org/serge-sans-paille/pythran.

(or may be this is not necessary, close if you want).

**Comment by drroe** [comment]
I don't think this is necessary as of right now. May be better to just add one or two additional test setups (maybe as suggested in #326).

**Comment by hainm** [comment]
yeah.
