### ISSUE TITLE
Recognition of Arbitrary Units in Helix for Helical Parameters

### ISSUE THREAD

**Issue by rwmolt** [Amber-MD/cpptraj#290]
Pursuant to the request of Dr. Hai Nguyen, it would be desirable if one could define an arbitrary unit as a nucleic acid in a helix for cpptraj. This would allow for the analysis of base-pair step parameters within cpptraj for non-standard nucleic acids which may have different atomic linkages than standard nucleic acids.

D. Roe. made a lovely post on the Amber forums outlining changes needed to the code to do this, in principle. Should I be able to persuade my post-doc advisor, I would like to do this myself (but it is questionable if time allows).

@hainm Is more detailed than this desired? Happy to be useful, given how much the Amber forums have helped me do what I need to do.

**Comment by drroe** [comment]
@rwmolt Sorry for the delay on this, but it's now done (more or less). See details here: #342. If you get a chance to try it I'd appreciate any feedback.

**Comment by drroe** [comment]
Since this has been in for a while and there have been no objections I'm going to close this. If any problems arise they can be addressed in a new issue.
