### ISSUE TITLE
Argument lists able to access data sets

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#302]
Idea is to allow ArgLists access to data in the master DataSetList, e.g.

```
val = 3
hbond dist val ...
```

This may be tricky since the simplest version (i.e. the version where I don't rewrite every single instance of ArgList) is going to require that ArgList be able to access the master DSL internally; currently not possible due to circular dependency.

**Comment by hainm** [comment]
what is this example different from bash script?

```bash
val = 3
hbond dist val ...
```

**Comment by drroe** [comment]
It's just a simple example. Ideally you could do something like what was mentioned on the Amber mailing list today: determine the max/min values from projection of principal components and use those values for `modes trajout`. The difference is that this will all be internal rather than having to have multiple cpptraj runs combined with scripting. 

It seems to me you should be able to do this in pytraj now as long as pytraj can access the data from cpptraj. However, this will give users more options in the long run. It's also been on my internal To-Do list for ages.

**Comment by drroe** [comment]
This has largely been addressed by the addition of "script" variables (#556) so I'm considering this accomplished.
