### ISSUE TITLE
update absolute path for libcpptraj in standalone version: need for OSX

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#314]
```bash
# libcpptraj ---------------------------
libcpptraj: $(LIBCPPTRAJ_TARGET)

libcpptraj$(SHARED_SUFFIX): $(OBJECTS) $(FFT_DEPEND) $(READLINE_TARGET)
        ...
	/bin/mv libcpptraj$(SHARED_SUFFIX) $(CPPTRAJLIB)
```

I tried to follow Jason's commit for Makefile_at but I am still noob with Makefile stuff.

This is good for OSX to avoid Image not found error.

`Makefile_at`
```bash
$(LIBDIR)/libcpptraj$(SHARED_SUFFIX): $(OBJECTS) pub_fft.o $(EXTERNAL_LIBS)
...
```

**Comment by hainm** [comment]
``pytraj`` can auto-fix but sometimes users want to install `libcpptraj` by them-self for their own apps.

**Comment by drroe** [comment]
@hainm #334 seems to work well for me on OSX. Can you verify as well? Thanks

**Comment by hainm** [comment]
confirmed. thanks.
