### ISSUE TITLE
cpptraj website + html doc

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#318]
I mention the `html` stuff with you and Jason before (for AMBER man). But I still think it's good if you (Dan) can convert cpptraj's manual to `html` format and push it to website.

Currently:

pytraj doc: [http://amber-md.github.io/pytraj](http://amber-md.github.io/pytraj)

So you can create a branch name `gh-pages`, make and `index.html` and make cpptraj html doc.
[http://amber-md.github.io/cpptraj](http://amber-md.github.io/cpptraj) should be available. For me, reading cpptraj doc in PDF format is hard. For example, how can I find "cif" format that relates to cpptraj section?

**Comment by drroe** [comment]
Addressed by #601.
