### ISSUE TITLE
RMSD: option not to dump data  to dataset?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#320]
hi,

is there any option that only perform rms fit without dumping rmsd value to dataset?

My issue is: I want to use out of core TrajectoryIterator with NGLView and want to perform transformation in the fly: `rmsd`, `center`, `autoimage`... 

To make things easier, I use `ActionList` to store all actions, whenever iterating to get Frame, I call `ActionList` to do action on Frame (so all transformations will be done by cpptraj to avoid python overhead). However, cpptraj dumps rmsd data to DataSetList. This is ok for cpptraj context but it's not OK if I want to play the movie again and again.

Of course, I can reuse `Frame` translation and rotation methods but this can't not be combined this with `ActionList`.

Any suggestion?

**Comment by hainm** [comment]
My current work around is: whenever the Dataset length reaches 1000 (frames), pytraj will remake `ActionList`, `DatasetList`, ...

**Comment by drroe** [comment]
There is currently no option to do this. Adding one is possible, but if all you need is the RMS fit maybe it would be better to just have pytraj do it via `Frame::RMSD()` or one of the other RMSD functions - is that possible? Or does that involve the python overhead you mentioned in your initial post?

> perform transformation in the fly: rmsd, center, autoimage...

Just to make certain, you should image *before* performing an RMS fit. Also, `center` is redundant if you are using `autoimage` (since `autoimage` performs centering).

> My current work around is: whenever the Dataset length reaches 1000 (frames), pytraj will remake ActionList, DatasetList, ...

Couldn't you just remake the ActionList and DataSetList whenever you hit "play"?

**Comment by hainm** [comment]
> Couldn't you just remake the ActionList and DataSetList whenever you hit "play"?

I want `pytraj` to be dependent from `nglview`. 

> Adding one is possible, but if all you need is the RMS fit maybe it would be better to just have pytraj do it via Frame::RMSD() or one of the other RMSD functions - is that possible? 

I want to use `RMSD` in `ActionList` so I can keep adding more actions.

```python
(traj.autoimage()
      .superpose()
      .translate('x 3.2')
      .scale('...'))
```

```python
actlist.add('autoimage')
actlist.add('rms')
actlist.add('translate')
...
for frame in traj: actlist.compute(frame)
``` --> much simple.

> Just to make certain, you should image before performing an RMS fit. Also, center is redundant if you are using autoimage (since autoimage performs centering).

ah yes, I am aware of doing `autoimage` before doing `rms` (read many emails from maillist).

**Comment by hainm** [comment]
> Also, center is redundant if you are using autoimage (since autoimage performs centering).

but `center` has option to center at `origin` too.

**Comment by hainm** [comment]
**updated**

> I want pytraj to be dependent from nglview. 

**dependent** should be **independent**

**Comment by hainm** [comment]
![cjaa_f7wyaavoos jpg large](https://cloud.githubusercontent.com/assets/4451957/15518752/6033a712-21cc-11e6-8348-cfcbae324061.jpg)

the main point here is I don't care about how many files are there in folder, how large are they, I just make `TrajectoryIterator` and view them, jump to some frames without caring about writing more code to load frames to memory. (btw, > 1TB trajectory is in above image).

**Comment by drroe** [comment]
> but center has option to center at origin too.

Does `autoimage origin` not do what you want? At any rate, just wanted to make the point that anything `center` does will be overwritten by `autoimage` anyway if the former precedes the latter (and vice-versa I suppose).

**Comment by drroe** [comment]
Since this is something that seems relevant only for pytraj, maybe it makes sense to create an action the sole purpose of which is to perform RMS fitting without doing anything else (call it `align` or something). How does that sound?

**Comment by hainm** [comment]
> Does autoimage origin not do what you want? At any rate, just wanted to make the point that anything center does will be overwritten by autoimage anyway if the former precedes the latter (and vice-versa I suppose). 

ah yes. I was just thinking about `autoimage()` then do bla bla, then `center` to do bla bla. This is my playground.

> Since this is something that seems relevant only for pytraj, maybe it makes sense to create an action the sole purpose of which is to perform RMS fitting without doing anything else (call it align or something). How does that sound?

sound fantastic. it would be great to have functionality of current RMSD action, of which we can superpose traj to reference with different mask region.

**Comment by drroe** [comment]
@hainm Let me know if #335 does what you need.

**Comment by hainm** [comment]
I am testing.

**Comment by hainm** [comment]
good now. thanks.
