### ISSUE TITLE
wrong conect for PDB?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#322]
hi,

I got those lines 

```
...
CONECT 9999 9998100001002010021
CONECT10000 999910001
CONECT1000110000100021000310004
CONECT1000210001 
CONECT1000310001
CONECT1000410001100051000610007
CONECT1000510004 
CONECT1000610004
CONECT1000710004100081001210016
CONECT1000810007100091001010011
CONECT1000910008 
...
```

input
```bash
parm DOPC_128.prmtop
trajin DOPC_128.inpcrd
trajout dopc.pdb conect
```

files: http://ambermd.org/tutorials/advanced/tutorial16/#LEaP

**Comment by drroe** [comment]
Why do you think it's wrong? Are the serial #s incorrect?

On Monday, May 16, 2016, Hai Nguyen <notifications@github.com> wrote:

> hi,
>
> I got those lines
>
> ...
> CONECT 9999 9998100001002010021
> CONECT10000 999910001
> CONECT1000110000100021000310004
> CONECT1000210001
> CONECT1000310001
> CONECT1000410001100051000610007
> CONECT1000510004
> CONECT1000610004
> CONECT1000710004100081001210016
> CONECT1000810007100091001010011
> CONECT1000910008
> ...
>
> input
>
> parm DOPC_128.prmtop
> trajin DOPC_128.inpcrd
> trajout dopc.pdb conect
>
> files: http://ambermd.org/tutorials/advanced/tutorial16/#LEaP
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/322>
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
I normally see this
```
CONECT  206  203  207  208  209
CONECT  207  206
CONECT  208  206
```

but not below
```
CONECT1000710004100081001210016
```

let me double large pdb file from rcsb.

**Comment by hainm** [comment]
close. this is normal :D 

http://files.rcsb.org/view/1FFK.pdb

**Comment by drroe** [comment]
> I normally see this

Yes, remember that PDB is a fixed-width format, not whitespace-delimited.
