### ISSUE TITLE
libcpptraj installed on appveor

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#324]
just open an issue here as a place holder. I am interested in making pytraj works on Windows (mostly to be used as backend for [NGLView](https://github.com/arose/nglview)).

I am lucky that I am using Windows ( :)) ). But compiling cpptraj in my laptop is really pain, took almost an hour. So I am thinking about just copying libcpptraj built by appveor so I can play with pytraj setup in win.

Not sure how this can be done.

related

- omnia have conda build for cpptraj  just by copying files from appveor
https://github.com/omnia-md/conda-recipes/blob/master/cpptraj/bld.bat

- lengthy discussion about building on windows 
- https://github.com/Amber-MD/cpptraj/pull/192
- https://github.com/Amber-MD/cpptraj/pull/197

**Comment by hainm** [comment]
oop, just realize that I have `wine` in my lap desktop.

**Comment by swails** [comment]
You can also build the mingw compilers on Linux and cross-compile libcpptraj for use on Windows.  That's what I did for both libcpptraj, libsander, and libnetcdf awhile ago and it worked fine.

**Comment by hainm** [comment]
> You can also build the mingw compilers on Linux and cross-compile libcpptraj for use on Windows. That's what I did for both libcpptraj, libsander, and libnetcdf awhile ago and it worked fine.

cool. I will try.

**Comment by hainm** [comment]
I was able to install cpptraj and libcpptraj with mingw32. 

The next step is how to install pytraj with libcpptraj.

`libpython27.a: error adding symbols: File format not recognized`

such a window adventure. ha ha.

**Comment by hainm** [comment]
I can build conda package for libcpptraj now. still need to figure out how to compile pytraj. close this issue.

**Comment by swails** [comment]
I would say copy the library to a Windows machine and build it there.  Python's distutils should take care of most of the heavy lifting.  (Although you may need VisualStudio for that to work).  Otherwise, you'll need to build a Windows-compatible Python using mingw and link to that dll.
