### ISSUE TITLE
OSX: not build libcpptraj with arpack if using macAccelerate?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#339]
I don't see the need for using `arpack` in pytraj. If using osx, I prefer to have `pytraj` to use macAccelerate. 

It's easy for standalone cpptraj, just adding `-noarpack`. But things become more complicated in AMBER.

Why?

I installed gfortran6.1 and built libcpptraj/pytraj with `clang++ -stdlib=libstdc++` but getting memory free error. This is because `libcpptraj` was linked to `/usr/local/gfortran/lib/libstdc++.6.dylib` while
pytraj was linked to `/usr/lib/libstdc++.6.dylib`

PS: may be I am wrong about `arpack` issue.

AMBER (not OK: memory error)
-------------------------------------------
```bash
export CXX='clang++ -stdlib=libstdc++'
export CXX=/usr/local/bin/g++-6
./configure -macAccelerate clang
```

cpptraj alone version (OK: NO memory error)
------------------------------------------------------------
```bash
./configure -shared -macAccelerate -noarpack clang "CXX=clang++ -stdlib=libstdc++"
```

**Comment by drroe** [comment]
> I don't see the need for using arpack in pytraj.

Doesn't pytraj use diagmatrix under the hood for PCA? If you don't use ARPACK then eigenvector/eigenvalue determination will become very slow for large matrices.

**Comment by hainm** [comment]
thanks for info. 

I've figured flags to make this work in AMBER/osx/miniconda: https://github.com/Amber-MD/osx_install_guide/blob/master/clang.md

So I am closing now (and you made a good point).
