### ISSUE TITLE
multidihedral: suppose to calculate all supported dihtype but only few

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#34]
hi,

this is my input
```
parm G5.pdb
trajin G5.pdb
multidihedral out test_all.out
multidihedral delta out test_delta.out
```

For the `multidihedral out test_all.out` line, cpptraj said 
``` 
[multidihedral out test_all.out]
    MULTIDIHEDRAL: Calculating phi psi chip omega alpha beta gamma delta epsilon 
zeta nu1 nu2 chin chin dihedrals for all solute residues.
    Output to test_all.out
    Output range is -180 to 180 degrees.
```

But this is all I got
```python
#Frame        gamma:1      delta:1        nu1:1        nu2:1       chin:1
       1      60.6213      96.8920     -35.6519      35.4184    -176.7765
```

To make sure I cal get `delta` value, I explicitly add `multidihedral delta out test_delta.out` and got
```python
#Frame        delta:1
       1      96.8920
```

Is this your intention?

Full output is here: https://gist.github.com/hainm/54883c68d13f3d0cb3a7
pdb file is here: https://github.com/pytraj/pytraj/blob/master/tests/data/Test_NAstruct/G5.pdb

thanks

Hai

**Comment by drroe** [comment]
Well, for G5, which is I'm assuming a 5' nucleotide (no phosphate group) there shouldn't be an alpha, beta, epsilon, or zeta. So this seems OK to me.

**Comment by hainm** [comment]
@drroe but there is `delta` ... and cpptraj says it calculate this dih. (check my log file in 1st post)

**Comment by drroe** [comment]
I guess I'm missing what the problem is. Your first output:
```
#Frame        gamma:1      delta:1        nu1:1        nu2:1       chin:1
       1      60.6213      96.8920     -35.6519      35.4184    -176.7765
```
Second output:
```
Frame        delta:1
       1      96.8920
```
Same value for delta in both, right?

**Comment by hainm** [comment]
ack. I am sorry. lol. I don't know why I did not see `delta`. :D :+1:
