### ISSUE TITLE
join topology and write trajectory to pdb, got weird characters

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#343]
this is mostly `pytraj` issue but I just don't know why.

Basically I use `join` to join two Topology and then use it for a combined coordinates trajectory.

If keeping that Topology in memory and then write pdb file, I got 

```python
ATOM    234  H3 <85>NME    13      -9.877   4.041  -0.293  0.00  0.00           H
ATOM    235  HA  NME    13      -8.930   2.162  -1.239  0.00  0.00           H
ATOM    236  HB2        13      -9.310   4.417  -3.193  0.00  0.00           H
ATOM    237  HB34NME    13      -9.108   2.719  -3.679  0.00  0.00           H
ATOM    238 HD21        13     -11.572   3.791  -4.444  0.00  0.00           H
ATOM    239 HD22        13     -12.757   3.183  -3.294  0.00  0.00           H
ATOM    240  N  ^QLEU A  14      -6.379   4.031  -2.228  0.00  0.00           N
ATOM    241  CA      A  14      -4.923   4.002  -2.452  0.00  0.00           C
ATOM    242  C       A  14      -4.136   3.187  -1.404 -0.00  0.00           C
ATOM    243  O  ªLEU A  14      -3.391   2.274  -1.760  1.88  0.00           O
ATOM    244  CB      A  14      -4.411   5.450  -2.619  0.00  0.00           C
ATOM    245  CG      A  14      -4.795   6.450  -1.495  0.00  0.00           C
ATOM    246  CD1     A  14      -3.612   6.803  -0.599  0.00  0.00           C
ATOM    247  CD2     A  14      -5.351   7.748  -2.084  0.00  0.00           C
ATOM    248  H       A  14      -6.821   4.923  -2.394  0.00  0.00           H
ATOM    249  HA ^DLEU A  14      -4.750   3.494  -3.403  0.00  0.00           H
ATOM    250  HB2     A  14      -3.340   5.414  -2.672  0.00  0.00           H
ATOM    251  HB3<98>LEU A  14      -4.813   5.817  -3.564  0.00 -0.00           H
ATOM    252  HG      A  14      -5.568   6.022  -0.85819157498441713202509667516700164096.00  2.63           H
```

You can see that there are weird characters.

However if I save the joined Topology to disk to parm7 file then reload to new Topology and use the new one as Topology for my trajectory, the written pdb files are fine.

This is code for joining topology
```python
    def join(self, Topology top):
        if top is self:
            raise ValueError('must not be your self')
        self.thisptr.AppendTop(top.thisptr[0])
        return self
```

**Comment by hainm** [comment]
this is `pytraj` code (in case you want to run by yourself (you just need to copy and paste))

```python
import pytraj as pt

traj = pt.datafiles.load_tz2()[:1]
traj2 = pt.datafiles.load_trpcage()[:1]

# join coordinates
traj3 = traj + traj2

# pdb file is weird
traj3.save("test.pdb", overwrite=True)

# pdb file is ok
traj3.top.save("new.parm7")
traj3.top = pt.load_topology("new.parm7")
traj3.save("test2.pdb", overwrite=True)
```

**Comment by drroe** [comment]
Does the combining work in cpptraj? Will something like the following work?
```
parm tz2.parm7
loadcrd tz2.rst7 name tz2
parm trpcage.parm7
loadcrd trpcage.rst7 name trpcage
combinecrd tz2 trpcage crdname combined
crdout combined combined.pdb
```

**Comment by hainm** [comment]
> Does the combining work in cpptraj? Will something like the following work?

yes, that does.

**Comment by hainm** [comment]
The weird thing is that the weird characters only appear if I used created Topology (from `AppendTop`) in memory. If I save that topology to disk (to `parm7` format (not tried others)) and reload, there is no issue.

**Comment by drroe** [comment]
> The weird thing is that the weird characters only appear if I used created Topology (from AppendTop) in memory. If I save that topology to disk (to parm7 format (not tried others)) and reload, there is no issue.

That indicates something is going wrong with the copying in memory. Based on where the weird characters show up it seems like it might be the atom name that's getting corrupted somehow.

**Comment by drroe** [comment]
Closing this since it works in cpptraj. Moved the issue to the pytraj repo.
