### ISSUE TITLE
adding CPPTRAJLDFLAGS and CPPTRAJCXXFLAGS

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#345]
hi, after spending my weekend to try to make osx/clang/miniconda work with pytraj/libcpptraj and failed due to messing up with other packages in AMBER (e.g. emil). I think it's much easier to pass only extra flags to libcpptraj build.

Please check my patch here. To test, you should have miniconda/anaconda python.

```bash
git apply patch_osx_clang.txt
./configure -macAccelerate clang
make install
# or just checking pytraj first
# (cd AmberTools/src && make pytraj -j8 && cd ../tests/ && make test.pytraj)
```

[patch_osx_clang.txt](https://github.com/Amber-MD/cpptraj/files/288610/patch_osx_clang.txt)

Since this only takes effect with osx/clang/miniconda(or anaconda), other configurations are not affected.

**Comment by drroe** [comment]
Should be addressed by #379

**Comment by hainm** [comment]
Thanks. I will try.

**Comment by hainm** [comment]
worked for me. thanks. close now.
