### ISSUE TITLE
in-memory reference

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#35]
like we discussed a while ago about reference structure (via email), currently cpptraj use reference from disk.

But it's more convenient to use in-memory reference (especially in `pytraj`). For example, we can in the fly create reference structure from any source (by loading `xyz` coordinate, like from Gaussian output) and use the reference for extra actions. 

(PS: I raise this issue again when looking at Dan's example
```
parm ../tz2.parm7
reference ../tz2.rst7
trajin pp2.rst7.save
# Apply backbone dihedrals from reference structure residues 1-13 to residues 1-13
makestructure "ref:1-13:tz2.rst7"
```

PS2: (@ Dan: you can search 'how to use 'reference' without loading from file' in your email)

**Comment by drroe** [comment]
This can already be done. See code in Action_Average (for the crdset keyword). Here is a brief example:
```C++
Frame AvgFrame_;
Topology AvgParm_;
DataSet* crdset_ = DSL->AddSet(DataSet::REF_FRAME, crdName, "AVGSTRUCT");
DataSet_Coords_REF& ref = static_cast<DataSet_Coords_REF&>( *crdset_ );
ref.SetTopology( AvgParm_ );
ref.AddFrame( AvgFrame_ );
```

**Comment by hainm** [comment]
thx. I will try and report later.

**Comment by drroe** [comment]
Any updates on this?

**Comment by hainm** [comment]
@drroe I have not tried yet. Currently ``pytraj`` just use the trick by pushing the reference to 1st frame (cpptraj uses default 'first').

Do you want me to close this? Or just make 'low priority' like the label says?

**Comment by hainm** [comment]
I go ahead closing this issue.

**Comment by hainm** [comment]
@drroe Actually the in-memory ref can be solved by using 'refindex'. Just need to add ref to DSL, right? I've tried and seems working for me.

**Comment by drroe** [comment]
FYI, 'refindex' refers to the reference data set's position in the DataSetList, so refindex 0 is the first, refindex 1 is the second, and so on.

**Comment by hainm** [comment]
:+1:
