### ISSUE TITLE
no force option anymore?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#362]
pytraj has a test failed with your recent force/velocity update #358.

`Warning: The 'force' keyword is no longer necessary and has been deprecated.`
(Basically output trajectory has no force although I specify 'force' option. Worked before.

How can I fix it? thanks

Minimal testing script

```python
import pytraj as pt
from pytraj.testing import cpptraj_test_dir # OK if you either have CPPTRAJHOME or AMBERHOME

def test_write_force_and_velocity():
    fn = cpptraj_test_dir + '/Test_systemVF/systemVF.nc'
    tn = cpptraj_test_dir + '/Test_systemVF/systemVF.parm7'

    traj = pt.iterload(fn, tn)
    assert traj.metadata['has_force']
    print(traj[0].force)

    fn2 = 'test.nc'
    traj.save(fn2, overwrite=True, options='force') # no velocity

    traj2 = pt.iterload(fn2, traj.top)
    assert traj2.metadata['has_force']
    print(traj2[0].force) # got None

test_write_force_and_velocity()
```

**Comment by drroe** [comment]
As the message states, 'force' is no longer necessary. Remove 'force'.

On Wed, Jun 22, 2016 at 2:12 PM, Hai Nguyen <notifications@github.com>
wrote:

> pytraj has a test failed with your recent force/velocity update #358
> <https://github.com/Amber-MD/cpptraj/issues/358>.
>
> Warning: The 'force' keyword is no longer necessary and has been
> deprecated.
> (Basically output trajectory has no force although I specify 'force'
> option. Worked before.
>
> How can I fix it? thanks
>
> Minimal testing script
>
> import pytraj as ptfrom pytraj.testing import cpptraj_test_dir # OK if you either have CPPTRAJHOME or AMBERHOME
> def test_write_force_and_velocity():
>     fn = cpptraj_test_dir + '/Test_systemVF/systemVF.nc'
>     tn = cpptraj_test_dir + '/Test_systemVF/systemVF.parm7'
>
>     traj = pt.iterload(fn, tn)
>     assert traj.metadata['has_force']
>     print(traj[0].force)
>
>     fn2 = 'test.nc'
>     traj.save(fn2, overwrite=True, options='force') # no velocity
>
>     traj2 = pt.iterload(fn2, traj.top)
>     assert traj2.metadata['has_force']
>     print(traj2[0].force) # got None
>
> test_write_force_and_velocity()
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/362>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJrJt0Kw_BzTZUXaPRkmXu2CobPCmC0hks5qOZdCgaJpZM4I8LD9>
> .
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
Remove force does not resolve the issue. Originally the test wanted to write force to disk. And the output trajectory does not have force.

**Comment by drroe** [comment]
>  And the output trajectory does not have force.

If the input trajectory has force, the output trajectory should have force. This is the current behavior with cpptraj (you can see that all I did to the `systemVF.nc` related test is remove `force`. Could this be a pytraj issue?

**Comment by hainm** [comment]
I need to check pytraj code again.

But do you intend to change that behavior? What if I dont want to write force?

**Comment by drroe** [comment]
> But do you intend to change that behavior? What if I dont want to write force?

Then you would have to use some combo of the new `mdcrd` and `mdvel` keywords; one or the other for either, both for both, etc.

**Comment by hainm** [comment]
I am confused. For example, if `traj.nc` has force value and I don't want to write `force` to output traj. What's correct cpptraj's input?

```bash
parm my.parm7
trajin traj.nc # has force
trajout out.nc # don't want to have force
```

**Comment by drroe** [comment]
The guiding principle of cpptraj is "don't modify things unless the user specifies it". That is why for example the `strip` command does not remove box information when all solvent is gone unless you tell it to. Old versions of cpptraj violated this principle by requiring the `force` and `velocity` keywords to include forces and velocities respectively in NetCDF output trajectories, even if that information was already present. In other words, cpptraj was by default stripping this information from trajectories, which is not desirable in my opinion.

The new `mdfrc`, `mdvel`, and `mdcrd` keywords for NetCDF, as well as the new `noX` keywords (`novelocity`, `noforce`, etc) allow users more control over how trajectories are output. So to answer your question, if you want to only write *only* coordinates to the NetCDF trajectory even when forces are present, you can use the `mdcrd` keyword:
```
trajin CrdFrc.nc
trajout CrdOnly.nc mdcrd
```
Make sense?

**Comment by hainm** [comment]
I agree with `"don't modify things unless the user specifies it"`

> The new mdfrc, mdvel, and mdcrd keywords for NetCDF

What's about other formats?

**Comment by drroe** [comment]
> What's about other formats?

This is only for NetCDF files for now.
