### ISSUE TITLE
no header "Cpptraj generated ..." for trr and xtc?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#373]
one of pytraj tests failed since the test expected

`expected_line = 'Cpptraj generated TRR file` for trr format.

**Comment by drroe** [comment]
The default title for TRR is "`GMX_trn_file`" because otherwise Gromacs analysis tools will not process the generated TRR trajectories (see https://github.com/Amber-MD/cpptraj/commit/41bd1e484ca69c02798ef3708ffdbe6791837d00). 

I don't think the XTC files format stores a title.

**Comment by hainm** [comment]
thanks. I just updated `pytraj` test https://github.com/Amber-MD/pytraj/pull/1285
