### ISSUE TITLE
change log

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#38]
I am not sure if you have a private log about new feature or changes or not. I think it's good idea to push it (if you have one) or create new one to `cpptraj` repo. It's easier to keep track.

This is example from `cython` project.
https://github.com/cython/cython/blob/master/CHANGES.rst

And it's easier to gather doc for new Ambertools release.

Tagging @swails  and @pengfeili1 here for your packages too.

**Comment by hainm** [comment]
example from `scipy` project: https://github.com/scipy/scipy/tree/master/doc/release

**Comment by drroe** [comment]
This is effectively what the wiki is now.

https://github.com/Amber-MD/cpptraj/wiki
