### ISSUE TITLE
add coordinates x|y|z value to Dataset for density?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#383]
I can not get those value from CpptrajState.DatasetList

cpptraj output

```bash
#Z                :PC@P31  sd(:PC@P31)      :PC@N31  sd(:PC@N31) 
    -24.1250       0.0000       0.0000       0.0000       0.0000 
```

**Comment by drroe** [comment]
> I can not get those value from CpptrajState.DatasetList

You're not supposed to. To save memory, this data is not stored for monotonic data sets (`DataSet_double`, `DataSet_integer`, etc). You're supposed to call 
```C++
DataSet::Coord(unsigned int d, size_t p)
```
to get the coordinate value for data point `p` in dimension `d`.

**Comment by hainm** [comment]
uhm, I recall that I did that for lowestcurve before too. thanks.
