### ISSUE TITLE
makestructure: custom1, custom2?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#414]
Hi,

I am very confused about `custom1`, `custom2`, ... keywords in `makestructure`.
Is this an arbitrary name or a command? 

Example from manual

```bash
Make residues 1 and 12 ’extended’, residues 6 and 7 a type I’ turn, 
and two custom assignments, one  (custom1)
for residues 2-5, the other (custom2) for residues 8-11:

makestructure extended:1,12 \
custom1:2-5:-80.0:130.0:-130.0:140.0 \
typeI’:6-7 \
custom2:8-11:-140.0:170.0:-100.0:140.0
```

In below case, can I replace `customdih` by `customhellothere`?

```bash
makestructure customdih:5:phi:90 custom:6,7:-70:60
```

**Comment by drroe** [comment]
This is an example of me trying to be clever, with mixed results. The short answer is yes, you can replace `custom1` with any name. The idea was that if you wanted to apply that same custom assignment to another set of residues you wouldn't have to type the dihedral angles again, e.g.
```
makestructure extended:1,12 \
                        custom1:2-5:-80.0:130.0:-130.0:140.0 \
                        typeI’:6-7 \
                        custom1:8-11
```
Would apply `custom1` to residues 2-5 _and_ 8-11, without having to enter the whole entry a second time.

**Comment by hainm** [comment]
I think manual should be updated about that. I played with `makestructure` a while and find it very useful.

**Comment by drroe** [comment]
Done via Amber GIT commit eb7901b326c6a9f03f6e7437fc9a17a1325f09a3
