### ISSUE TITLE
Add a remap command

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#415]
Essentially a manual version of atommap.

**Comment by hainm** [comment]
does this relate to 

> [AMBER] Mapping back the original PDB numbering and chain IDs when analysing Amber trajectories

**Comment by drroe** [comment]
@hainm not directly, since I think what that user really needed was the preservation of PDB info. However, it could be related if the ordering in the PDB is different from the Amber residue templates (I don't think they are but I could be wrong).

This is really something that cpptraj has been able to do "under the hood" for a long time (among other things it's actually the mechanism that underlies `strip`) but I hadn't gotten around to exposing the functionality as an action. The user's email reminded me.

**Comment by drroe** [comment]
Addressed by #416.
