### ISSUE TITLE
cluster output: repout: inconsistent name? (e.g: x.pdb.c0.pdb)

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#418]
hi,

if I uses `repoup x.pdb`, I  got
`x.pdb.c0.pdb`

if using `repout x`, I got
`x.c0.crd, ...`

Seems to me that `x.pdb.c0.pdb` should be `x.c0.pdb`

**Comment by drroe** [comment]
From the help syntax:
```
[ repout <repprefix> [repfmt <repfmt>]
```
So what you specify to `repout` is a prefix, not the full file name. What is happening is that because you don't specify `repfmt`, cpptraj tries to guess what you want. But it is still a prefix so cpptraj includes the whole thing. Does that make sense?

**Comment by hainm** [comment]
yeah. thanks.
