### ISSUE TITLE
Easier methods to allocate force and velocity?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#426]
Can you add methods to allocate force/velocity based on natom (and do nothing else)?

Basically I have an existing frame and just want to add velocity/force

frame.velocity = vel_array

SetupFrameV does not serve my need in this case (overkill + need vector of atoms (if remember correctly))

Thanks

**Comment by drroe** [comment]
Would a constructor or function that takes an `int` and `CoordinateInfo` work?

**Comment by hainm** [comment]
Probably work.

for example, if user constructed a trajectory `traj` with only topology and coordinates.
Then later user decides to get vel from another source as 3D array.

```bash
traj.velocity = vel_3d_array
# --> will update traj's crdinfo (has_velocity=True)
# so if iterating traj
for frame in traj:
    # pytraj will construct
    # frame = Frame(n_atoms=30, crdinfo={'has_velocity': True})
    do_something(frame)
```

but this is troubled case
```
# take 1st frame with no vel/force info
frame = traj[0]

# user decide to add vel/force
frame.velocity = vel_2darray
--> How we deal with this case?
```

**Comment by drroe** [comment]
My proposed functions:
```C++
Frame(int natom, CoordinateInfo const& cinfoIn);
int SetupFrameV(int natom, CoordinateInfo const& cInfoIn);
```
Only thing to keep in mind is that all masses will be set to 1.0. Do you need an option to pass in mass info as well?

**Comment by hainm** [comment]
I am thinking about an API like below

```python
trajout = pt.TrajectoryWriter(...)
for frame in traj:
    frame.velocity = vel_2darray
    trajout.write(frame, velocity=True)
```

**Comment by hainm** [comment]
>  Do you need an option to pass in mass info as well?

it would be great if I can set mass from an array rather than a vector of Atoms.
pytraj does dirty hack if need setting mass:
```python
    def _set_mass_from_array(self, double[:] arr):
        '''mostly for pickling
        '''
        cdef Atom atom
        cdef vector[_Atom] va
        cdef unsigned int i

        for i in range(arr.shape[0]):
            # just try to create dummy atom (name, type, charge, mass)
            atom = Atom(name='X', type='X', charge=0.0, mass=arr[i])
            va.push_back(atom.thisptr[0])
        self.thisptr.SetMass(va)
```

**Comment by hainm** [comment]
by the way, it that does not cost much of your time, we can try and let's see.

**Comment by drroe** [comment]
How about something like:
```C++
int AddVelocities(std::vector<double> const&);
void RemoveVelocities();
```
and so on for mass/forces?

**Comment by hainm** [comment]
... which will be great. ^^

**Comment by drroe** [comment]
Let me know if #428 adequately addresses this.

**Comment by hainm** [comment]
Yes thanks
