### ISSUE TITLE
upload cpptraj pdf - devguide

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#43]
Dan,

can you render and upload pdf version of devguide so I can link from pytraj.
http://amber-md.github.io/pytraj/doc/build/html/developer_guide.html#read-also

thanks

**Comment by drroe** [comment]
Check out the update-devguide branch on my fork (https://github.com/drroe/cpptraj.git), I've made a few improvements. I'd appreciate any comments you have before I merge.

**Comment by hainm** [comment]
thanks. I will read it.

**Comment by hainm** [comment]
@drroe 

i think your doc will help a log for new dev.

Can you also try to finish doc for Traj_... and DataSet_..TRJ? pytraj is using DataSet..TRJ for its backend since this class can load multiple file with smart indexing (better than Trajin_Single IMO). Those are important classes.

**Comment by hainm** [comment]
Sorry for many typos, hard to update by phone.

**Comment by hainm** [comment]
And may be write more about the design/feature you think cool too (you mentioned some in our emails).

**Comment by swails** [comment]
> Can you also try to finish doc for Traj_... and DataSet_..TRJ? pytraj is using DataSet..TRJ for its backend since this class can load multiple file with smart indexing (better than Trajin_Single IMO). Those are important classes.

I'll go ahead and speak for Dan here (he can correct me if I'm wrong) -- but you are more than welcome to modify this document as well.  Dan can pretty easily correct stuff that is wrong, and you have a better idea of what would be helpful to new developers than Dan.  Dan has never been a "new developer" for cpptraj -- he's always known the entire code base, object model, design principles, etc.

These suggestions are good, but they're even better in the form of a PR ;).

**Comment by hainm** [comment]
Yeah. I though about this but my English is really suck recently. So many typos + grammar. :))

**Comment by hainm** [comment]
Writing code is so much easier

**Comment by drroe** [comment]
Closed via #53
