### ISSUE TITLE
configure wishlist: add -wine options for testing *.exe linking 

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#438]
This is good for cross compiling. 
Which is similar to AMBER configure.

**Comment by drroe** [comment]
NOTE: Amber `configure -wine` ensures that `wine` is used to execute binaries.

**Comment by hainm** [comment]
yeah, this is what I meant. 

I created a docker image here so everything is ready there.

https://github.com/hainm/amber-win-cross/blob/master/Dockerfile

**Comment by hainm** [comment]
Close. Should let user install Ubuntu natively on Windows. https://msdn.microsoft.com/en-us/commandline/wsl/about
