### ISSUE TITLE
 implement new Frame constructor 

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#44]
from closed PR: #22

**Comment by drroe** [comment]
Is there any need to include velocity info?

**Comment by hainm** [comment]
@drroe I think only coords + mass is good. Currently pytraj does not use any vel info.

**Comment by swails** [comment]
But it can often be useful to have access to that information when available, even if the user does all of their own analysis.  (The `NetCDFTraj` class in ParmEd exposes both the velocities *and* the forces in addition to the coordinates for precisely this reason, even though it doesn't *use* that data for anything).

**Comment by hainm** [comment]
I agree. 

The only thing I concern is memory. Does including all the vel + force make the Frame too fat (given that Frame use double precision)? (so pytraj is consuming double memory compared to mdtraj or mdanalysis). But this might not be problem since pytraj focuses more on out-of-core calculation like cpptraj.

**Comment by drroe** [comment]
To simplify things at first I will only make a constructor for coords. If all goes well, then I can worry about adding velocity info.

**Comment by swails** [comment]
> The only thing I concern is memory. Does including all the vel + force make the Frame too fat (given that Frame use double precision)? (so pytraj is consuming double memory compared to mdtraj or mdanalysis). But this might not be problem since pytraj focuses more on out-of-core calculation like cpptraj.

Why can't you just make the velocity array `NULL` if it's not available so that memory is only consumed for velocities when they're available?

**Comment by hainm** [comment]
yeah, right.

**Comment by drroe** [comment]
> Why can't you just make the velocity array NULL if it's not available so that memory is only consumed for velocities when they're available?

This is currently what cpptraj does. The difficulty with having external velocities right now is that due to the way velocity allocation happens (in fact *because* it doesn't always happen) there are more spots I have to modify to ensure conversions between external and non-external memory frames happen correctly. I just want to make sure the simple case of external coordinates works before working on that.

@hainm Try the branch called frame_externalData in my fork, drroe/cpptraj.

**Comment by hainm** [comment]
thanks. I will.

**Comment by hainm** [comment]
@drroe so for those actions that change coords of Frame, like rmsd, translate, ... cpptraj does in-place (without changing mem address), right?

**Comment by drroe** [comment]
Yes. The only time memory is changed is in the SetupFrameX routines and if the Frame size is modified (AddXYZ, AddVec3).

**Comment by hainm** [comment]
ok I see. So rule of thumb here is: no worry about those stuff, as long as I don't change Frame's size.

**Comment by drroe** [comment]
Yeah. The only thing that might be annoying about this is the RMS routines
dont take atom masks (for performance reasons). If necessary i can make one
that will take an atom mask or masks.

On Monday, August 17, 2015, Hai Nguyen <notifications@github.com> wrote:

> ok I see. So rule of thumb here is: no worry about those stuff, as long as
> I don't change Frame's size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/44#issuecomment-131978317>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
@drroe I am testing your branch with pytraj and seems fine to me. I will go ahead redesign pytraj's in-memory Trajectory with your new change. I will play with it for a while and let you know if we can merge to master (for both cpptraj and pytraj). thanks.

**Comment by drroe** [comment]
@hainm Development on this has gotten a little out-of-sync now that there are multiple branches floating around. I'd like to finish this up somehow. We have a few options:

1) I implement mass and coordinate setting in my frame_externalData branch, get rid of the Amber-MD/cpptraj frame_externalData branch, and create a PR.
2) You update the Amber-MD/cpptraj frame_externalData branch with what you've done and create a PR.

Based on the few benchmarks I've ran there doesn't appear to be a performance hit (as expected). How would you like to proceed?

**Comment by hainm** [comment]
@drroe 

let's follow `#1`.

**Comment by drroe** [comment]
OK - so to be clear:
1) Frame::Frame(int,double*) needs to set up mass as well.
2) Add a routine (something like SetXptr(double*)) which will change Frame::X_ when memIsExternal_ is true.
Anything I'm missing?

**Comment by hainm** [comment]
> 1) Frame::Frame(int,double) needs to set up mass as well.

Yes

> 2) Add a routine (something like SetXptr(double)) which will change Frame::X_ when memIsExternal_ is true.

Yes. I want to use Frame as a pointer

3)  We need to add `SetMass` too. There is a SetupX routine for mass but requiring allocate X_. 
In pytraj, Frame's mass is on-the-fly updated for Action that needs this. (given that updating mass is cheap).

**Comment by hainm** [comment]
when you finish this stuff and merge to master branch, I will update pytraj master too.

**Comment by drroe** [comment]
What should SetMass() take as an argument? Same as the constructor (int, double*). Something else? Let me know if you want to chat directly about this via gchat etc.

**Comment by hainm** [comment]
yes. let's move to my gchat (typing only since I am in lab and don't have mic).

**Comment by drroe** [comment]
Closed via #56
