### ISSUE TITLE
cpptraj in AmberTools: how to NOT to link to libsander

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#445]
compiling sander and libsander in windows is quite tricky. So it would be great to have option to not link to libsander in configure2; or an env variable.

Why? Sometimes user only need a subset of AmberTools (e.g: force field related (sqm, tleap, ParmEd, ..._) + a program like cpptraj for analyzing some trajectories).  We are experimenting that (added "ambermini" options in `AmberTools/src/Makefile` ).

**Comment by drroe** [comment]
> So it would be great to have option to not link to libsander in configure2; or an env variable.

OK. This probably isn't the best place for this feature request though since configure2 doesn't live here. Maybe better to put it on the Amber bug tracker?

**Comment by drroe** [comment]
Addressed by adding `-nosanderlib` flag to Amber configure (Amber GIT ae475dc856ba12260cdd77187013325b3dde981f).
