### ISSUE TITLE
What is the current status on SPAM?

### ISSUE THREAD

**Issue by 1860** [Amber-MD/cpptraj#464]
Hello cpptraj,

I have a question concerning SPAM and how to run it... I have run the md simulation of hewl-nag (pdb 2LYO) as described in "SPAM: a simple approach for profiling bound water molecules". 

Using this local version of cpptraj and not the one included in Amber, I have run  `volmap waters 0.5 0.5 0.5 :SOL peakcut 0.05 peakfile peaks.xyz` and got 14 peaks as output - are these my 14 hydration sites? I am surprised because in the publication you state to find 388. Which could be the reason for this large difference?

Then I ran `spam peaks.xyz solv SOL reorder name hewl_spam info spam_info.out summary spam_sum.out out spam.out`. 

I get two warnings:
Warning: 'dgbulk' not specified; using default for SPC/E water.
Warning: 'dhbulk' not specified; using default for SPC/E water.
Since I was using SPC/E water this should not be a problem. However, I would like to indicate dgbulk and dhbulk. Could you please tell me the correct way to do this?

Also I am confused on what I have to do next? Is it still necessary to run SPAM.py?
I see that in peaks.xyz I have coordinates and in spam_sum.out i have [DG]. In order to get the free energies of the hydration sites, could I just get the coordinates from peaks.xyz and the free energy from spam_sum.out and "merge" them together in one pdb file? Or would this be completely wrong?

Thank you very much

**Comment by drroe** [comment]
SPAM functionality was recently fully implemented within CPPTRAJ: see PR #429. 

> got 14 peaks as output - are these my 14 hydration sites? I am surprised because in the publication you state to find 388. Which could be the reason for this large difference?

You have a different system, so you will get different results. How many peaks you will get depends on what your solute is, how long you run, what your cutoff is, etc. I recommend just viewing the density output from `volmap` to get an idea what the average behavior of water is before you decide on cutoffs etc.

> However, I would like to indicate dgbulk and dhbulk. Could you please tell me the correct way to do this?

If you run `help spam` within an interactive CPPTRAJ session, you will get the full syntax for the command. The keywords you want are listed there:
```
> help spam
	<filename> [solv <solvname>] [reorder] [name <name>]
	[purewater] [cut <cut>] [info <infofile>] [summary <summary>]
	[site_size <size>] [sphere] [out <datafile>]
	[dgbulk <dgbulk>] [dhbulk <dhbulk>] [temperature <T>]
    <filename> : File with the peak locations present (XYZ- format)
    <solvname> : Name of the solvent residues
    <cut>      : Non-bonded cutoff for energy evaluation
    <dgbulk>   : SPAM free energy of the bulk solvent in kcal/mol
    <dhbulk>   : SPAM enthalpy of the bulk solvent in kcal/mol
    <T>        : Temperature at which SPAM calculation was run.
    <infofile> : File with stats about which sites are occupied when.
    <size>     : Size of the water site around each density peak.
    [sphere]   : Treat each site like a sphere.
    [purewater]: The system is pure water---used to parametrize the bulk values.
    [reorder]  : The solvent should be re-ordered so the same solvent molecule
                 is always in the same site.
    <summary>  : File with the summary of all SPAM results. If not specified,
                 no SPAM energies will be calculated.
    <datafile> : Data file with all SPAM energies for each snapshot.
```

> Also I am confused on what I have to do next? Is it still necessary to run SPAM.py?

No - you can get that output from the `summary` keyword.

> could I just get the coordinates from peaks.xyz and the free energy from spam_sum.out and "merge" them together in one pdb file? Or would this be completely wrong?

I'm not sure I understand your question completely. The peaks file contains the peak locations. The `summary` file contains the free energy/enthalpy/entropy terms. The numbering in the summary file matches the order in the peaks file, e.g. the first peak is 1 in summary, etc. See `$CPPTRAJHOME/test/Test_SPAM` for a simple example calc.

@swails, any additonal comments?

**Comment by swails** [comment]
> @swails, any additonal comments?

Sorry, just saw this.  No additional comments -- your analysis seems complete to me.

**Comment by 1860** [comment]
Great work!!! Thank you very much for implementing Spam into cpptraj!!!

One more question: Have you calculated dgbulk and dhbulk for tip3p using amber16?

**Comment by drroe** [comment]
> One more question: Have you calculated dgbulk and dhbulk for tip3p using amber16?

I haven't, but it should be relatively straightforward with the `purewater` keyword. The `spam` action is both OpenMP and MPI parallelized, so you can use cpptraj.OMP, cpptraj.MPI, or cpptraj.OMP.MPI to speed things up.

**Comment by 1860** [comment]
I am now simulating a box of tip3p water with amber14ff forcefield and will then post the values for dgbulk and dhbulk here.

**Comment by 1860** [comment]
Could you please explain me how to run spam with `purewater`? I would still need a peaks.xyz file to run spam? How can I have peaks in bulkwater? Correspondingly my peaks.xyz file is empty after volmap even if I put the density cut-off to 0.

**Comment by swails** [comment]
You run `purewater` on the raw water trajectory -- no peaks file.  It loops over every water molecule in the box and computes the SPAM energy for each (so it doesn't take a very long simulation *at equilibrium* to converge the results).

**Comment by drroe** [comment]
Something like:
```
parm spcbox.parm7
trajin spcbox.nc
spam purewater name SPAM cut 12.0 out spampure.dat
avg SPAM out spam.avg.dat name AVG
```
Or just take the average of the values in `spampure.dat` manually.

**Comment by 1860** [comment]
I am using your commands but I don't get any output!

I have uploaded my files [here](https://www.dropbox.com/sh/z6abmppy1yboz8j/AAAcQ8cmJ2pKSfW-SmTl-c6Za?dl=0) in case you want to give it a try...

PS: I ran the simulation in gromacs and then converted it to amber topology and trajectory

**Comment by drroe** [comment]
If you are running interactively you need to type `run` or `go` to actually execute a trajectory analysis run.

**Comment by drroe** [comment]
Also, you shouldn't need to convert - cpptraj reads most gromacs files.

**Comment by 1860** [comment]
Spam gives me following output on the screen:
`SPAM bulk energy values:`
`<G>= -28.4597, <H>= -17.7415 +/- 5.08996, -TdS= -10.7182`
Does this mean `dgbulk=-28.4597` and `dhbulk=-17.7415` ?
What about the standard deviation in `<H>`? Isn't it too large?

Also I have calculated avg as drroe suggested which is basically the same:
`#Set       AVG[avg]    AVG[sd]  AVG[ymin]  AVG[ymax] AVG[yminidx] AVG[ymaxidx] AVG[names]`
`       1     -17.74       5.09     -37.31      10.45     18228696     12804100     "SPAM"`

**Comment by swails** [comment]
No, that standard deviation is not too large. What makes you think it is?

**Comment by 1860** [comment]
I would have thought it's a bit high... But if you say it is fine, then I'll leave it like this.

For anybody reading this post in the future:
For the amber14 force field and tip3p water model, I have found the parameters:

dgbulk=-28.4597
dhbulk=-17.7415
