### ISSUE TITLE
libsander is not ever tested on travis

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#476]
FYI

```bash
TEST: /home/travis/build/Amber-MD/cpptraj/test/Test_Esander
SANDER energy tests requires compilation with the Sander API from AmberTools.
```

Reason: no `AMBERHOME` is set. :D 
```bash
Checking availability of the SANDER API from AmberTools
Warning: Compilation with the SANDER API requires AMBERHOME to be set
         if '--with-sanderlib' not specified.
```

**Comment by swails** [comment]
I thought it used to be?

In any case, I think it's tested on Jenkins... :)

**Comment by hainm** [comment]
I see. (@drroe spent lots of time fixing error in downloading `pysander` https://github.com/Amber-MD/cpptraj/pull/475#issuecomment-289116217)

**Comment by drroe** [comment]
If it's tested on Jenkins I have no interest in getting it tested on Travis.

**Comment by hainm** [comment]
For both linux and osx?

**Comment by swails** [comment]
Travis doesn't do Mac OS anymore.

**Comment by hainm** [comment]
I though you machine only do macos. We still need testing for linux libsander.

Hai Nguyen

**Comment by swails** [comment]
You can check the Jenkins build status. It also runs on Linux with the Intel compilers. 

It runs 6 builds on Jenkins. 4 are on Linux, and each links libsander

**Comment by swails** [comment]
www.jasonswails.com:8888/job/cpptraj/48/

**Comment by hainm** [comment]
oh cool. thanks.

**Comment by hainm** [comment]
just check

```bash
Triggering cpptraj » -mpi,macos [1]
Triggering cpptraj » -nosanderlib,macos
Triggering cpptraj » -nosanderlib,linux
Triggering cpptraj » -cuda,linux
Triggering cpptraj » -mpi,linux [2]
Triggering cpptraj » -openmp,linux [3]
```

--> So can I assume [1, 2, 3] are built with `libsander`? :D

**Comment by hainm** [comment]
never mind, I just check its build log and does see energy testing there. cool.
