### ISSUE TITLE
new Frame constructor: wrong rmsd result for ActionList`

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#49]
Dan,

I am using ActionList to calculate rmsd for a series of masks. It works fine (got I expected) with immutable TrajecotryIterator but I got 0.0 results if using mutable Trajectory (numpy). Any idea why?

Note that if I am using Action_Rmsd directly, the result is correct.

Here is my python code

This give correct results for both mutable and immutable Trajectory. 
```python
        def test_rmsd(input_traj):
            from pytraj.actions.CpptrajActions import Action_Rmsd
            from pytraj.datasets import DataSetList
            dslist = DataSetList()
            act = Action_Rmsd()
            act.read_input('first @CA', top=input_traj.top, dslist=dslist)
            act.process(input_traj.top)

            for frame in input_traj:
                act.do_action(frame)
            print(dslist.values)
```

This give correct results for **immutable** Trajectory but wrong result for **mutable** Trajectory
```python
        def test_rmsd_actlist(input_traj):
            from pytraj.actions.CpptrajActions import Action_Rmsd
            from pytraj.core.ActionList import ActionList
            from pytraj.datasets import DataSetList

            alist = ActionList()
            dslist = DataSetList()
            act = Action_Rmsd()
            alist.add_action(act, 'first @CA', top=input_traj.top, dslist=dslist)

            for frame in input_traj:
                alist.do_actions(frame)
            print(dslist.values)
```

**Comment by hainm** [comment]
so I think ActionList in cpptraj deallocate/allocate mem a bit different. But this might be due to `pytraj` part. Just want to ask you about internal cpptraj first.

**Comment by drroe** [comment]
If you're using ActionList you need to call SetupActions with the address
of the current Topology before actually doing actions so that the Action's
Setup() routine is called.

On Tue, Aug 18, 2015 at 12:28 PM, Hai Nguyen <notifications@github.com>
wrote:

> so I think ActionList in cpptraj deallocate/allocate mem a bit different.
> But this might be due to pytraj part. Just want to ask you about internal
> cpptraj first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/49#issuecomment-132308719>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
I think I already did that. https://github.com/hainm/pytraj/blob/Frame_pt_constructor/pytraj/core/ActionList.pyx#L73-L93

Please note that
* I am testing your new branch `frame_externalData`
* I change Trajectory api with new Frame constructor (n_atoms, double* ptr)
* I got expected result with our official pytraj + cpptraj with ActionList

**Comment by hainm** [comment]
might be because of below?

```python
bool ActionList::DoActions(Frame **FrameAddress, int frameNumIn)
```
https://github.com/drroe/cpptraj/blob/master/src/ActionList.cpp#L94

vs
```python
Action::RetType Action_Rmsd::DoAction(int frameNum, Frame* currentFrame, Frame** frameAddress)
```
https://github.com/Amber-MD/cpptraj/blob/master/src/Action_Rmsd.cpp#L306

**Comment by drroe** [comment]
Yeah probably - DoActions requires the address of a frame, not the frame
itself (in case frame is modified by action as in the case of e.g. strip).

On Tue, Aug 18, 2015 at 12:44 PM, Hai Nguyen <notifications@github.com>
wrote:

> might be because of below?
>
> bool ActionList::DoActions(Frame **FrameAddress, int frameNumIn)
>
> https://github.com/drroe/cpptraj/blob/master/src/ActionList.cpp#L94
>
> vs
>
> Action::RetType Action_Rmsd::DoAction(int frameNum, Frame* currentFrame, Frame** frameAddress)
>
> https://github.com/Amber-MD/cpptraj/blob/master/src/Action_Rmsd.cpp#L306
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/49#issuecomment-132314538>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
or may be `SetupFrameM` that pytraj using to set mass for Frame.

(pytraj code: https://github.com/Amber-MD/pytraj/blob/master/pytraj/Frame.pyx#L649-L650)

correct (from immutable traj)
```python
In [7]: traj
Out[7]:
<pytraj.TrajectoryIterator with 10 frames: 
<Topology with 5293 atoms, 1704 residues, 1692 mols, 5300 bonds, PBC with box type = ortho>>


In [8]: f0 = traj[0]

In [9]: f0.xyz[0]
Out[9]: array([ 15.55458927,  28.54844856,  17.18908691])

In [10]: f0.set_frame_mass(traj.top)
Out[10]: 0

In [11]: f0.xyz[0]
Out[11]: array([ 15.55458927,  28.54844856,  17.18908691])
```

**incorrect** (frame coords was set to 0.0 after setting mass)
```python
In [13]: t0
Out[13]:
<pytraj.Trajectory with 10 frames: 
<Topology with 5293 atoms, 1704 residues, 1692 mols, 5300 bonds, PBC with box type = ortho>>


In [14]: f0 = t0[0]

In [15]: f0.xyz[0]
Out[15]: array([ 15.55458927,  28.54844856,  17.18908691])

In [16]: f0.set_frame_mass(traj.top)
Out[16]: 0

In [17]: f0.xyz[0]
Out[17]: array([  1.15927142e-312,   1.15927142e-312,   2.34938467e-315])
```

**Comment by drroe** [comment]
Is this issue still a problem?

**Comment by hainm** [comment]
work great now. closed.
