### ISSUE TITLE
add SetMass

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#50]
Dan,

can you review my proposal here? (forked from frame_externalData branch)
https://github.com/hainm/cpptraj/commit/34089f4586911399d2e17dbe571eb7e7271d10ee
hainm@c74b221
it fixes this issue https://github.com/Amber-MD/cpptraj/issues/49

Feel free to rewrite it as you like.

**Comment by hainm** [comment]
uhm, add `Mass_(natom, 1.0),` cause memory leaked in pytraj. :((

C++ is so hard.

**Comment by hainm** [comment]
I just fixed mem leaked in pytraj at cython level. It's still good to review my PR. May be we can discuss about assign mass for Frame.

**Comment by hainm** [comment]
just add `SetXptr` to speed up pytraj iterating

cpptraj PR: https://github.com/hainm/cpptraj/commit/c74b221e49182b5623dc4fcca01d58036a69dd70

with new implementation in cpptraj, pytraj was able to iterate as fast as numpy. And probably as fast as iterating the raw pointer.

pytraj's benefit: 
https://github.com/hainm/pytraj/blob/ff3fa0debb1524299c06d74b730b271e35fecc71/pytraj/_fast_iter.pyx#L21-L36

**Comment by hainm** [comment]
This is timing to iterate 1000 frames with ~17K atoms

(in second)
raw numpy array: 0.00032
old iterating: 0.06929
new PR for cpptraj: 0.000345 (as fast as iterating numpy array)

**Comment by drroe** [comment]
Nice! Sorry for delay on this Hai, i'll get to it first thing tomorrow.

On Wednesday, August 19, 2015, Hai Nguyen <notifications@github.com> wrote:

> This is timing to iterate 1000 frames with ~17K atoms
>
> (in second)
> raw numpy array: 0.00032
> old iterating: 0.06929
> new PR for cpptraj: 0.000345 (as fast as iterating numpy array)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/50#issuecomment-132888449>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
close via https://github.com/Amber-MD/cpptraj/pull/56
