### ISSUE TITLE
Installation error with MACos

### ISSUE THREAD

**Issue by taushifkhan** [Amber-MD/cpptraj#509]
I have tried installing with pip and source code, but could not (install properly). I am using Mac OS (Sierra 10.12.5). While importing pytraj is saying following error,

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/usr/local/lib/python3.6/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/usr/local/lib/python3.6/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so, 2): Library not loaded: @rpath/python3.6/site-packages/pytraj/lib/libcpptraj.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so
  Reason: image not found

**Comment by drroe** [comment]
I'm going to ping @hainm since this seems to be a [pytraj](https://github.com/Amber-MD/pytraj) issue (although it is possible that it is somehow a problem with cpptraj).

As a first start, it would probably help to debug if you specify every step (i.e. command) you have used to try and install/run pytraj so far.

**Comment by hainm** [comment]
@taushifkhan  I am not sure what is going on here.

it works fine with my computer (10.12.5). May be because I am using Python from Miniconda distribution?

```bash
$ pip install pytraj --no-cache-dir
Collecting pytraj
  Downloading pytraj-2.0.0-cp36-cp36m-macosx_10_7_x86_64.whl (5.9MB)
    100% |████████████████████████████████| 5.9MB 9.9MB/s 
Installing collected packages: pytraj
Successfully installed pytraj-2.0.0
(py36) haichit@haimac ~ $ python -c "import pytraj; print(pytraj.__version__)"
2.0.0
```

Can you try?

```bash
otool -L /usr/local/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so
```

The output from my try is
```bash
$ otool -L miniconda3/envs/py36/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so
miniconda3/envs/py36/lib/python3.6/site-packages/pytraj/core/topology_objects.cpython-36m-darwin.so:
	@rpath/python3.6/site-packages/pytraj/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by hainm** [comment]
May be trying install pytraj from master branch.

```
# IMPORTANT: uninstall first
rm -rf /usr/local/lib/python3.6/site-packages/pytraj*

git clone https://github.com/Amber-MD/pytraj
cd pytraj

# linux
python setup.py install
```

**Comment by taushifkhan** [comment]
I have used 
1. pip3 install pytraj [it says paytraj in installed but its runs very quickly like 15 sec; but while I tried to import , mentioned error occurred]

2. I cloned pytraj from git and used python3 setup.py install
again it says it installs but could not import.
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by taushifkhan** [comment]
here are the results

(pyMd) taushif@taushifs-MBP:mDAnalysis$ pip install pytraj --no-cache-dir
Collecting pytraj
  Downloading pytraj-2.0.0-cp27-cp27m-macosx_10_7_x86_64.whl (5.7MB)
    100% |################################| 5.8MB 8.3MB/s 
Installing collected packages: pytraj
Successfully installed pytraj-2.0.0


(pyMd) taushif@taushifs-MBP:mDAnalysis$ python -c "import pytraj; print(pytraj.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/__init__.py", line 23, in <module>
    from .utils.misc import info
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: dlopen(/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/core/topology_objects.so, 2): Library not loaded: @rpath/python2.7/site-packages/pytraj/lib/libcpptraj.dylib
  Referenced from: /Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/core/topology_objects.so
  Reason: image not found

(pyMd) taushif@taushifs-MBP:mDAnalysis$ otool -L /Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytra
j/core/topology_objects.so
/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/python2.7/site-packages/pytraj/core/topology_objects.so:
	@rpath/python2.7/site-packages/pytraj/lib/libcpptraj.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
—
Regards,

Taushif Khan
Ph.D.
Post-Doctoral Research,
Inter university Institute of Bioinformatics in Brussels (IB-Square),
Brussels, Belgium

**Comment by hainm** [comment]
Per install from source code, you need to change folder from pytraj root
folder. Otherwise python will try to import pytraj from source folder.

Hai

**Comment by hainm** [comment]
Uhm, I think this is the limitation of current pytraj builder. It assumes
that your

/Users/taushif/Taushif_Ib2/mDAnalysis/pyMd/lib/

is the loader_path to search for
 @rpath/python2.7/site-packages/pytraj/lib/libcpptraj.lib

I guess I have never countered this issue since I always use python
miniconda, which takes care of those issues.

FWIW, you might have want to install python from Miniconda too. This
distribution is better for python scientific computing. (E.g handle binary
distribution better)

https://conda.io/miniconda.html

Hai

**Comment by drroe** [comment]
Since this is primarily a pytraj issue I'm closing this. Feel free to reopen under the pytraj repo if you're still having issues.
