### ISSUE TITLE
create frame_externalData branch in amber-md repo

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#52]
Dan,

can you make this frame_externalData branch available in amber-md repo. I can not fork from your personal branch.

And it's easier to discuss when I or you submit new changes.

**Comment by drroe** [comment]
This has been pushed to Amber-MD/cpptraj. Sorry for the delay - wanted to
make sure I did it correctly.

On Wed, Aug 19, 2015 at 4:36 PM, Hai Nguyen <notifications@github.com>
wrote:

> Dan,
>
> can you make this frame_externalData branch available in amber-md repo. I
> can not fork from your personal branch.
>
> And it's easier to discuss when I or you submit new changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/52>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
@hainm -- in the future this is actually fairly easy to do without publishing another branch.  Create an alias to Dan's fork in your local repository:

```
git remote add drroe git@github.com:/drroe/cpptraj.git
```

Then fetch the information from his remote:

```
git fetch drroe
```

Then checkout whatever branch you want from Dan's repo:

```
git checkout frame_externalData
```

Or if that doesn't work (because your git is too old):

```
git checkout -b frame_externalData drroe/frame_externalData
```

**Comment by hainm** [comment]
Great. Thanks.
