### ISSUE TITLE
Replace appveyor?

### ISSUE THREAD

**Issue by swails** [Amber-MD/cpptraj#541]
I added a Windows slave to my Jenkins array (it's really just a VM running on the master Linux machine).

@drroe - I can give you VNC access to set it up for cpptraj CI if you want.  Then we can add cpptraj tests in Windows through Jenkins and disable the always-seems-to-fail appveyor.

Contact me off-line if you want access to the VM.  (I already installed msys2, so you should be able to go off of the appveyor.yml recipe to set it up).

**Comment by drroe** [comment]
@swails Thanks for the offer! If appveyor keeps acting up even after the test framework overhaul from #514 I will definitely take you up on it.

**Comment by drroe** [comment]
Appveyor has been pretty well behaved since the test framework was cleaned up, so I'll close this for the time being.
