### ISSUE TITLE
Tests to add

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#550]
Placeholder to remind me to do this.

**Comment by drroe** [comment]
- [ ] Read energies from CHARMM output.
- [ ] Test MKL compile, perhaps via https://anaconda.org/intel/mkl

**Comment by drroe** [comment]
CHARMM output read test added during #622.

**Comment by drroe** [comment]
I'm not going to add MKL testing anytime soon. Too much hassle for too little payoff. Also I test locally with MKL all the time.

**Comment by swails** [comment]
I still have designs on getting this back into Jenkins (via a Jenkinsfile so it's more resilient to Jenkins failures).

Once that's the case, we can get MKL testing in there.  We can probably bang this out at the Amber meeting in a couple weeks.
