### ISSUE TITLE
trajout: int Trajout_Single::SetupTrajWrite

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#58]
Dan,

previously, with this method in ``cpptraj``,
```int Trajout_Single::SetupTrajWrite(Topology* tparmIn)```

pytraj is able to open trajout by calling ``int Trajout_Single::SetupTrajWrite(Topology* tparmIn)``
then iterate Frame and write, then close without knowing how many frames ahead.

Is there any reason to change this behavior?

**Comment by hainm** [comment]
Anyway, to simply the pytraj's API, I think I will let users to use cpptraj for pre-processing trajectory from from REMD runs (since pytraj can only support openmp in cpptraj, not MPI).

So which Trajout class you are suggesting for pytraj to use? 

What ``pytraj`` needs is 
+ open a a filename with a given Topology (may be need to specify format too)
+ iterate Frames and write
+ close

current code in ``pytraj`` (used to work with Trajout_Single)

```python
    with Trajout(filename=filename,
                 top=_top,
                 format=format,
                 overwrite=overwrite,
                 mode=mode, *args, **kwd) as trajout:

                for idx, frame in enumerate(traj):
                    trajout.write(idx, frame)
```

What I want is to create a minimal API like that for cpptraj and make it stable.
``pytraj`` can implement further methods from ``cpptraj`` if performance is critical.

**Comment by hainm** [comment]
it's likely that TrajouList is ideal?

```c++
class TrajoutList {
  public: 
    TrajoutList() : debug_(0) {} 
    ~TrajoutList() { Clear(); } 
    void SetDebug(int); 
    void Clear(); 
    /// Add output trajectory to the list and associate with given topology. 
    int AddTrajout(std::string const&, ArgList const&, Topology*); 
    /// \return Array with current output trajectories converted to ensemble output trajectories. 
    int MakeEnsembleTrajout(EnsembleOutList&, int) const; 
    /// Set up trajectories for given topology. 
    int SetupTrajout(Topology*); 
    /// Write frame to normal output trajectories. 
    int WriteTrajout(int, Frame const&); 
    /// Call end for all trajectories 
    void CloseTrajout(); 
    /// List output trajectories. 
    void List() const; 
    /// \return true if no args/trajectories present. 
    bool Empty()     const { return trajout_.empty();     } 
```

**Comment by drroe** [comment]
Hi,

Lets chat about this directly since the API change is significant and I
want to make sure I answer your questions adequately. When will you have
time?

On Wednesday, September 2, 2015, Hai Nguyen <notifications@github.com>
wrote:

> it's likely that TrajouList is ideal?
>
> class TrajoutList {
>   public:
>     TrajoutList() : debug_(0) {}
>     ~TrajoutList() { Clear(); }
>     void SetDebug(int);
>     void Clear();
>     /// Add output trajectory to the list and associate with given topology.
>     int AddTrajout(std::string const&, ArgList const&, Topology*);
>     /// \return Array with current output trajectories converted to ensemble output trajectories.
>     int MakeEnsembleTrajout(EnsembleOutList&, int) const;
>     /// Set up trajectories for given topology.
>     int SetupTrajout(Topology*);
>     /// Write frame to normal output trajectories.
>     int WriteTrajout(int, Frame const&);
>     /// Call end for all trajectories
>     void CloseTrajout();
>     /// List output trajectories.
>     void List() const;
>     /// \return true if no args/trajectories present.
>     bool Empty()     const { return trajout_.empty();     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/58#issuecomment-137250614>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
can you chat now?
