### ISSUE TITLE
error: cannot pass object of non-POD

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#594]
Hi,
I think recent commit causes below error on macos

```
Trajin_Multi.cpp:125:32: error: cannot pass object of non-POD type 'const std::pair<const double, int>' through variadic function; call will
      abort at runtime [-Wnon-pod-varargs]
              mprinterr(" %g", *it);
```

I am using
```
bash configure -shared -macAccelerate -noarpack   -nosanderlib clang CXX="clang++ -stdlib=libstdc++"
make libcpptraj
```

**Comment by hainm** [comment]
```
 $ clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
```

**Comment by dacase** [comment]
Note on a workaround:  if you just comment out line 125 of Trajin_Multi.cpp, the build proceeds.

This swallows up (temporarily) an error message, but at least allows other things to be built and tested with clang.

**Comment by hainm** [comment]
thanks Dave, that helps. I am running tests for both clang and gnu (macos) now.

**Comment by drroe** [comment]
@hainm Can you see if #596 fixed this? Thanks.

**Comment by hainm** [comment]
indeed. thanks.
