### ISSUE TITLE
Reading of CONECT records in PDB leads to bad molecule assignment

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#60]
In PDB 3OIE the CONECT records bond MG to 6 coordinating oxygen atoms - however, these atoms are in arbitrary order so oxygen 547 ends up with a lower molecule number than oxygen 546. Should reading of CONECT records be optional?

**Comment by drroe** [comment]
Note also that the failure to determine molecules leads to several non-fatal memory errors (detected by valgrind).

**Comment by swails** [comment]
Hard to tell what should be done here.  On the one hand, CONECT records store useful information, and other programs in Amber respect them (particularly LEaP).

On the other hand, they're the mechanism by which the PDB indicates bonds in nonstandard residues.  It assumes that "standard" residues have well-defined bonds and so are not listed.  But cpptraj just assigns bonds based on distance (it's certainly not alone in doing this).  Which probably means that it will get most of the the CONECT records specify.

So the question here is whether you are more likely to encounter PDBs with bad CONECT records or more likely that *good* CONECT records assign a bond that cpptraj doesn't based on its distance criteria.

If you suspect the bad PDB count is higher, then optional reads are probably the way to go.  If the other, then automatic reading is probably better.

Keep in mind that "what the user should do" as far as using CONECT records or not will not be clear based without knowing some rather obscure details about cpptraj, so it would be best if that was a workaround for rare corner cases than something that a sizeable number of people will need to know.

**Comment by drroe** [comment]
> So the question here is whether you are more likely to encounter PDBs with bad CONECT records or 
@swails It's not really that the CONECT records are "bad" per se, just bad for cpptraj since it expects atoms, residues, and molecules to be ordered a certain way, i.e. the issue is with cpptraj. My inclination right now is to make an option for turning off reading of CONECT records but leaving it on by default. I don't know how often this will be a "gotcha" but my feeling is that it's a corner case as far as cpptraj is concerned - I assume that most often people will not be using PDBs with these issues as their topology file. Although you know what they say about assuming...

**Comment by swails** [comment]
I agree, probably a minor corner case.  I'm good with your plan.

**Comment by drroe** [comment]
Closed via #77.
