### ISSUE TITLE
Trajout returns ncrst with zeroed forces

### ISSUE THREAD

**Issue by IAlibay** [Amber-MD/cpptraj#630]
Hi,

I have noticed that on writing a ncrst file from a forces containing nc trajectory, the forces data variable is created but is filled with zeroes instead of the actual force values. 

I was wondering if this was intended behaviour?

Cpptraj version: github Amber-MD/cpptraj ``master`` branch

Many thanks,

Irfan

**Comment by drroe** [comment]
I can reproduce the bug and I am working on a fix.

**Comment by IAlibay** [comment]
@drroe That fixed my issue, thanks!

**Comment by drroe** [comment]
Awesome - thanks for the report!
