### ISSUE TITLE
Update CircleCI or find alternative way to test pytraj

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#685]
CircleCI is upgrading to 2.0 - the current build will not work after this Friday (https://circleci.com/docs/2.0/migrating-from-1-2/). @hainm do you want to take a crack at this?

**Comment by drroe** [comment]
@swails is this something the new Jenkins framework could do?

**Comment by swails** [comment]
Jenkins can do anything we wanted it to.  I'm not exactly sure what CircleCI is doing here.

What I would probably do is add a job that automatically updates a "lib-cpptraj" docker image on DockerHub whenever a PR merges to master, and have that job fire off a "test pytraj" job after the upload is finished that pulls that uploaded docker image and tests pytraj inside it.  Then it could send emails for any failed builds.

**Comment by hainm** [comment]
Circleci does similar thing, pull cpptraj and pytraj then compile pytraj to
make sure it compilable. Only a simple test (import pytraj and print
something) is performed.

**Comment by drroe** [comment]
May be addressed by #690

**Comment by drroe** [comment]
@hainm Are you OK with the new pytraj test gate that @swails implemented? Can I get rid of CircleCI? It's no longer supported anyway.

**Comment by hainm** [comment]
Yeah go ahead removing it. Thanks.

**Comment by drroe** [comment]
@swails Does Jenkins have build status icon URLs? I looked around a bit and it seems like there are a few plugins, but it seems it could be a bit of a pain to configure. If they already exist I'd like to add them to cpptraj's README.md, but if they don't no big deal.

**Comment by swails** [comment]
Not that I know of but if there’s a plug-in for it I’d be happy to add it.

**Comment by drroe** [comment]
Handled quite handily by Jenkins, so I'm closing this.
