### ISSUE TITLE
Cpptraj and watershell give unexpected results

### ISSUE THREAD

**Issue by piia600** [Amber-MD/cpptraj#686]
Hi,

I am trying to estimate the number of water molecules within my enzyme's active site. I used the command

'watershell :108@CG watershell_nuc.out lower 6 upper 10'

For most of the frames this works fine, but in some cases, the number of waters is much more than actually in those frames.

See here an example output from VMD (distance <10 to CG of 108):

40 16
41 18
42 16
43 14
44 13
45 12
46 15
47 14
48 17
49 17

And the same frames in the output of cpptraj
      41               5              16
      42               6              18
      43               6              16
      44               6              20
      45               5              22
      46               7              27
      47              12              40
      48              15              45
      49               8              29
      50               8              28
      51               6              21

The first 3 frames (and the frames before) have the same number of water (I noted the difference in frame numbering, VMD displays them from 0). However, on frame 43/44 the amounts start to deviate. The abnormally high water number is retained for some time after which the data converges again, only to be diverted again later.

I can output a totally normal looking dcd trajectory from cpptraj (where the water number corresponds to the output of VMD), and I can also extract single pdbs ('mask ':108@CG<:10.0' maskpdb ./watershell_pdb/watershell.pdb') where the number of water molecules is 15 on frame 48 (and not 45 as watershell suggests).

I think the issue might be that I started with an .xtc trajectory, but the fact that the other outputs work fine makes me think there is a bug in watershell. I am using cpptraj from Amber 16.

I hope there is some explanation/fix for this behavior, since I wouldn't want to load/analyse my hundreds of trajectories in VMD...

**Comment by drroe** [comment]
Hi,

Could this be due to imaging? The `watershell` command by default uses the minimum image convention, so e.g. a water that is close to your target area but on the other side of a periodic boundary still gets counted. A simple way to test if this the issue is to turn imaging off for `watershell` via the `noimage` keyword.

**Comment by piia600** [comment]
I tried to run it with the noimage keyword, but it had no effect on the results.

**Comment by piia600** [comment]
Ok, apparently it works if I don't modify the original trajectory in any way (wrapping, aligning etc) and still keep the imaging on.  Thanks for guiding me to the correct track, it was quite a mystery to me where the extra waters come from 👍

**Comment by drroe** [comment]
> Ok, apparently it works if I don't modify the original trajectory in any way (wrapping, aligning etc) 

Oh, were you doing something like an RMS best-fit before `watershell`? If so, this is a problem as rotation of the coordinates will screw up any subsequent imaging (cpptraj should be printing a warning about this).

**Comment by piia600** [comment]
I just wanted to do everything in one script.. Apparently, it is better to leave the creation of the to-be-visualized trajectories out from the analysis script. :)

**Comment by drroe** [comment]
You can do the rms fitting in the same script, it just has to go after anything that requires imaging (autoimage, various distance calculations, etc)

**Comment by drroe** [comment]
Seems this issue is resolved. If not, feel free to reopen.
