### ISSUE TITLE
add `parm` to cpptraj input for testing

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#69]
I prefer to have cpptraj testing input to have consistent syntax. It's easier to parse. 

for example, this is a good ``traj.in`` that ``pytraj`` can uses to compare data to cpptraj.

`cat traj.in`
```
parm 2koc.parm7 # need to have parm here
trajin traj.x
....
```

``pyraj`` will use above input to create `CpptrajState`

(dir: `cpptraj/test/Test_DRMSD`)
```python
In [8]: state = pt.load_cpptraj_file('./drmsd.in')

In [9]: state.run()
Out[9]: 0

In [10]: state.datasetlist.values
Out[10]:
array([[  0.00000000e+00,   2.95729211e+00,   4.49201771e+00, ...,
          5.18656700e+00,   5.37325298e+00,   4.82324321e+00],
       [  0.00000000e+00,   4.02238772e+00,   6.57384971e+00, ...,
          9.72083983e+00,   1.02589014e+01,   9.38592381e+00],
       [  2.43182129e-07,   4.01623189e+00,   6.41421043e+00, ...,
          8.27504991e+00,   8.19405473e+00,   7.77917637e+00],
       [  0.00000000e+00,   2.95729211e+00,   4.49201771e+00, ...,
          5.18656700e+00,   5.37325298e+00,   4.82324321e+00]])
```

For example:
* this test does not `parm` in input: `cpptraj/test/Test_IRED`
* this one does: `cpptraj/test/Test_DRMSD`

If you think this is an ok proposal, I will remind you in the future if you add more test folder.

**Comment by drroe** [comment]
> I prefer to have cpptraj testing input to have consistent syntax. It's easier to parse.

Maybe so, but I prefer to have a mix of 'parm' and '-p' in my tests; this way command line flags get tested as well (same reason sometimes it's -i and sometimes not for input files).

**Comment by swails** [comment]
> Maybe so, but I prefer to have a mix of 'parm' and '-p' in my tests; this way command line flags get tested as well (same reason sometimes it's -i and sometimes not for input files).

+1

**Comment by hainm** [comment]
Oops. Yeah. Agree. Forgot about -p
