### ISSUE TITLE
RMSD based clustering

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#693]
Can you elaborate on whether we can do RMSD based clustering in cpptraj or not?
If yes I would really appreciate on what page number of amber18 manual can I find it?

**Comment by hainm** [comment]
I think you can just specify `rms` keyword in `cluster` command.

**Comment by hainm** [comment]
> If yes I would really appreciate on what page number of amber18 manual can I find it?

I think it's 702.

**Comment by DDGmichigan** [comment]
Also can I do side chain based clustering instead of backbone RMSD?

________________________________

**Comment by hainm** [comment]
I recall  you can use `mask` to specify the atom selection.
And I am not sure if cpptraj really use backbone RMSD as the default clustering metric.

**Comment by drroe** [comment]
> And I am not sure if cpptraj really use backbone RMSD as the default clustering metric.

@hainm is correct here; the `mask` that you specify (along with other distance metric options) determines how the distance metric is calculated. Read the manual, make sure you understand what the keywords are doing, check out the [clustering tutorial](http://www.amber.utah.edu/AMBER-workshop/London-2015/Cluster/) (it's for combined clustering but the core concepts are the same), and experiment with small numbers of frames (say around 100) until you're familiar with how clustering in cpptraj works. There's no substitute for practical experience!

**Comment by drroe** [comment]
Seems the issue is solved.
