### ISSUE TITLE
distance command in cpptraj not picking up atom masks

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#700]
Hi,
I have this input file
parm ../run_1/ACN_IL1B_solvated.prmtop
trajin ../run_1/prod/ACN_IL1B_production4A.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4B.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4C.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4D.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4E.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4F.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4G.mdcrd 1 1250 1
trajin ../run_1/prod/ACN_IL1B_production4H.mdcrd 1 1250 1
autoimage
strip :WAT
reference ../run_1/ACN_IL1B_allmin.rst
distance acetonitrile :169 :24 out distance.out noimage
run

I am trying to specifically calculate the distance between acetonitrile_label 169@N1 and residue 24@H

But I am unable to provide this atom mask selection in cpptraj.  ANybody can tell me why is this happening?

**Comment by hainm** [comment]
can you please post the cpptraj log?

**Comment by DDGmichigan** [comment]
@hainm  It works now. My mistake! I had an extra colon in the mask.typo error.
Thanks
