### ISSUE TITLE
cpptraj.MPI is confused

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#720]
parm x.prmtop
trajin abc.mdcrd 1 20000 1
trajin abc2.mdcrd 1 20000 1

center mass origin :1-200
image origin center

reference imaged.pdb
strip :Cl-,Na+

cluster C1 :115,116,119,156&!@H= clusters 10 out cluster01.dat summary summary01.dat clusterout pdb.cx

it works when I do cpptraj<cluster.in

but when i do 
mpiexec -n 4 cpptraj.MPI <cluster.in

It just reads trajin the first line and just stands there stationary doing nothing !
any ideas?

**Comment by drroe** [comment]
> it works when I do cpptraj<cluster.in

Don't use STDIN with cpptraj.MPI. Use `-i` instead, e.g.
```
mpiexec -n 4 cpptraj.MPI -i cluster.in
```

**Comment by hainm** [comment]
@drroe may be add warning to direct user to always use `-i` instead of `<`?

**Comment by drroe** [comment]
> may be add warning to direct user to always use -i instead of <?

See #709

**Comment by drroe** [comment]
@DDGmichigan did you try `-i`? Did it work for you?

**Comment by DDGmichigan** [comment]
Hi Dan,
Yes it did work I tried it few moments earlier.
Thanks so much!
Debarati

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by drroe** [comment]
Excellent. I'll close this and get to #709 as soon as I can.

**Comment by DDGmichigan** [comment]
Thank you

**Comment by DDGmichigan** [comment]
I am really waiting to see  #711 resolved . Thanks
