### ISSUE TITLE
How to convert jpeg from gnu file using cpptraj

### ISSUE THREAD

**Issue by saikat0003** [Amber-MD/cpptraj#745]
I have performed secstruct command successfully using the command:
 secstruct:1-45 out t-dssp.gnu
Now I want to convert gnu into a jpeg file. I have seen in write command (p 625 manual amber 19). I am unable to use it.

**Comment by drroe** [comment]
You don't say what you actually tried and what the result was (error message etc), so I'm just guessing at what might be wrong. When using gnuplot output with the `jpeg` option you need to actually run the file with gnuplot to generate the jpeg. The `jpeg` option generates gnuplot input that has the output device set to jpeg.

**Comment by saikat0003** [comment]
Thank you. This problem is solved
