### ISSUE TITLE
Code cleanup 2

### ISSUE THREAD

**Issue by ValZapod** [Amber-MD/cpptraj#756]
@drroe Thanks for fast patches. I usually do not do pull requests. And yeah, it is not all at all🤣🤣
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/molsurf.c#L4249-L4253
You probably missed it. Parameter 'xaxis' is not used in function body. Maybe some of line 4324 or 4325 should use xaxis. Or delete xaxis at all.
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/molsurf.c#L3961
Again, missed it)) Variable is assigned to itself. Git blame https://github.com/Amber-MD/cpptraj/blame/585842232192a7d2e59cd730f465760a843009a0/src/molsurf.c#L3961
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/molsurf.c#L6871
Here: there is no free(group); All other returns indeed have free.
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/ReferenceAction.cpp#L103
Now, you do not `delete trj;` here. Really someone should use clang-format on all code))
Valgrind is good, but nothing is better than static analysis.
The same about other in my first issue.))
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Action_HydrogenBond.h#L236
Just `return false;` here
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/CpptrajState.cpp#L1451
Here you should `delete ref;` created on line 1448.
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/CmdInput.cpp#L33
end > 0 is always true (it is without sign (size_t) and end == 0 is already checked (chain rule also applied, from left to right))
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Analysis_HausdorffDistance.cpp#L165-L170
Maybe   
```
if (df != 0) {
df->AddDataSet( out_ );
if (dfab != 0) 
df->AddDataSet( ab_out_ );
if (dfba != 0)
df->AddDataSet( ba_out_ );
}
``` 
Do not forget that a->b is just shorthand for (*a).b
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Analysis_HausdorffDistance.cpp#L145
Maybe check out_ == 0 ? We are in else if already so return may not have worked.
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Action_XtalSymm.cpp#L1090
Break, where is it? Though it is not important, I suppose as we return))
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Action_Remap.cpp#L57
Always true... Maybe.
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/DataSet_Modes.cpp#L804-L806
What is the point? Already done on lines https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/DataSet_Modes.cpp#L781-L783
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/DataSet_Coords_TRJ.cpp#L63
Maybe `delete trajin;` here

https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Exec_CrdAction.cpp#L53
And here delete crdOut; created on line 40.
That is all. P.S. Nope))

**Comment by ValZapod** [comment]
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/readline/complete.c#L743
You can delete this else at all... This just looks bad(( I understand it is Third party and all but...

https://github.com/Amber-MD/cpptraj/blob/c38a771bb07721724d444c875de50c5c8864f6bf/src/molsurf.c#L4064
Still better delete this line... I mean it is your mistake entirely https://github.com/Amber-MD/cpptraj/commit/b412c1060505204da600741b00954d05eaeb131c (load large diff) as you can see in git blame https://github.com/Amber-MD/cpptraj/blame/8ad769dfe02f4f74649aa5c2b86dcb7965701ca1/src/molsurf.c#L4064
And about rewriting to c++, it is never a good idea))) I understand if you write something in c++ but rewrite from c? What you hope for? ))

**Comment by ValZapod** [comment]
Valgrind is good, but nothing is better than static analysis.
https://github.com/Amber-MD/cpptraj/blob/c38a771bb07721724d444c875de50c5c8864f6bf/src/ReferenceAction.cpp#L102
Here we return but only on line 
https://github.com/Amber-MD/cpptraj/blob/c38a771bb07721724d444c875de50c5c8864f6bf/src/ReferenceAction.cpp#L104
we do the destructor magic. So I suppose one should delete trj; after all))
The same about other in my first issue.))

**Comment by ValZapod** [comment]
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Control.cpp#L237
"Array overrun is possible. The value of 'MH.endOp_' index could reach 4." Not like I see it)) But usually it is true... So...

https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/DataIO_Std.cpp#L737
This looks wrong if you look into std::fill https://en.cppreference.com/w/cpp/algorithm/fill

Maybe `std::fill(mat, mat + 9, 0.0); ` like on line 682.

So, mmm... Do you think I should check the whole AmberTools and Amber? Maybe I will just send you files?

**Comment by ValZapod** [comment]
```
xdrfile_trr.c	263	err	V595 The 'v' pointer was utilized before it was verified against nullptr. Check lines: 263, 270.
xdrfile_trr.c	286	err	V595 The 'f' pointer was utilized before it was verified against nullptr. Check lines: 286, 295.
xdrfile_trr.c	389	err	V595 The 'v' pointer was utilized before it was verified against nullptr. Check lines: 389, 396.
xdrfile_trr.c	410	err	V595 The 'f' pointer was utilized before it was verified against nullptr. Check lines: 410, 417.
xdrfile_trr.c	439	warn	V522 There might be dereferencing of a potential null pointer 'sh'. Check lines: 439, 436.
```
I do not know if this is possible but... The last is about calloc() returning NULL I suppose...
https://github.com/Amber-MD/cpptraj/blob/585842232192a7d2e59cd730f465760a843009a0/src/Matrix_3x3.cpp#L184
This and also line 186, 188 will only executed once... So...

**Comment by ValZapod** [comment]
@drroe So, should I give you pull request))

**Comment by drroe** [comment]
@ValZapod I appreciate all the work that has gone into these comments. Unfortunately I have a lot of other things demanding my attention at my day job (I don't really get paid to develop cpptraj so I don't have as much cpptraj development time as I used to) so I just haven't been able to get to them yet. Feel free to open a PR if you want - otherwise it will have to wait until some free time opens up (hopefully soon!).

**Comment by ValZapod** [comment]
@drroe Okay))

**Comment by drroe** [comment]
I'll try to work on some of this today.

**Comment by ValZapod** [comment]
@drroe first look at this one 
First look into std::fill please))

**Comment by drroe** [comment]
> You probably missed it. Parameter 'xaxis' is not used in function body. Maybe some of line 4324 or 4325 should use xaxis. Or delete xaxis at all.

I don't  see the harm in leaving it as-is. Unlikely to be a performance bottleneck and as I mentioned before I'm much more hesitant to modify code I didn't originally write unless there's a bug. I could be convinced otherwise.

> concave_cycle[icycle].iface = concave_cycle[icycle].iface;

This was actually in the original code, and based on context I think it's a bug. Looks like it's supposed to be getting assigned `tmp_cycle.iface`. I changed it and limited testing shows no changes in results, so I think this is ok.

**Comment by drroe** [comment]
> Here: there is no free(group); All other returns indeed have free.

I did miss that one, thanks. 

> Though maybe it is not. And you just copied code. I do not know))

That is actually in the original code as well. Believe it or not I actually cleaned up a lot of the original code. You would have had a field day with that...

**Comment by drroe** [comment]
> And about rewriting to c++, it is never a good idea))) I understand if you write something in c++ but rewrite from c? What you hope for? ))

Strongly disagree here - after all, cpptraj started as a C++ rewrite of C code (ptraj). :smile:

Benefits of a rewrite:
1) If the code is old and not under active development, a rewrite is a good way to bring it back to life. You can ensure best practices are used and properly document as you go. 
2) A rewrite (at least in my experience) of old code tends to reveal areas for optimization or lurking bugs.
3) A rewrite is also a good place to add features that aren't present in the old code. For example, it would be great to have the per-atom surface area from molsurf, but in the old code this was only partially implemented.
4) C to C++ allows use of the STL, the benefits of which I don't think I need to enumerate here.

**Comment by ValZapod** [comment]
First 3 could and should be done without rewriting and (probably) introducing new bugs...))

**Comment by ValZapod** [comment]
@drroe Wow, that was fast))) So I wanted to ask you if that break in previous issue and that std::fill are important? I mean did I help you at all, because it is not obvious for me... And again should I check Amber as a whole? I will email you list of bugs then (without github links, alas). I am just using static analyzer, if you are wondering))

**Comment by drroe** [comment]
> So I wanted to ask you if that break in previous issue and that std::fill are important?

Those in particular weren't too critical from an execution standpoint. The `break` was really cosmetic because of the `return` (as you noted) and the matrix not being correctly initialized was OK in this case because if the number of numbers scanned wasn't 9, the read exits before `mat` is used anyway (could probably get away with no init there but it doesn't really cost much and is more correct).

> I mean did I help you at all, because it is not obvious for me

It has definitely helped to have a fresh set of eyes looking at the code! Although some fixes are more cosmetic in nature, others were very helpful (e.g. all the times routines were exiting without properly freeing memory) and still others led me to find other things off with the code (a valgrind trace while looking at some of the `crdaction` stuff helped me find uninitialized variables in `Action_Energy`).

> And again should I check Amber as a whole?

Certainly you are welcome to do this, but that's a pretty monumental undertaking. Sander alone is probably tons of work. Do you have access to the Amber gitlab repo? If not, you could contact @dacase or @swails for access.

> I will email you list of bugs then

I'm going to be up front and let you know I probably won't be able to handle all the Amber bugs you find (I'm barely keeping up with the cpptraj ones!). My advice if you really want to contribute will be to get gitlab access, then open merge requests to fix the bugs you find. Things will just be faster that way.

**Comment by ValZapod** [comment]
@drroe No, break in previous issue! I mean that one https://github.com/Amber-MD/cpptraj/blob/c38a771bb07721724d444c875de50c5c8864f6bf/src/Atom.cpp#L642-L643

Okay, will be happy to have those mentioned people give me an access to gitlab repo... Indeed that will be faster, because there are still rather much false positves.

**Comment by drroe** [comment]
>  No, break in previous issue! I mean that one

Oh yeah, that one was good. In the grand scheme of things the difference between 1.71 and 1.68 Angstroms isn't that much, but it's better to be correct!

**Comment by ValZapod** [comment]
@drroe @swails So, can somebody give me a read access as said here http://dev-archive.ambermd.org/201806/0014.html ? Or should a send an email? All the info is on github (real name, username, email). Thanks))

**Comment by ValZapod** [comment]
@swails Okay, I send you an email))
