### ISSUE TITLE
cpptraj add "Z" column to pdb output?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#759]
hi, 
pytraj has been failing for awhile due to the change in pdb format.
In below line, the 'Z' column is new. Is it expected?
`ATOM      1  N   SER Z   1      -1.889   9.159   7.569  1.00  0.00           N`
Here is the the assertion in pytraj:
https://github.com/Amber-MD/pytraj/blob/7ee64bd01060606b55b6ec464f3ab2f0e418df2b/tests/test_io/test_io.py#L336

Here is the input commands:
```
parm tz2.parm7
trajin tz2.nc 1 1
trajout test.pdb
```

cheers

**Comment by drroe** [comment]
> Is it expected?

Yes. This change was made at the suggestion of @dacase in order to better conform to the PDB standard. See https://github.com/Amber-MD/cpptraj/pull/747

Seems I need to improve my CI testing with pytraj. I may just have to add a full pytraj build and test somewhere.

**Comment by hainm** [comment]
thanks @drroe. I will update pytraj tests.

> Seems I need to improve my CI testing with pytraj. I may just have to add a full pytraj build and test somewhere.

I think it's ok to let it as is for now.  pytraj has nightly testing and it detects the failure but I was to lazy to fix (since it's not critical, just a matter of clarifying with you and updating the test).

By the way, the full pytest test does not take that long, only about 1 minute.

**Comment by swails** [comment]
cpptraj should test pytraj via the Jenkins pipeline.  It's worth seeing why this failed to catch the pytraj issue.

**Comment by drroe** [comment]
> cpptraj should test pytraj via the Jenkins pipeline. It's worth seeing why this failed to catch the pytraj issue.

OK, so it's weird. If I look at a PR from after the introduction of the PDB chain ID change (#753), the associated pytraj build + test on Jenkins [passed](https://jenkins.jasonswails.com/blue/organizations/jenkins/amber-github%2Fpytraj/detail/pytraj/47/pipeline). @hainm is this because the tests were run with `--simple`?

**Comment by hainm** [comment]
Yeah, the —simple only to make sure cpptraj wont break pytraj compilation.

**Comment by drroe** [comment]
@hainm so would you recommend that `run_tests.py` be run without the `--simple` option?

**Comment by hainm** [comment]
Yeah I think so, given that full pytraj test only takes 1-2 minutes.

**Comment by drroe** [comment]
@swails this may be a silly question, but where is `run_tests.py` called from on Jenkins? I can't seem to find it in any of the files in the repo. Is it part of the docker image?

**Comment by swails** [comment]
It's called from here: https://github.com/Amber-MD/pytraj/blob/master/Jenkinsfile#L30

The pytraj job is triggered from inside the cpptraj job from here: https://github.com/Amber-MD/cpptraj/blob/master/Jenkinsfile#L150-L152

**Comment by hainm** [comment]
> It's called from here: https://github.com/Amber-MD/pytraj/blob/master/Jenkinsfile#L30

I don't see it. J/K, updated.
