### ISSUE TITLE
command line flags -ya and -xa do not work

### ISSUE THREAD

**Issue by Haruk-Kono** [Amber-MD/cpptraj#762]
Hi,
I installed AmberTools 19 from anaconda cloud (cpptraj: V4.14.0).

I used new flag ```-xa``` and ```-ya``` (#614)  as follows
```cpptraj -p top.prmtop -y pro_01.mdcrd -y pro_02.mdcrd -y pro_03.mdcrd -ya "1 last 10" ```

According to #614, above input may be equivalent to
```
parm top.prmtop
trajin pro_01.mdcrd 1 last 10
trajin pro_02.mdcrd 1 last 10
trajin pro_03.mdcrd 1 last 10
```
but I got following return
 ```
        Arguments for 3 input trajectories:
          pro_01.mdcrd 1
          pro_02.mdcrd last
          pro_03.mdcrd 10
        Reading 'pro_01.mdcrd' as Amber NetCDF
        Reading 'pro_02.mdcrd' as Amber NetCDF
        Reading 'pro_03.mdcrd' as Amber NetCDF
        Loading previous history from log 'cpptraj.log'
```

Is there something wrong with my input?

**Comment by drroe** [comment]
> Is there something wrong with my input?

Not exactly. I think the problem here is that the shell is interpreting your quotes before they get to cpptraj, so what cpptraj sees is actually:
```
cpptraj -p top.prmtop -y pro_01.mdcrd -y pro_02.mdcrd -y pro_03.mdcrd -ya 1 last 10
```
What you need to do is escape the quotes with a backslash `\` so that the shell leaves them alone:
```
cpptraj -p top.prmtop -y pro_01.mdcrd -y pro_02.mdcrd -y pro_03.mdcrd -ya \"1 last 10\"
```
I think that should work. Let me know if not. If it does work I'll have to add a little note in the docs.

**Comment by Haruk-Kono** [comment]
@drroe 

I tried your command 
```
cpptraj -p top.prmtop -y pro_01.mdcrd -y pro_02.mdcrd -y pro_03.mdcrd -ya \"1 last 10\"
```
and it worked as follows!
```       
        Arguments for 3 input trajectories:
          pro_01.mdcrd 1 last 10
          pro_02.mdcrd 1 last 10
          pro_03.mdcrd 1 last 10
        Reading 'pro_01.mdcrd' as Amber Trajectory
        Reading 'pro_02.mdcrd' as Amber Trajectory
        Reading 'pro_03.mdcrd' as Amber Trajectory
        Loading previous history from log 'cpptraj.log'
```
Thank you for your suggestion!
I hope my trouble will be helpful for somebody.

**Comment by drroe** [comment]
Glad to help!
