### ISSUE TITLE
cpptraj.MPI does not run

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#764]
Input file slurm script is as follows
#! /bin/bash
#SBATCH -J updated_1P3_jobs
#SBATCH -o array_out.txt
#SBATCH --partition=cpuland
#SBATCH --array=1-305%5
#SBATCH -n 4 # This means one task per job..

###############################################################
export submit_dir=/users/debarati/PHANI_ABL_KINASE/ACN_H2O_5-95vv_layered/3kfa_ACN_xplor_bind_energ_last5ns_10runs/ANALYSIS_NEW/cumulative_prob_1P3/$1
cd $submit_dir
echo Working Directory = $submit_dir
echo Hostname = `hostname -s`
echo Date = `date`

export AMBERHOME=/usr/local/amber18
export CUDA_HOME=/usr/local/cuda-9.2
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$CUDA_HOME/lib64
export MPI_HOME=/usr/local/mpich-3.2.1

name=$(awk -F "_" '{print $2}' "$2"| sed 's:.in::g')

while read x ;
do

$MPI_HOME/bin/mpiexec -n 4 cpptraj.MPI -i "$x" > "$x"_log
done<$2

Error I get is 
Working Directory = /users/debarati/PHANI_ABL_KINASE/ACN_H2O_5-95vv_layered/3kfa_ACN_xplor_bind_energ_last5ns_10runs/ANALYSIS_NEW/cumulative_prob_1P3/RUN1
Hostname = grape6
Date = Mon Oct 7 15:25:27 EDT 2019
cpptraj.MPI: error while loading shared libraries: libmpicxx.so.12: cannot open shared object file: No such file or directory
cpptraj.MPI: error while loading shared libraries: libmpicxx.so.12: cannot open shared object file: No such file or directory

**Comment by drroe** [comment]
Based on your script, try adding:
```sh
export LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH
```
below the `export MPI_HOME`

**Comment by DDGmichigan** [comment]
Its running,, waiting for output!
Thanks!

**Comment by DDGmichigan** [comment]
Works!
Thank you so much!
