### ISSUE TITLE
Create separate CMAKE build system

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#784]
Right now, the cpptraj cmake build system is dependent on being inside of AmberTools. This is not ideal, since presumably (hopefully?) a lot of people are using cpptraj direct from GitHub but would still like to use cmake. So I'd like to put an independent cmake build system in place. The trick will be making it play nicely with Amber's cmake system when cpptraj is inside AmberTools. I presume there is some way to do this, although my cmake knowledge is pretty slim so it's possible this is all a pipe dream.

@multiplemonomials if you have any advice on this front I'd appreciate it. I also wanted to let you know that this is hopefully coming down the pipe in case you start working on the Amber cmake system.

**Comment by multiplemonomials** [comment]
Wait the cpptraj CMake build system already supports standalone builds, and has for years.  That's how the AppVeyor CMake build is able to work!

**Comment by drroe** [comment]
Addressed by #955.
