### ISSUE TITLE
Tinker ARC without Title

### ISSUE THREAD

**Issue by genericsciencer** [Amber-MD/cpptraj#801]
I run TINKER without having title information within the ARC files. Using `trajin my_traj.arc_1 parm [x] as arc` where `head my_traj.arc_1` is 
```
 123123
   125.000000  125.000000  125.000000   90.000000   90.000000   90.000000
      1  N    -15.743424  -13.783230    7.570206   231      2      5      6      7
```
gives `Error: Could not get # atoms / title from Tinker file.`

I fixed this issue by changing the first line of the relevant arc files to ` 123123 SOMETITLE`. Just wanted to let others know that the title is currently required for reading via trajin.

**Comment by drroe** [comment]
Should be addressed by #802 once it is merged in. Thanks for the report!

**Comment by drroe** [comment]
Should be fixed now. Let me know if not.

**Comment by drroe** [comment]
Please re-open this issue if #802 has not addressed it. Thanks!
