### ISSUE TITLE
Using the new DTR reader

### ISSUE THREAD

**Issue by slochower** [Amber-MD/cpptraj#815]
Hi Dan, I'm trying to take advantage of the newly adding DTR support (https://github.com/Amber-MD/cpptraj/pull/796) to process some Desmond trajectories. As far as I can tell, `cpptraj` doesn't yet support reading the CMS input files as topology, so I've used the Schrodinger `structconvert` utility to try converting the CMS to PDB and MOL2. Whenever I do that, and read the PDB/MOL2 into `cpptraj` with the DTR trajectory, I get a mismatch between the number of atoms in the trajectory and the number of atoms in the topology:

```
Error: # of atoms in DTR (216125) != # atoms in associated topology (216124)
```

I'm guessing this is because of a lone pair or pseudoatom in the originating FF that doesn't show up in the PDB/MOL2. Do you have tips or suggestions for how to use the new DTR reading with a Desmond trajectory? 

~~I know this is using the VMD plugin under the hood. In VMD, I can load the CMS and DTR pair directly and view the trajectory there. If I use VMD to output a PDB (instead of using `structonvert`), then `cpptraj` complains (e.g., `Warning:   Old # residues= 20019, new # residues = 50315`) but will use that PDB as topology. Example snippet:~~

```
# Written by VMD after loading in the CMS and exporting a PDB
parm tmp.pdb
# Written by Desmond
trajin tmp_trj/clickme.dtr
strip :SPC
parmwrite out tmp.prmtop
trajout tmp.nc onlyframes
```

~~But if I try to load in `tmp.prmtop` and `tmp.nc`, then `cpptraj` recognizes there's an atom number mismatch.~~

```
Error: Number of atoms in NetCDF file (70937) does not match number
Error:  in associated topology (216125)!
```

**Edit**: I _can_ use the DTR trajectory directly with `cpptraj` if I use VMD to load the input CMS and write a PDB file. I forgot to do `strip :SPC outprefix tmp` in the first `cpptraj` input file when writing `tmp.prmtop`.

**Comment by drroe** [comment]
> As far as I can tell, cpptraj doesn't yet support reading the CMS input files as topology

Yeah; CMS is a database format that requires some extra dependencies. I guess I could think about supporting it via the VMD plugin framework like I do with DTR but it's a non-negligible amount of work and unfortunately my time is really limited these days.

>  If I use VMD to output a PDB (instead of using structonvert), then cpptraj complains (e.g., Warning: Old # residues= 20019, new # residues = 50315) 

Maybe try writing to a Mol2 file instead. As a topology format, PDB is pretty terrible. Among other things there is almost no actual topology info; all connectivity outside of some LINK/CONECT records is inferred. The Mol2 format at least has bonds, which is needed to make sure you get molecules correct.

**Comment by slochower** [comment]
> Yeah; CMS is a database format that requires some extra dependencies. I guess I could think about supporting it via the VMD plugin framework like I do with DTR but it's a non-negligible amount of work and unfortunately my time is really limited these days.

Right, got it. I can go through VMD, especially since it's easy to script it to work headless.

> Maybe try writing to a Mol2 file instead. As a topology format, PDB is pretty terrible. Among other things there is almost no actual topology info; all connectivity outside of some LINK/CONECT records is inferred. The Mol2 format at least has bonds, which is needed to make sure you get molecules correct.

Yup. Doesn't work if I use Schrodinger to go to MOL2, but it does work with VMD.

So I think I can actually close this issue. The solution is to use VMD to write out topology, whether that's PDB (not ideal due to CONECT record ambiguity) or MOL2.

**Comment by drroe** [comment]
> Yup. Doesn't work if I use Schrodinger to go to MOL2, but it does work with VMD.

Open source FTW! :smiley:
