### ISSUE TITLE
arbitrarily iterate Trajectory with given frame indices: parallel benefit

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#83]
Dan,

AFIAK, cpptraj does not have option to iterate trajectory with given frame indices (only support start, stop, stride).

I am thinking about parallelize CpptrajState for simple actions.

For example

```bash
parm 2koc.parm7
trajin md0.nc 0 1000 10
trajin md1.nc 0 1000 10
trajin md2.nc 0 1000 10
....
ref restart.nc
autoimage
rms reference @CA
distance :1 :2
```

In pytraj, above script will be like this

```python
traj = pt.iterload('md*.nc', '2koc.parm7', frame_slice=[(0, 1000, 10),]*3)
data = pt.load_batch(traj, '''
ref restart.nc
autoimage
rms reference @CA
distance :1 :2
''', n_cores=8)
```

So my wish is to have frame_indices = range(traj.n_frames): if using n_cores=8, pytraj will create 8 CpptrajState in each core and lt each state perform calculation with a chunk of frame indices.

What's your advice here?

My idea is quite simple, just make the parallel run more abstract:

* load a bunch of files by ``iterload`` with arbitrary frames
* tell pytraj/cpptraj to run the job in N nodes
* take the data

**Comment by hainm** [comment]
Currently pytraj has parallel implementation but this is only good for single calculation. For multiple actions, ``pytraj`` can't not beat ``cpptraj`` due to python overhead (example shown below, again).

python has builtin multiprocessing so I don't bother user to install  MPI.
```
ref restart.nc
autoimage
rms reference @CA
distance :1 :2
```

**Comment by drroe** [comment]
@hainm This is currently an area of active development. It's not just splitting up the trajectory, it's making sure the data is correctly used afterwards as well (e.g. a covariance matrix needs to be properly summed up, data set time series need to be put in the correct order, etc). I'm currently working on this in-house and will keep you up to date on my progress.

**Comment by hainm** [comment]
cool. I am waiting for it. Hopefully you release it soon. ha ha.

**Comment by hainm** [comment]
@drroe 

I just double-check cpptraj's man and found 'crdframes', which is what pytraj currently need.

It's likely that cpptraj has everything I need to make pytraj and cpptraj better. So my job now is only to ask you 'does cpptraj has this, where is it'. lol.

**Comment by hainm** [comment]
'crdframes' solves my problem. Just added a [PR](https://github.com/Amber-MD/pytraj/pull/851)  for ``pytraj``. I am closing this.
