### ISSUE TITLE
Internal Error: Adding DataSet test copy to invalid list.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#84]
So I am having trouble with adding Analysis class to CpptrajState.

I just created a State and add a MatrixDouble dataset with name 'mat'

```python
In [105]: s2
Out[105]:
CpptrajState, include:
<datasetlist: 1 datasets>

In [106]: s2.datasetlist[0]
Out[106]: <pytraj.datasets.DatasetMatrixDouble: size=666, key=mat>
```

I just want to add Analysis_Matrix class to analyze the matrix:

```
In [109]: s2.add_analysis(Analysis_Matrix(), ArgList('matrix mat name test'))
Internal Error: Adding DataSet test copy to invalid list.
Error: Could not setup analysis [matrix]
Out[109]: 1
```

It's clearly that I don't understand how cpptraj works at all. Can you point me where I can read? thanks.

**Comment by hainm** [comment]
it's likely because of using 'AddCopyOfSet' rather 'AddSet' method. uhm.

**Comment by hainm** [comment]
In another example,

I created a Dataset_Coords_TRJ, load trajectory to it and:

```python
dslist = DatasetList()

# add TRJ coords to dslist
dslist._add_traj(traj)

# create Analysis_Rms2D object
act = CA.Analysis_Rms2d()

# perform analysis
act('crdset _traj @CA out test', dslist=dslist, top=traj.top)
```

The thing is: this analysis can find the DataSet with name '_traj' but (again), I got

`Internal Error: Adding DataSet Rms2d_00001 copy to invalid list.
Error: Could not set up DataSet for calculating 2DRMS.`

Is there any trivial way to make this work?

**Comment by hainm** [comment]
ok, from DSL code, I see now.

Just don't use AddCopyofSet but using AddSet and let DSL free the memory.

**Comment by drroe** [comment]
@hainm here it may have helped to read the internal documentation for DataSetList (DataSetList.h), or maybe you did read it but it wasn't clear (and that's on me).

Essentially there are two modes for DataSetList: as owner of data, i.e. DataSetList is responsible for allocating, holding, and freeing the DataSets it contains (like the master DataSetList in CpptrajState), or as a "keeper" of data, i.e. DataSetList just has pointers to the data but is not responsible for the memory. The "keeper" mode is useful for functions like GetMultipleSets(), or for use in DataFile. Does this make more sense now?

**Comment by hainm** [comment]
actually you told me about two modes before. 

Can you tell more about this error?

'Internal Error: Adding DataSet test copy to invalid list.
Error: Could not setup analysis [matrix]'

**Comment by drroe** [comment]
Although the error message needs to be improved, you get messages like this if 1) you try to add an instance of a DataSet to a DataSetList that is set up to only contain copies (which is your case) or 2) you try to add a copy of a DataSet to a DataSetList that does *not* have copies.

**Comment by hainm** [comment]
ok. thanks.

So what's about this error message.

First, I arbitrarily add a TRJ to DatasetList and tell cpptraj to calculat rms2d.

`Internal Error: Adding DataSet Rms2d_00001 copy to invalid list. Error: Could not set up DataSet for calculating 2DRMS.`

Note that `DataSet Rms2d_00001` was added by cpptraj, not me.

**Comment by drroe** [comment]
I need to see the code. Without seeing it I can only guess. My guess is that the problem is happening inside Rms2d; the DataSetList you are providing to Analysis_Rms2d::Setup() is set up to hold copies (i.e.) hasCopies_ is true.

**Comment by hainm** [comment]
I don't think this is import to pytraj (anymore since I can work around). So I am closing this issue.
