### ISSUE TITLE
nastruct: stagger array length?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#851]
Hi,
I am working on an issue in pytraj (https://github.com/Amber-MD/pytraj/issues/1519). I am trying to understand how cpptraj stores the data for `stagger`.

Here is the cpptraj command with this data https://github.com/Amber-MD/pytraj/files/4274861/new.tar.gz

```
import pytraj as pt

s = pt.load_cpptraj_state("""
parm wbox_no_water_ions.prmtop
trajin run_nowater.nc
nastruct
""")

s.run()
```

Then I try to get the length of the `stagger` array:
```
In [5]: for d in s.data[1:]: 
   ...:     if d.aspect == 'stagger': 
   ...:         print(d.key, d.values.shape) 
   ...:          
   ...:          
   ...:                                                                                                                                             
1C24G (1000,)
2G23C (1000,)
3C22G (1000,)
4C21G (1000,)
5A20T (1000,)
6A19T (1000,)
7C18G (1000,)
8G17C (1000,)
9A16T (1000,)
10C15G (1000,)
11U14A (960,)
12G13C (563,)
```

You can see that most of the basepair has array length of 1000 (as expected since the trajectory has 1000 frames). 
But here is the difference
```
11U14A (960,)
12G13C (563,)
```

Any idea why? Does that mean the rest is just zero? Thanks.

**Comment by drroe** [comment]
OK - I see the error now. UpdateSeries isn't being called when there is no output file. It's a bug. Temporary workaround is to specify an output file. I'll work on a fix in the meantime. Thanks.

**Comment by drroe** [comment]
Should be addressed by #854

**Comment by hainm** [comment]
hi @drroe, the PR indeed fixes the issue I mentioned. However, I've tried with different code that uses `Action_NAstruct` directly. The array length is still different. Am I supposed to call something like `SyncAction`? 

https://github.com/Amber-MD/pytraj/blob/20e82d4fb87d69abde2f489f5ccd0ed911404d56/pytraj/analysis/nucleic_acid_analysis.py#L117-L120

**Comment by hainm** [comment]
Uhm, it turns out I just need to call `Action_NAstruct.Print()`

**Comment by hainm** [comment]
Thanks Dan.

**Comment by drroe** [comment]
> Uhm, it turns out I just need to call `Action_NAstruct.Print()`

Yeah, Print is an unfortunate legacy name. A better one would probably be something like Finish. 🤷‍♂️
