### ISSUE TITLE
run_cmake for amber20tools installation

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#857]
![image](https://user-images.githubusercontent.com/48214273/96932497-fac31d00-148c-11eb-93d5-08a88fd26ea7.png)

**Comment by DDGmichigan** [comment]
Hello Dan,
Any ideas on how to get this fixed?
Thanks in advance
The set of commands I used after unzipping the amber20.tar.bz2 and amberTools20.tar.bz2 are as follows:
cd amber20_src/build
vi run_cmake
edited the DCUDA=FALSE to DCUDA=TRUE
./run_cmake
Everything looked fine
Then I did make install 
It fails after ~ 67% of the run showing the above error

**Comment by drroe** [comment]
Note that the cmake build system is not maintained by me; it is actually from a separate repo: https://github.com/Amber-MD/cmake-buildscripts

Second, that MPI is pretty old - maybe try a more recent version of mvapich/openmpi?

Last, try building cpptraj stand-alone (i.e. from the cpptraj subdir with 'configure' and '-amberlib'. If that works it further points to an issue with the cmake build and not necessarily the source code.

**Comment by DDGmichigan** [comment]
Hi Dan,
So I am about to port some of my free energy runs on a central compute facility so that I can have access to more GPUs.
I did spend a day to install AMBER20 and Amber Tools yesterday.
I was just curious and wanting to install the cpptraj standalone in the home folder.
So I did these steps:
 module load gcc/8.2.0
 module load lapack/3.8.0
 module load netcdf-fortran
 module load netcdf-c
 module load openblas/0.3.9
 module load openmpi/4.0.2
 module load lapack/3.8.0
 module load cuda/10.1.243
 then I did ./configure gnu

It  failed here 
![image](https://user-images.githubusercontent.com/48214273/97060977-39c3a200-1563-11eb-90aa-199aee639ad9.png)

**Comment by drroe** [comment]
Unless your system has compiler wrappers, it's not enough to load the modules - you need to tell cpptraj where they are. These are usually set with environment variables (e.g. `NETCDF_HOME` for NetCDF - try `env | grep -i netcdf` to try and track these down). So you'd have to do something like `./configure --with-netcdf=$NETCDF_HOME ...` etc.

**Comment by drroe** [comment]
This issue is pretty old now and hopefully was resolved; please feel free to reopen it if not.
