### ISSUE TITLE
It's time to abandon Travis-CI and move to GitHub Actions (or entirely Jenkins)

### ISSUE THREAD

**Issue by swails** [Amber-MD/cpptraj#861]
GHA will take some time, but has mac builds.  Jenkins is effectively already supported, and once the Utah machine comes online will be more reliable.

First step is to probably just turn off Travis integration.

They're basically ending support for free Open Source builds - https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by drroe** [comment]
What a bummer. Well, it was fun while it lasted. I had noticed the Mac builds were "failing" out of the blue but hadn't had time to look into it. While I don't begrudge Travis CI the right to charge for services, it seems like they could have gone about this transition a better way. 

Either option (all Jenkins or GA) is fine with me. I'll have to educate myself on GA, not sure how much work will be involved, although from the post you linked to it seems entirely doable. I'm not fully back until next week but I'll try to make some small progress (e.g. disabling Travis) until then.

**Comment by swails** [comment]
I'll whip up a GHA pipeline at some point when I get a chance (I've been working with them in my new job).  Under Microsoft's stewardship I expect GHA to be free for OSS repos.

We could alternatively use Azure pipelines, but GHA is easier to set up and manage.

**Comment by swails** [comment]
Cpptraj is on GitHub actions and off Travis
