### ISSUE TITLE
Trajectory rotation does not rotate unit cell vectors

### ISSUE THREAD

**Issue by halx** [Amber-MD/cpptraj#871]
Hi,

I was planning to RMSD fit a whole trajectory (for later analysis) to a reference structure but get the following warning:

Warning: Coordinates are being rotated and box coordinates are present.
Warning: Unit cell vectors are NOT rotated; imaging will not be possible
Warning:  after the RMS-fit is performed.

This suggests to me that I won't be able to use the transformed trajectory for the analysis I intend to do because it is dependent on proper imaging.  It is not clear to me though why the unit cell dimensions are not update accordingly.  Or maybe the question really is: where are the unit vectors stored and where does cpptraj expected to extract those from?

EDIT: I am writing out the trajectory and do the analysis in a different run.  I suppose the warning is really just relevant when imaging is done after rotation in-script?

Many thanks,
Hannes.

**Comment by drroe** [comment]
Hi,
Make sure you are running version 5.0.0 - the warning you list is from the old version, where unit cell vectors are not rotated. The new version does rotate unit cell vectors, but be aware that if you're writing a trajectory with rotated unit cell vectors that not all formats support this. In fact, currently only Gromacs Trr and Xtc formats support this - all others assume either X-aligned or symmetric (charmm) cell vectors. 
If you're using the old version, do anything that requires imaging before rms-fitting. In the new version it won't matter. The only thing to consider is if the original unit cell is X-aligned and orthorhombic, imaging is way faster, so in that case it probably pays to do any image-related things before rotation.
Hope this helps.

**Comment by drroe** [comment]
Hi @halx - did upgrading to version >= 5.0.0 solve this issue?

**Comment by halx** [comment]
Hi,

sorry for the late reply.  From a quick test the new version seems to resolve the issue.

Many thanks.
