### ISSUE TITLE
Should support "chi" as alias for "chin" for backwards compatibility.

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#88]
Recent changes to dihedral code have made it so that "chin" means nucleic chi and "chip" is protein chi. However, in ptraj "chi" just meant nucleic chi, so this should be supported.

**Comment by hainm** [comment]
>  in ptraj "chi" just meant nucleic chi, so this should be supported.

is it a good idea? ptraj itself is not perfect. 'chi' is meant for nuc is not reasonable for me.

**Comment by hainm** [comment]
anyway, we (you) need to break 'ptraj' to let users move on to cpptraj.

**Comment by drroe** [comment]
> is it a good idea? ptraj itself is not perfect. 'chi' is meant for nuc is not reasonable for me.

I agree it's not ideal, but it's not worth breaking users' existing scripts IMO. Also, until recently cpptraj had also supported 'chi' to mean 'chin', so the die has already been cast so to speak.

**Comment by hainm** [comment]
is there any easy way to summarize the deprecated warning in the end of cpptraj log?

 I saw some warning in the middle of the stdout but I think most of them will be ignored by users if the log the quite long.

**Comment by drroe** [comment]
Fixed via #132
