### ISSUE TITLE
Internal Cpptraj Error not counted as test error.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#880]
as a reminder: https://github.com/Amber-MD/pytraj/issues/1552

**Comment by drroe** [comment]
The error is raised from cpptraj here: https://github.com/Amber-MD/cpptraj/blob/74b5c2a440b9cbafc5f69f8e3c8834172864851c/src/TrajoutList.cpp#L46-L48

That function, `AddTrajout`, is called from `CpptrajState`: https://github.com/Amber-MD/cpptraj/blob/74b5c2a440b9cbafc5f69f8e3c8834172864851c/src/CpptrajState.cpp#L131

Which in turn is called from `Cpptraj` in two places; both appear to trap errors: https://github.com/Amber-MD/cpptraj/blob/74b5c2a440b9cbafc5f69f8e3c8834172864851c/src/Cpptraj.cpp#L565-L570

At every step it seems like errors are being handled. Are you sure no error is being raised to pytraj?

**Comment by hainm** [comment]
>  err = trajoutList_.AddTrajout( fname, argIn, DSL_, top ); 

I think `pytraj` does not check this `err`. :D
