### ISSUE TITLE
doc: crdframes: space sensitive

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#91]
I think you need to update doc about space sensitivity for crdframes command

`crdaction <crd set> <actioncmd> [<action args>] [crdframes <start>,<stop>,<offset>]`

**Comment by drroe** [comment]
Not sure what you mean here; isn't that exactly what is in the manual? I'm not seeing what is wrong with it.

**Comment by hainm** [comment]
You meant `[crdframes <start>,<stop>,<offset>]` implicitly says that?

**Comment by drroe** [comment]
Well there are no spaces (only commas) between `<start>`, `<stop>`, and `<offset>` in either the syntax or the example so I'm not sure how to make it more clear. If there were supposed to be spaces it would look like
```
crdframes <start> <stop> <offset>
```
If the manual lists a comma in the syntax then that comma is part of the syntax. The only characters which are not part of syntax are `<>[]{}|` and `...` (ellipsis). There probably should be a section at the very beginning of the manual that explains this.

**Comment by hainm** [comment]
ok, I see now.

**Comment by drroe** [comment]
Lets keep this open until I make those mods to the manual (I'm pretty sure it's not explained anywhere ATM).

**Comment by drroe** [comment]
Now updated in AT manual.
