### ISSUE TITLE
Tab and arrow keys don't work on cpptraj v5.1.0

### ISSUE THREAD

**Issue by Haruka-Kono** [Amber-MD/cpptraj#919]
Hello,
I installed AmberTools 21 including cpptraj v5.1.0 via conda (referred to https://ambermd.org/GetAmber.php) on remote cluster TSUBAME 3.0 (system software: https://www.t3.gsic.titech.ac.jp/en/system-software) and my local PC (openSUSE leap-15.2 on WSL2).
```
conda create -n ambertools
conda activate ambertools
conda install -c conda-forge ambertools=21 compilers

...

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
But I couldn't use command histories and tab completion on cpptraj interactive mode, as following:
```
CPPTRAJ: Trajectory Analysis. V5.1.0
    ___  ___  ___  ___
     | \/ | \/ | \/ |
    _|_/\_|_/\_|_/\_|_

| Date/time: 10/03/21 11:04:17
| Available memory: 53.207 GB

> ^[[A^[[B      ^[[C^[[D    # I pressed Up, Down, Tab, Right and Left keys in order
```
It happens both of TSUBAME and my local PC.
How should I try to fix it?  
I searched previous issues but couldn't find same problem on v5.1.0 but sorry for if it exists.

Thanks,

**Comment by drroe** [comment]
This behavior indicates that the cpptraj binary in question was compiled without the `readline` library. This was an issue with previous `cmake` builds and something I thought was fixed. It's possible the people who built the `conda` package were working with the older broken `cmake`  system. I'll raise the issue on the Amber GitLab and ping the people responsible to see if they can shed any more light.

In the meantime, you could always build your own copy of cpptraj from GitHub. Once you `git clone` or download and decompress the archive, running something like `./configure --buildlibs gnu && make install` should be enough to create a fully-functioning cpptraj. Let me know if you try this and encounter any issues.

Thanks for the report.

**Comment by Haruka-Kono** [comment]
Many thanks for your handling. I will build cpptraj as you described.

**Comment by Haruka-Kono** [comment]
@drroe Sorry for being late my feedback. I tried re-install ambertools with conda. Tab and arrow keys in cpptraj worked fine! Thank you solving this issue and tell me it.

**Comment by drroe** [comment]
Glad it's working!
