### ISSUE TITLE
for loop error in cpptraj

### ISSUE THREAD

**Issue by saikat0003** [Amber-MD/cpptraj#922]
I am using the following command to read the trajectory (https://amberhub.chpc.utah.edu/for/):
for TRAJ in cum_md1_*.nc 
trajin $TRAJ 1 last 10
done 
autoimage
trajout total.nc

My trajectory files are : cum_md1_1.nc, cum_md1_2.nc, cum_md1_3.nc etc upto 100

However, the following error is shown:

INPUT: Reading input from 'traj-strip-test.in'
  [for TRAJ in cum_md1_*.nc]
    Setting up 'for' loop.
Error: for loop type not specfied.
        1 errors encountered reading input.
TIME: Total execution time: 0.3965 seconds.
Error: Error(s) occurred during execution.

I am using " CPPTRAJ: Trajectory Analysis. V18.01".

**Comment by drroe** [comment]
> I am using " CPPTRAJ: Trajectory Analysis. V18.01".

I think the version your are using is too old. What is the result of `cpptraj --internal-version`? I think you need at least 4.9.1 for the file globbing to work in `for` loops. Try upgrading to either the most recent GitHub version or the one that ships with AmberTools 21 and see if that improves things for you.

**Comment by saikat0003** [comment]
Thank you. It works fine In the latest version of cpptraj. However,  it doesnot read the trajectory sequentially.

0: 'cum_md1_1.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 1: 'cum_md1_10.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 2: 'cum_md1_11.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 3: 'cum_md1_12.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 4: 'cum_md1_13.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 5: 'cum_md1_14.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)
 6: 'cum_md1_15.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm 6L1W_ZAFF_solv.prmtop (Orthorhombic box) (reading 500 of 5000)

**Comment by drroe** [comment]
The ordering is following Linux wildcard rules for sorting, so traj* will match traj1, then traj10, then traj2 etc. Try something like 'for T in traj?,traj??', or use a naming scheme with leading zeroes (traj01, traj02, etc).

**Comment by drroe** [comment]
Hopefully this is resolved for you. If not please feel free to reopen the issue.
