### ISSUE TITLE
Does cpptraj support numeric residue name?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#930]
> Does cpptraj support numeric residue name?

Hi,

An user asked about `pytraj` but I am asking here: https://github.com/nglviewer/nglview/issues/785#issuecomment-1011423719

**Comment by drroe** [comment]
Yes, but in order to differentiate it from a residue number you need to prepend the digits with a backslash, e.g. for a residue named `144` you would use the mask expression `:\1\4\4`.

**Comment by hainm** [comment]
Thanks @drroe. Let's track this in https://github.com/Amber-MD/pytraj/issues/1593.
