### ISSUE TITLE
RMSF info into a PDB (suggestion)

### ISSUE THREAD

**Issue by rodrigogalindo** [Amber-MD/cpptraj#935]
It would be cool that the RMSF info can be saved into an averaged PDB in the bfactor column. With this, you can 'render by attribute' in Chimera to see where in a protein has the higher fluctuations, something like this example (I just copied the results from atomic fluctuations by atom to the bfactor column of a PDB and render by attribute with the 'worms' depiction):
![image](https://user-images.githubusercontent.com/13966647/151019759-19ed6292-ae00-4b37-8c40-678de58dbf1f.png)

**Comment by drroe** [comment]
This can already be done via the `bfacdata` keyword for PDB format output for writing to the B-factor column (and `occdata` for writing to the Occupancy column):
```
	bfacdata <set>  : Use data in <set> for B-factor column.
	occdata <set>   : Use data in <set> for occupancy column.
```
Here's an example from one of the `atomicfluct` command tests (in `test/Test_AtomicFluct`):
```
trajin ../DPDP.nc
rms first mass
atomicfluct MyFluct out dpdp.fluct.dat adpout dpdp.adp.dat
atomicfluct Heavy calcadp :2-21&!@/H
average crdset MyAvg
run
writedata myfluct.adp.dat MyFluct[ADP]
crdout MyAvg dpdp.adp.pdb adpdata MyFluct[ADP] bfacdata MyFluct
crdout MyAvg heavy.adp.pdb adpdata Heavy[ADP] bfacdata Heavy
```
Note that this example also calculates and writes anisotropic B-factor data; you can omit if you don't want/need.

Let me know if this helps.

**Comment by drroe** [comment]
For reference, here are all the keywords related to B-factor/occupancy data writing for PDBs (from `help Formats trajout pdb`):
```
	bfacdefault <#> : Default value to use in B-factor column (default 0).
	occdefault <#>  : Default value to use in occupancy column (default 1).
	bfacdata <set>  : Use data in <set> for B-factor column.
	occdata <set>   : Use data in <set> for occupancy column.
	bfacbyres       : If specified assume X values in B-factor data set are residue numbers.
	occbyres        : If specified assume X values in occupancy data set are residue numbers.
	bfacscale       : If specified scale values in B-factor column between 0 and <bfacmax>.
	occscale        : If specified scale values in occupancy column between 0 and <occmax>.
	bfacmax <max>   : Max value for bfacscale.
	occmax <max>    : Max value for occscale.
	adpdata <set>   : Use data in <set> for anisotropic B-factors.
```

**Comment by rodrigogalindo** [comment]
Thanks so much! Sorry, I obviously was unaware of this option. Will use it and add a tutorial on it to amberhub.

**Comment by drroe** [comment]
Going to mark this as closed, feel free to reopen if this wasn't enough to address!
