### ISSUE TITLE
Dataset name

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#94]
sometimes I need to use `name my_dataset_name`, sometimes I don't need to.
```bash
readdata a1.dat name a1
readdata d1.dat name d1
```

```bash
symmrmsd [<name>] [<mask>] 
```

What's you  rationale here?

(I know that in python, two things below are the same
```python
do_x(traj, name='myname')
do_x(traj, 'myname')
```
)

**Comment by drroe** [comment]
The general convention is that Actions do not require explicit `name` keyword for historical reasons (i.e. that's the way it was in ptraj), while pretty much everything else (Analyses etc) does.

**Comment by hainm** [comment]
I see now.

**Comment by hainm** [comment]
@drroe 
what's about reference?

`reference avgstruct.pdb [tz2avg]`?

should this be `reference avgstruct.pdb name [tz2avg]`?

**Comment by drroe** [comment]
Heheh, nope, because that is technically a "tag" (same thing with 'parm'). The reason is that this syntax is from before the time when reference coords were part of the main DataSetList. Changing it will break backwards compatibility for very little benefit.

**Comment by hainm** [comment]
> Heheh, nope, because that is technically a "tag" (same thing with 'parm'). 

To me, tag or name is the same. Just a way to identify the object.

> Changing it will break backwards compatibility for very little benefit.

I agree. Just ask because I am curious.

**Comment by drroe** [comment]
> To me, tag or name is the same. Just a way to identify the object.

For reference structures it actually is the same now - but previously when reference structures had their own list the tag was something else.
