### ISSUE TITLE
imaging issue with OpenMM simulation

### ISSUE THREAD

**Issue by rpavlovicz** [Amber-MD/cpptraj#954]
I'm having trouble imaging some snapshots from a trajectory of a two-component protein complex that was setup with LEaP using a truncated octahedron water box (solvateoct) and run with OpenMM. About 5% of the snapshots fail to image correctly. So far, I have tried autoimage with the anchor as either the first or second protein:

`autoimage anchor :205-380`
or
`autoimage anchor :1-204`

Both have the same number of frames imaged incorrectly. 

I do get some warning messages when running cpptraj:

```
Warning: trajectory_st.dcd: Reported number of frames in DCD file is 8839,
Warning:	actual number of frames is 8844. Only reading 8844 frames.
	Version >= 22; assuming shape matrix is stored.
Warning: Trajectory box type is 'Rhombohedral' but topology box type is 'Truncated octahedron'.
Warning: Setting topology box information from trajectory.
```

I'm not sure if the wrapping done with OpenMM with the Amber topology is part of the problem here. All wrapped output from OpenMM makes the input octahedron look rectangular, but I have been assured that this is just a wrapping artifact. 

Any ideas of how to get all my frames imaged correctly?

**Comment by drroe** [comment]
Can you attach a topology and 1 or 2 frames (or as many as you can give me) of coordinates that illustrate the issue so I can reproduce it? Thanks.

**Comment by rpavlovicz** [comment]
Hey Daniel,

I've attached a zip with the prmtop and 4 frames that capture the problem (the first two frames image correctly, while the second two do not). Thanks for taking a look!

[topology_and_snaps.zip](https://github.com/Amber-MD/cpptraj/files/8226302/topology_and_snaps.zip)

**Comment by drroe** [comment]
Thanks for the files. The problem appears to be in how OpenMM is writing unit cell information to DCD files. As you probably know, DCD is the binary charmm trajectory format. In charmm versions < 22, unit cell information was stored as X-aligned with 3x lengths and 3x angles (A, B, C, alpha, beta, gamma). From version 22 and up however, charmm stores the symmetric shape matrix (upper-right + diagonal, so still 6 elements). It seems that although OpenMM writes DCD trajectories with the version bit set to >= 22, it is still storing X-aligned unit cell values.

The good news is that you can work around this in cpptraj by telling it to assume the X-aligned unit cell values are stored via the `ucell` keyword for the `trajin` command, e.g.:
```
trajin selected_frames.dcd ucell
```
I tested this on the files you sent me and it seems to work well. Let me know if it works for your entire trajectory.

**Comment by rpavlovicz** [comment]
Thanks so much, Daniel. This worked perfectly! I'll let the OpenMM people know about this -- not sure if their DCD output format is purposeful.

![rmsd_plot_2](https://user-images.githubusercontent.com/8700070/157928094-cef2741b-fca7-475e-8e39-30d7bce271cc.png)

**Comment by rpavlovicz** [comment]
Also, if it's ok with you, can I quote what you said about cpptraj's expected dcd ucell format over at the OpenMM repo?

**Comment by drroe** [comment]
Glad it's working!

> Also, if it's ok with you, can I quote what you said about cpptraj's expected dcd ucell format over at the OpenMM repo?

Sure, go ahead; feel free to tag me as well @drroe
