### ISSUE TITLE
Cpptraj install failed with ./configure gnu

### ISSUE THREAD

**Issue by debarati31** [Amber-MD/cpptraj#974]
![image](https://user-images.githubusercontent.com/106696539/174653555-ca2d2fcf-2ba1-4790-b80c-44de1fe913c9.png)
Cpptraj installation issue

**Comment by drroe** [comment]
This usually happens because CPPTRAJ is pulling in an external library that was compiled with the position independent code flag. Try to re-configure with the `-shared` option and recompile.

**Comment by debarati31** [comment]
Hi Dan
Are you suggesting this:
./configure -amberlib gnu -shared

**Comment by drroe** [comment]
Yes. Alternatively you can have cpptraj try to build what libraries it needs itself with:
```
./configure -fftw3 --buildlibs gnu
```

**Comment by debarati31** [comment]
Still fails the make install step.
Thanks
Debarati

**Comment by drroe** [comment]
Which fails? Both?

**Comment by debarati31** [comment]
The configure step is successful and it says its fine but the make install
throws a sea of errors. Never happened with me before as I have been
installing cpptraj in so many clusters previously.

ddasgupta:cpptraj$ ./configure -fftw3 --buildlibs gnu
  fftw3 enabled.

  Testing C++ compiler: OK
  Testing C compiler: OK
  Testing Fortran compiler: OK
  Testing basic C++11 support: OK
  Testing system headers for C++11 support: OK
Enabled libraries will be built if not present.
  Checking BZLIB: OK
  Checking ZLIB: OK
  Checking NetCDF:   Checking for bundled NetCDF:     Downloading netcdf...
--2022-06-21 15:09:55--
ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.6.1.tar.gz
           => ‘netcdf-4.6.1.tar.gz’
Resolving ftp.unidata.ucar.edu (ftp.unidata.ucar.edu)... 128.117.149.10
Connecting to ftp.unidata.ucar.edu (ftp.unidata.ucar.edu)|128.117.149.10|:21...
connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/netcdf ... done.
==> SIZE netcdf-4.6.1.tar.gz ... 5693557
==> PASV ... done.    ==> RETR netcdf-4.6.1.tar.gz ... done.
Length: 5693557 (5.4M) (unauthoritative)

netcdf-4.6.1.tar.gz
100%[===================================================================================================================>]
  5.43M  13.6MB/s    in 0.4s

2022-06-21 15:09:55 (13.6 MB/s) - ‘netcdf-4.6.1.tar.gz’ saved [5693557]

    Unpacking netcdf...
    Configuring netcdf... Success.
    MAKE_COMMAND is not set; set to 'make -j2'
    Compiling netcdf (may be time-consuming)... Success.
  Checking built NetCDF: OK
  Checking LAPACK/BLAS: OK
  Checking FFTW3: OK
  Checking gnu RPATH type for libsander: OK

Configuration summary:
  Build type: Serial
  Options: netcdf bzlib tng zlib arpack lapack blas fftw3 readline xdrfile
sanderlib
  Target platform: Linux, 64-bit.
  gnu compilers in use.
  C++11 support enabled.
  PME support enabled.
  Compiler optimizations are on.

Cleaning source directory.

--------------------------------------------------------------------------------
An environment resource file for CPPTRAJ has been created:
  /storage/debarati/cpptraj/cpptraj.sh
You may 'source' this file to set up your environment for CPPTRAJ.
--------------------------------------------------------------------------------

CPPTRAJ configuration complete.

ddasgupta:cpptraj$ make install

**Comment by drroe** [comment]
Try adding the '-shared' flag.

**Comment by drroe** [comment]
Did the -shared flag work for you?
