### ISSUE TITLE
cpptraj installation issues from zipped source code

### ISSUE THREAD

**Issue by debarati31** [Amber-MD/cpptraj#987]
Hi I am installing cpptraj latest Github version using command ./configure gnu
Then make install
I see errors at this stage:
![image](https://user-images.githubusercontent.com/106696539/186038550-80d7e5d3-1cdf-4622-96ba-ac17497c2a68.png)

and I see a lot of warning notifications 
![image](https://user-images.githubusercontent.com/106696539/186038637-16039bbe-88d6-43a0-b77c-7d354c0f1e92.png)

**Comment by debarati31** [comment]
![image](https://user-images.githubusercontent.com/106696539/186040061-85e09938-02dd-4d29-9799-70f8dffa41da.png)

**Comment by drroe** [comment]
The warnings are innocuous and can be ignored.

The "relocation" error means one or more of the libraries cpptraj is being linked to has been compiled with position-independent code. Re-configure cpptraj with the `-shared` flag to turn on position independent code and try to recompile.

**Comment by drroe** [comment]
Did the -shared flag work for you?

**Comment by debarati31** [comment]
Yes it did!
Thanks
Debarati
