### ISSUE TITLE
Question about the unit of forces in the Amber NetCDF trajectories.

### ISSUE THREAD

**Issue by initqp** [Amber-MD/cpptraj#989]
Hi all, I found that the unit of the forces in the Amber NetCDF trajectories generated by CppTraj is `kilocalorie/mole/angstrom`. In contrast, in [Amber's convention](https://ambermd.org/netcdf/nctraj.xhtml), the unit of the forces is specified as `amu*angstrom/picosecond^2`. If I did not make a mistake, these seem to be two different units. So my question is, which unit should I believe? Thanks a lot!

**Comment by drroe** [comment]
> in [Amber's convention](https://ambermd.org/netcdf/nctraj.xhtml), the unit of the forces is specified as amu*angstrom/picosecond^2

The website is wrong and what's listed in the NetCDF trajectory is correct. While technically you can express force as `energy / distance` (as in the NetCDF file) or as `mass * acceleration` (as on the website), in AKMA units (used by Amber) the unit of time is actually `1/20.455 ps`.

**Comment by initqp** [comment]
Oh, okay, I see. Thanks a lot for the answer! I am just curious, why does Amber not use `angstrom/AKMA_time` as the velocity unit in NetCDF trajectories?

**Comment by drroe** [comment]
It does; this is what the `scale_factor` attribute is for when you `ncdump` a trajectory with velocities:
```
	float velocities(frame, atom, spatial) ;
		velocities:units = "angstrom/picosecond" ;
		velocities:scale_factor = 20.455 ;
```

**Comment by initqp** [comment]
I could understand it now, many thanks😊

**Comment by drroe** [comment]
Glad to help!
