### ISSUE TITLE
problem regarding "change" command in cpptraj

### ISSUE THREAD

**Issue by saikat0003** [Amber-MD/cpptraj#994]
Dear all,

I have converted my topology file with added PDB information (like chain ID and renumbering PDB) using "parmed". However, the previously mentioned information still missing in  output file (like rmsf). I have gone through the following link:
http://archive.ambermd.org/201709/0275.html
http://archive.ambermd.org/202106/0042.html

Here is my steps:

parm rgs01-1.rgs01.parm7
addPDB rgs01.pdb
parmout rgs01-1-mod.rgs01.parm7
go

change  oresnums of :1-317 min 32 max 348 
change  chainid of :1-317 to A
change  oresnums of :318-449 min 60 max 191
change  chainid of :318-449 to D 
out remap.dat

It shows the error:
        ..................................................................................
	Changing chain ID of residue TYR:441 from 'D' to 'D'
	Changing chain ID of residue LEU:442 from 'D' to 'D'
	Changing chain ID of residue ASN:443 from 'D' to 'D'
	Changing chain ID of residue LEU:444 from 'D' to 'D'
	Changing chain ID of residue LEU:445 from 'D' to 'D'
	Changing chain ID of residue ASN:446 from 'D' to 'D'
	Changing chain ID of residue ASP:447 from 'D' to 'D'
	Changing chain ID of residue LEU:448 from 'D' to 'D'
	Changing chain ID of residue GLN:449 from 'D' to 'D'
  [out remap.dat]
Warning: Data set 'outremap.dat' not found.
Error: Data set with name 'outremap.dat' not found.
'out remap.dat': Invalid command or expression.
	1 errors encountered reading input.
TIME: Total execution time: 0.0169 seconds.
Error: Error(s) occurred during execution.

I want to put information like residue number and chain id in the topology file. 

Thanks and Regards,

Saikat Pal

**Comment by drroe** [comment]
The error arises because 'out' is not a recognized command. What did you intend with 'out remap.dat'? By itself, 'out' is not a command, though it is a keyword for many other commands.

**Comment by drroe** [comment]
Perhaps what you wanted instead of `out` was `parmwrite out <file>` to write a topology?

**Comment by drroe** [comment]
Did `parwrite out` work for you?

**Comment by drroe** [comment]
Since there hasn't been any movement on this in a while I'm going to close it. Feel free to reopen if it is still an issue.
